"""Frozen synthetic DDL from 2.x source 286396e; no backend imports.

Schema drift is checked by test_v3_migration_harness.py.
"""

LEDGER_DDL = ('\n'
 'CREATE TABLE IF NOT EXISTS doc (\n'
 '  key  TEXT PRIMARY KEY,\n'
 '  val  TEXT NOT NULL\n'
 ') WITHOUT ROWID;\n'
 'CREATE TABLE IF NOT EXISTS nodes (\n'
 '  id   TEXT PRIMARY KEY,\n'
 '  ord  INTEGER NOT NULL,\n'
 '  val  TEXT NOT NULL\n'
 ') WITHOUT ROWID;\n'
 'CREATE TABLE IF NOT EXISTS log_d (\n'
 '  seq   INTEGER PRIMARY KEY AUTOINCREMENT,\n'
 '  sect  TEXT NOT NULL,\n'
 '  owner TEXT NOT NULL,\n'
 '  at    TEXT,\n'
 '  val   TEXT NOT NULL\n'
 ');\n'
 'CREATE INDEX IF NOT EXISTS ix_log_d ON log_d(sect, owner, seq);\n'
 'CREATE TABLE IF NOT EXISTS log_l (\n'
 '  seq   INTEGER PRIMARY KEY AUTOINCREMENT,\n'
 '  sect  TEXT NOT NULL,\n'
 '  at    TEXT,\n'
 '  val   TEXT NOT NULL\n'
 ');\n'
 'CREATE INDEX IF NOT EXISTS ix_log_l ON log_l(sect, seq);\n'
 'CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, val TEXT NOT NULL);\n')

SIDECAR_DDL = {'transcript-records.sqlite3': 'CREATE TABLE IF NOT EXISTS transcript_sources (\n'
                               '            source TEXT PRIMARY KEY, path TEXT NOT NULL, epoch '
                               'INTEGER NOT NULL,\n'
                               '            signature TEXT, lower_byte INTEGER NOT NULL, '
                               'upper_byte INTEGER NOT NULL);\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_records (\n'
                               '            source TEXT NOT NULL, epoch INTEGER NOT NULL, position '
                               'INTEGER NOT NULL,\n'
                               '            body TEXT NOT NULL, PRIMARY '
                               'KEY(source,epoch,position)) WITHOUT ROWID;\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_order (\n'
                               '            source TEXT NOT NULL, event TEXT NOT NULL, rank REAL '
                               'NOT NULL,\n'
                               '            PRIMARY KEY(source,event)) WITHOUT ROWID;\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_owned (source TEXT '
                               'PRIMARY KEY);\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_views (\n'
                               '            source TEXT NOT NULL, position INTEGER NOT NULL, body '
                               'TEXT NOT NULL,\n'
                               '            PRIMARY KEY(source,position)) WITHOUT ROWID;\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_tool_results (\n'
                               '            source TEXT NOT NULL, tool TEXT NOT NULL, epoch '
                               'INTEGER NOT NULL,\n'
                               '            position INTEGER NOT NULL, body TEXT NOT NULL,\n'
                               '            PRIMARY KEY(source,tool)) WITHOUT ROWID;\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_native_rows (\n'
                               '            source TEXT NOT NULL, identity TEXT NOT NULL, digest '
                               'TEXT NOT NULL,\n'
                               '            PRIMARY KEY(source,identity,digest)) WITHOUT ROWID;\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_spooled (\n'
                               '            source TEXT NOT NULL, record_id TEXT NOT NULL,\n'
                               '            PRIMARY KEY(source,record_id)) WITHOUT ROWID;\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_anchors (\n'
                               '            source TEXT PRIMARY KEY, upper INTEGER NOT NULL, '
                               'digest TEXT NOT NULL);\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_order_meta (\n'
                               '            source TEXT PRIMARY KEY, epoch INTEGER NOT NULL);\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_journal_ids (\n'
                               '            sid TEXT PRIMARY KEY, source TEXT NOT NULL);\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_view_rows (\n'
                               '            source TEXT NOT NULL, digest TEXT NOT NULL, at TEXT '
                               'NOT NULL,\n'
                               '            key TEXT NOT NULL, body TEXT NOT NULL);\n'
                               '          CREATE UNIQUE INDEX IF NOT EXISTS '
                               'transcript_view_rows_key\n'
                               '            ON transcript_view_rows(source,digest,at,key);\n'
                               '          CREATE TABLE IF NOT EXISTS transcript_view_sources (\n'
                               '            source TEXT PRIMARY KEY, path TEXT NOT NULL,\n'
                               '            upper INTEGER NOT NULL, anchor TEXT NOT NULL);\n'
                               '          CREATE TABLE IF NOT EXISTS assistant_messages (\n'
                               '            ordinal INTEGER PRIMARY KEY AUTOINCREMENT,\n'
                               '            scope TEXT NOT NULL, id TEXT NOT NULL, body TEXT NOT '
                               'NULL,\n'
                               '            materialized INTEGER NOT NULL DEFAULT 0, '
                               'UNIQUE(scope,id));\n'
                               '          CREATE INDEX IF NOT EXISTS assistant_messages_pending\n'
                               '            ON assistant_messages(scope,materialized,ordinal);\n'
                               '          CREATE TABLE IF NOT EXISTS assistant_receipts (\n'
                               '            scope TEXT NOT NULL, id TEXT NOT NULL, PRIMARY '
                               'KEY(scope,id)) WITHOUT ROWID;',
 'reply-events.sqlite3': 'CREATE TABLE IF NOT EXISTS events (org TEXT, agent TEXT, generation '
                         'INTEGER, id TEXT, text TEXT, scope TEXT, PRIMARY '
                         'KEY(org,agent,generation,id));',
 'file-deliveries.db': 'CREATE TABLE IF NOT EXISTS deliveries (id TEXT PRIMARY KEY, fingerprint '
                       'TEXT NOT NULL, result TEXT);',
 'tool-waits.db': 'CREATE TABLE IF NOT EXISTS operations (id TEXT PRIMARY KEY, record TEXT NOT '
                  'NULL);\n'
                  'CREATE TABLE IF NOT EXISTS dead_letters (id TEXT PRIMARY KEY, record TEXT NOT '
                  'NULL);'}
