//! The P03 prototype PostgreSQL schema (`engine/native/store/CONTRACT-M1.md` §7).
//!
//! Ordered SQL migrations are embedded as text. The WS1 runner applies
//! [`MIGRATIONS`] in order as the admin role and checks each checksum against
//! its range's `ranges/<range>.sha256`; the runtime role gets DML only. A
//! landed migration is immutable: its checksum is pinned, and a test fails if
//! the file changes.
//!
//! **Ranges.** Each workstream owns a number range and contributes only its own
//! files: `migrations/NNNN_<name>.sql`, `ranges/<range>.range` (its tables and
//! its entries for the publication and lint lists) and `ranges/<range>.sha256`.
//! `build.rs` collects them, so parallel ranges never edit a shared line (lead
//! request 2026-09-25). The public lists below are unions over every range.
//!
//! This crate has no driver and runs no SQL. [`lint`] is a static checker for
//! the conventions of CONTRACT-M1 §2; it parses only the subset of DDL these
//! files use and is not a SQL parser. Proving the DDL is accepted by
//! PostgreSQL needs a WS1 dev cluster.

pub mod lint;

/// One migration file.
#[derive(Clone, Copy, Debug)]
pub struct Migration {
    pub version: u32,
    pub name: &'static str,
    pub file: &'static str,
    pub sql: &'static str,
}

impl Migration {
    /// The minimum store-writer version that understands the schema once this
    /// migration is applied: the optional FIRST-line header
    /// `-- orgtree:min_writer=N` (covered by the checksum), else 1. The WS1
    /// runner reads the same header from the file at run time.
    pub fn min_writer(&self) -> u32 {
        header_min_writer(self.sql)
    }
}

pub fn header_min_writer(sql: &str) -> u32 {
    let first = normalized(sql).lines().next().unwrap_or("").trim().to_string();
    first.strip_prefix("-- orgtree:min_writer=").and_then(|n| n.trim().parse().ok()).unwrap_or(1)
}

/// One migration RANGE (`ranges/<range>.range` + `ranges/<range>.sha256`).
#[derive(Clone, Copy, Debug)]
pub struct RangeDef {
    pub file: &'static str,
    pub name: &'static str,
    pub first: u32,
    pub last: u32,
    /// Every table this range's migrations create.
    pub tables: &'static [&'static str],
    /// `<sha256 hex>  <file>` per line, this range's files only.
    pub manifest: &'static str,
}

impl RangeDef {
    pub fn contains(&self, version: u32) -> bool {
        version >= self.first && version <= self.last
    }

    pub fn migrations(&self) -> impl Iterator<Item = &'static Migration> + '_ {
        MIGRATIONS.iter().filter(move |m| self.contains(m.version))
    }

    /// The manifest this range's current files would produce.
    pub fn computed_manifest(&self) -> String {
        let mut out = String::new();
        for m in self.migrations() {
            out.push_str(&sha256_hex(m.sql));
            out.push_str("  ");
            out.push_str(m.file);
            out.push('\n');
        }
        out
    }
}

// MIGRATIONS, RANGE_DEFS, RANGES and the union lists: PUBLISHED, EXCLUDED,
// HIGH_RATE_TABLES, RECEIVER_HEAD_TABLES, SOURCE_SIDE_TABLES,
// INSTALLATION_TABLES, ORG_WIDE_TABLES, RECEIPT_PUBLISHED_COLUMNS and
// DECLARED_SERVER_SIDE — generated by build.rs from migrations/ and ranges/.
include!(concat!(env!("OUT_DIR"), "/generated.rs"));

/// Content with CR removed, so the checksum does not depend on the checkout's
/// line endings (`.gitattributes` is `* text=auto eol=crlf`).
///
/// HASHING RULE, shared verbatim with the WS1 migration runner (which reads
/// `migrations/` and `ranges/*.sha256` at run time): sha256 over the file's
/// bytes with EVERY carriage return (CR) removed, nothing else changed (no
/// trimming, no BOM handling). The runner applies exactly those CR-stripped
/// bytes. Changing this function requires telling WS1 first.
pub fn normalized(sql: &str) -> String {
    sql.replace('\r', "")
}

pub fn sha256_hex(sql: &str) -> String {
    use orgtree_op_receipt_codec::sha256::{hex, sha256};
    hex(&sha256(normalized(sql).as_bytes()))
}

/// Every range's computed manifest, in range order.
pub fn computed_manifest() -> String {
    RANGE_DEFS.iter().map(|r| r.computed_manifest()).collect()
}

/// Every range's pinned manifest, concatenated in range order.
pub fn pinned_manifest() -> String {
    RANGE_DEFS.iter().map(|r| r.manifest.replace('\r', "")).collect()
}

/// The whole schema, parsed for linting.
pub fn schema() -> lint::Schema {
    let mut s = lint::Schema::default();
    for m in MIGRATIONS {
        s.add(m.file, m.sql);
    }
    s
}

/// The schema one range's migrations create.
pub fn range_schema(r: &RangeDef) -> lint::Schema {
    let mut s = lint::Schema::default();
    for m in r.migrations() {
        s.add(m.file, m.sql);
    }
    s
}
