//! Collects the schema from files so parallel migration ranges never edit a
//! shared line (lead request 2026-09-25):
//!
//! * `migrations/NNNN_<name>.sql` — every migration, discovered and ordered by
//!   number;
//! * `ranges/<range>.range` — one per workstream range: its number span, the
//!   tables its migrations create, and its entries for the publication and
//!   lint lists;
//! * `ranges/<range>.sha256` — the pinned checksums of that range's files.
//!
//! It generates `$OUT_DIR/generated.rs` with the same public constants the
//! crate always exposed (`MIGRATIONS`, `PUBLISHED`, `HIGH_RATE_TABLES`, ...),
//! each the union over ranges. std only.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

#[derive(Default)]
struct Range {
    file: String,
    name: String,
    first: u32,
    last: u32,
    lists: Vec<(String, Vec<String>)>,
    server_side: Vec<(String, String, Vec<String>)>,
}

impl Range {
    fn list(&self, key: &str) -> Vec<String> {
        self.lists.iter().filter(|(k, _)| k == key).flat_map(|(_, v)| v.clone()).collect()
    }
}

const LIST_KEYS: &[&str] = &[
    "tables", "published", "excluded", "high_rate", "receiver_heads", "source_side", "installation", "org_wide",
    "receipt_published_columns",
];

fn parse_range(file: &str, text: &str) -> Range {
    let mut r = Range { file: file.to_string(), ..Range::default() };
    for (n, raw) in text.lines().enumerate() {
        let line = raw.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let (k, v) = line.split_once('=').unwrap_or_else(|| panic!("{file}:{}: expected key = value", n + 1));
        let (k, v) = (k.trim(), v.trim());
        match k {
            "name" => r.name = v.to_string(),
            "first" => r.first = v.parse().unwrap_or_else(|_| panic!("{file}:{}: first is not a number", n + 1)),
            "last" => r.last = v.parse().unwrap_or_else(|_| panic!("{file}:{}: last is not a number", n + 1)),
            "server_side" => {
                let parts: Vec<&str> = v.split(" | ").collect();
                assert!(parts.len() == 3, "{file}:{}: server_side = <object> | <relations, comma-separated> | <what it does>", n + 1);
                let rels = parts[1].split(',').map(str::trim).filter(|s| !s.is_empty()).map(str::to_string).collect();
                r.server_side.push((parts[0].trim().to_string(), parts[2].trim().to_string(), rels));
            }
            k if LIST_KEYS.contains(&k) => r.lists.push((k.to_string(), v.split_whitespace().map(str::to_string).collect())),
            other => panic!("{file}:{}: unknown key {other:?}", n + 1),
        }
    }
    assert!(!r.name.is_empty() && r.first > 0 && r.last >= r.first, "{file}: needs name, first and last");
    r
}

fn strs(v: &[String]) -> String {
    let mut s = String::from("&[");
    for x in v {
        write!(s, "{x:?}, ").unwrap();
    }
    s.push(']');
    s
}

fn main() {
    let root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let mig_dir = root.join("migrations");
    let ranges_dir = root.join("ranges");
    println!("cargo:rerun-if-changed={}", mig_dir.display());
    println!("cargo:rerun-if-changed={}", ranges_dir.display());

    let mut migrations: Vec<(u32, String, String)> = Vec::new();
    for e in fs::read_dir(&mig_dir).expect("migrations/") {
        let p = e.unwrap().path();
        println!("cargo:rerun-if-changed={}", p.display());
        let file = p.file_name().unwrap().to_string_lossy().to_string();
        let Some(stem) = file.strip_suffix(".sql") else { continue };
        let (num, name) = stem.split_once('_').unwrap_or_else(|| panic!("migration {file} is not NNNN_<name>.sql"));
        assert!(num.len() == 4 && num.bytes().all(|b| b.is_ascii_digit()), "migration {file} is not NNNN_<name>.sql");
        migrations.push((num.parse().unwrap(), name.to_string(), file));
    }
    migrations.sort();

    let mut ranges: Vec<Range> = Vec::new();
    let mut manifests: Vec<(String, String)> = Vec::new();
    for e in fs::read_dir(&ranges_dir).expect("ranges/") {
        let p = e.unwrap().path();
        println!("cargo:rerun-if-changed={}", p.display());
        let file = p.file_name().unwrap().to_string_lossy().to_string();
        if let Some(stem) = file.strip_suffix(".range") {
            ranges.push(parse_range(&file, &fs::read_to_string(&p).unwrap()));
            manifests.push((stem.to_string(), p.with_extension("sha256").display().to_string()));
        }
    }
    ranges.sort_by_key(|r| r.first);

    let mut out = String::new();
    out.push_str("// @generated by build.rs from migrations/ and ranges/. Do not edit.\n\n");
    out.push_str("pub const MIGRATIONS: &[Migration] = &[\n");
    for (v, name, file) in &migrations {
        let abs = mig_dir.join(file).display().to_string();
        writeln!(out, "    Migration {{ version: {v}, name: {name:?}, file: {file:?}, sql: include_str!({abs:?}) }},").unwrap();
    }
    out.push_str("];\n\n");

    out.push_str("pub const RANGE_DEFS: &[RangeDef] = &[\n");
    for r in &ranges {
        let (_, sha_path) = manifests.iter().find(|(stem, _)| format!("{stem}.range") == r.file).unwrap();
        assert!(Path::new(sha_path).exists(), "{} has no matching .sha256 file", r.file);
        write!(
            out,
            "    RangeDef {{ file: {:?}, name: {:?}, first: {}, last: {}, tables: {}, manifest: include_str!({:?}) }},\n",
            r.file,
            r.name,
            r.first,
            r.last,
            strs(&r.list("tables")),
            sha_path
        )
        .unwrap();
    }
    out.push_str("];\n\n");

    out.push_str("pub const RANGES: &[(&str, u32, u32)] = &[\n");
    for r in &ranges {
        writeln!(out, "    ({:?}, {}, {}),", r.name, r.first, r.last).unwrap();
    }
    out.push_str("];\n\n");

    for (konst, key, doc) in [
        ("PUBLISHED", "published", "Tables WS6 may publish (CONTRACT-M1 §7), over every range."),
        ("EXCLUDED", "excluded", "Tables never published, over every range."),
        ("HIGH_RATE_TABLES", "high_rate", "High-rate tables (lint R9), over every range."),
        ("RECEIVER_HEAD_TABLES", "receiver_heads", "Receiver head rows (lint R10), over every range."),
        ("SOURCE_SIDE_TABLES", "source_side", "Source-side tables (lint R10), over every range."),
        ("INSTALLATION_TABLES", "installation", "Tables without org_id (lint R1), over every range."),
        ("ORG_WIDE_TABLES", "org_wide", "One-row-per-org tables (lint R9), over every range."),
        ("RECEIPT_PUBLISHED_COLUMNS", "receipt_published_columns", "Safe identifier columns of operation_receipts."),
    ] {
        let all: Vec<String> = ranges.iter().flat_map(|r| r.list(key)).collect();
        writeln!(out, "/// {doc}\npub const {konst}: &[&str] = {};\n", strs(&all)).unwrap();
    }

    out.push_str("/// Server-side statements (triggers, functions) and the relations they touch, over every range.\n");
    out.push_str("pub const DECLARED_SERVER_SIDE: &[(&str, &str, &[&str])] = &[\n");
    for r in &ranges {
        for (obj, what, rels) in &r.server_side {
            writeln!(out, "    ({obj:?}, {what:?}, {}),", strs(rels)).unwrap();
        }
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").unwrap()).join("generated.rs");
    fs::write(dest, out).unwrap();
}
