import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import test from 'node:test'

const root = path.resolve(import.meta.dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')

test('frameless windows expose only sender-scoped window controls', () => {
  const main = read('apps/desktop/main/index.ts')
  const preload = read('apps/desktop/preload/index.ts')
  const contracts = read('packages/contracts/index.ts')
  assert.match(main, /frame: false/)
  assert.match(main, /desktop:window-minimize/)
  assert.match(main, /desktop:window-toggle-maximize/)
  assert.match(main, /desktop:window-close/)
  assert.match(main, /desktop:window-controls-state/)
  assert.match(main, /assertNativeSender\(event, main, engine\.origin\)/)
  assert.match(preload, /minimizeWindow: \(\) => ipcRenderer\.invoke\('desktop:window-minimize'\)/)
  assert.match(preload, /getWindowControlsState: \(\) => ipcRenderer\.invoke\('desktop:window-controls-state'\)/)
  assert.match(preload, /toggleMaximizeWindow: \(\) => ipcRenderer\.invoke\('desktop:window-toggle-maximize'\)/)
  assert.match(preload, /closeWindow: \(\) => ipcRenderer\.invoke\('desktop:window-close'\)/)
  assert.match(contracts, /minimizeWindow\(\): Promise<void>/)
  assert.match(contracts, /toggleMaximizeWindow\(\): Promise<void>/)
  assert.match(contracts, /closeWindow\(\): Promise<void>/)
})

test('renderer keeps interactive controls out of drag regions and offers top/bottom margins', () => {
  const app = read('apps/desktop/renderer/src/App.tsx')
  const controls = read('apps/desktop/renderer/src/window-controls.tsx')
  const styles = read('apps/desktop/renderer/src/styles.css')
  const nativeProbe = read('tests/window-controls-native.probe.ts')
  assert.match(app, /<WindowControls \/>/)
  assert.match(app, /<header className="orgbar">[\s\S]*<WindowControls \/>/)
  assert.match(app, /<h1>[\s\S]*showControls && <WindowControls \/>[\s\S]*<\/h1>/)
  assert.match(app, /<Onboarding windowControls=\{<WindowControls \/>\}>/)
  assert.match(app, /fallback-orgbar/)
  assert.match(app, /orgPanel\(false\)/)
  assert.match(controls, /aria-label="Minimize window"/)
  assert.match(controls, /aria-label="Refresh app view"/)
  assert.match(controls, /aria-label=\{state\.maximized \? 'Restore window' : 'Maximize window'\}/)
  assert.match(controls, /aria-label="Close window"/)
  assert.match(app, /!desktop\(\) && <button type="button" className="iconbtn" title="refresh app view"/)
  assert.equal((app.match(/className="window-drag-margin"/g) ?? []).length, 2, 'top and bottom canvas margins')
  assert.match(app, /desktop\(\) && <div className="window-drag-margin"/)
  assert.match(styles, /\.window-controls \{[^}]*-webkit-app-region: no-drag/)
  assert.match(styles, /\.window-controls \{[^}]*flex: 0 0 auto[^}]*flex-wrap: nowrap/)
  assert.match(styles, /\.window-control \{[^}]*flex: 0 0 46px/)
  assert.match(styles, /@media [(]min-width: 600px[)] and [(]max-width: 780px[)]/)
  assert.match(styles, /padding-right: 192px/)
  assert.match(styles, /\.orgbar button, \.orgbar a, \.orgbar input, \.orgbar select, \.orgbar \.chip/)
  assert.match(styles, /\.canvas-stage > \.viewport \{[^}]*-webkit-app-region: no-drag/)
  assert.match(nativeProbe, /native BrowserWindow state operations only/)
})
