const fs=require('node:fs'),path=require('node:path')
const {BrowserWindow}=require('electron')
const styleProbe=`(()=>({compatMode:document.compatMode,fontsStatus:document.fonts.status,sheets:[...document.styleSheets].map(s=>s.href),chain:['body','.movable-surface','.movable-content','.movable-events','.desk-body','.msg','.cc-composer textarea'].map(selector=>{const e=document.querySelector(selector);if(!e)return{selector,missing:true};const s=getComputedStyle(e);return{selector,fontFamily:s.fontFamily,fontSize:s.fontSize,font:s.font,lineHeight:s.lineHeight,sans:s.getPropertyValue('--sans'),color:s.color,background:s.backgroundColor}})}))()`
exports.download=async({root,evaluate,main,assert})=>{
  const expected=await evaluate(`fetch('/api/orgs/import-demo/documents/import-report/download').then(async r=>({body:await r.text(),name:r.headers.get('Content-Disposition')}))`)
  assert.equal(expected.body,'# Imported document\nThis synthetic document must survive the copy.')
  const filename=expected.name.match(/filename="([^"]+)"/)[1]
  const folder=path.join(root,'downloads');fs.mkdirSync(folder,{recursive:true})
  const downloaded=new Promise((resolve,reject)=>{
    const timer=setTimeout(()=>reject(Error('Native download did not finish')),15000)
    main.webContents.session.once('will-download',(_event,item,contents)=>{
      const name=item.getFilename();item.setSavePath(path.join(folder,name))
      item.once('done',(_event,state)=>{clearTimeout(timer);if(state!=='completed')reject(Error('Download '+state));else resolve({name,owner:contents.id})})
    })
  })
  assert.equal(await evaluate(`(()=>{const a=document.querySelector('.document-download');if(!a)return false;a.click();return true})()`),true)
  const result=await downloaded;assert.equal(result.name,filename)
  assert.equal(fs.readFileSync(path.join(folder,result.name),'utf8'),expected.body)
  fs.writeFileSync(path.join(root,'source-download.json'),JSON.stringify({filename:result.name,bytes:Buffer.byteLength(expected.body),nativeDownload:true,sourceBytesMatch:true}))
}
exports.reply=async({root,evaluate,waitFor,capture,main,assert})=>{
  const source=await evaluate(`(()=>{const e=[...document.querySelectorAll('[data-reply-event]')].find(e=>e.textContent.trim()==='Copied V1 history for active.');if(!e)return null;const r=e.getBoundingClientRect();e.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:r.x+15,clientY:r.y+8}));return {id:e.getAttribute('data-reply-event'),text:e.textContent.trim()}})()`)
  assert.ok(source?.id.startsWith('reply_'))
  await capture(main,'reply-context-menu')
  assert.equal(await evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(b=>b.textContent==='Reply');if(!b||b.disabled)return false;b.click();return true})()`),true)
  assert.equal(await waitFor(`document.querySelector('.reply-preview blockquote')?.textContent==='Copied V1 history for active.'`),true)
  await evaluate(`(()=>{const t=document.querySelector('.cc-composer textarea');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(t,'Synthetic reply preserves the imported source.');t.dispatchEvent(new Event('input',{bubbles:true}));return true})()`)
  await capture(main,'reply-preview')
  const mainFonts=await evaluate(`({text:getComputedStyle(document.querySelector('.msg')).fontFamily,composer:getComputedStyle(document.querySelector('.cc-composer textarea')).fontFamily})`)
  const mainStyleChain=await evaluate(styleProbe)
  const before=new Set(BrowserWindow.getAllWindows().map(w=>w.id))
  assert.equal(await evaluate(`(()=>{const b=document.querySelector('.desk-body button[aria-label="Open in new window"]');if(!b)return false;window.__replyComposer=document.querySelector('.cc-composer textarea');b.click();return true})()`),true)
  const child=BrowserWindow.getAllWindows().find(w=>!before.has(w.id));assert.ok(child)
  assert.equal(await waitFor(`window.__replyComposer.ownerDocument!==document`),true)
  assert.equal(await child.webContents.executeJavaScript(`document.querySelector('.cc-composer textarea').value`),'Synthetic reply preserves the imported source.')
  assert.equal(await child.webContents.executeJavaScript(`document.querySelector('.reply-preview blockquote').textContent`),source.text)
  const childFonts=await child.webContents.executeJavaScript(`({text:getComputedStyle(document.querySelector('.msg')).fontFamily,composer:getComputedStyle(document.querySelector('.cc-composer textarea')).fontFamily})`)
  const beforeCapture=await child.webContents.executeJavaScript(styleProbe)
  await capture(child,'reply-popout')
  const boundedPaint=async(code)=>Promise.race([child.webContents.executeJavaScript(code),new Promise(resolve=>setTimeout(()=>resolve('INERT: no completion within 1500ms'),1500))])
  const fontReady=await boundedPaint(`document.fonts.ready.then(()=>true)`)
  const frameReady=await boundedPaint(`new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve(true))))`)
  const visibility={visible:child.isVisible(),minimized:child.isMinimized(),document:await child.webContents.executeJavaScript('document.visibilityState'),fontReady,frameReady}
  await new Promise(r=>setTimeout(r,500))
  const settledBeforeCapture=await child.webContents.executeJavaScript(styleProbe)
  await capture(child,'reply-popout-settled')
  const afterCapture=await child.webContents.executeJavaScript(styleProbe)
  fs.writeFileSync(path.join(root,'reply-popout-styles.json'),JSON.stringify({main:mainFonts,child:childFonts,mainStyleChain,beforeCapture,settledBeforeCapture,afterCapture,visibility},null,2))
  child.close();assert.equal(await waitFor(`window.__replyComposer.ownerDocument===document`),true)
  assert.equal(await evaluate(`(()=>{const b=document.querySelector('.cc-composer .cc-send');if(!b||b.disabled)return false;b.click();return true})()`),true)
  let pending
  for(let i=0;i<40;i++){
    pending=await evaluate(`fetch('/api/orgs/import-demo/nodes/active/chat').then(r=>r.json()).then(c=>(c.pending_mail||[]).find(m=>m.body==='Synthetic reply preserves the imported source.'))`)
    if(pending)break
    await new Promise(r=>setTimeout(r,150))
  }
  const pendingHasReply=Boolean(pending.reply_to)
  const inbox=await evaluate(`fetch('/api/orgs/import-demo/nodes/active/inbox').then(r=>r.json())`)
  const persisted=[...inbox.pending,...inbox.delivered].find(m=>m.body==='Synthetic reply preserves the imported source.')
  assert.equal(persisted.reply_to.source_event_ref.eventId,source.id)
  assert.equal(persisted.reply_to.quoted_context,source.text)
  await capture(main,'reply-sent')
  assert.equal(await evaluate(`(()=>{const b=document.querySelector('button[aria-label="settings for active"]');if(!b)return false;b.click();return true})()`),true)
  assert.equal(await waitFor(`[...document.querySelectorAll('button')].some(b=>b.textContent==='Remove retained reply quotes')`),true)
  await evaluate(`[...document.querySelectorAll('button')].find(b=>b.textContent==='Remove retained reply quotes').click();true`)
  assert.equal(await waitFor(`document.querySelector('.confirm-box')`),true)
  await capture(main,'reply-removal-confirmation')
  await evaluate(`[...document.querySelectorAll('.confirm-box button')].find(b=>b.textContent==='cancel').click();true`)
  const afterCancel=await evaluate(`fetch('/api/orgs/import-demo/nodes/active/chat').then(r=>r.json())`)
  assert.ok(afterCancel.messages.some(m=>m.event_id===source.id),'Cancel preserves source snapshot')
  await evaluate(`[...document.querySelectorAll('button')].find(b=>b.textContent==='Remove retained reply quotes').click();true`)
  assert.equal(await waitFor(`document.querySelector('.confirm-box button.solid')`),true)
  await evaluate(`document.querySelector('.confirm-box button.solid').click();true`)
  assert.equal(await waitFor(`document.body.innerText.includes('retained reply quote') && !document.querySelector('.confirm-box')`),true)
  await new Promise(r=>setTimeout(r,500))
  const refused=await evaluate(`fetch('/api/orgs/import-demo/nodes/active/message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:'This invalid old reference must not be sent.',reply_to:{source_event_ref:{org:'import-demo',agent:'active',generation:0,eventId:${JSON.stringify(source.id)}},quoted_context:${JSON.stringify(source.text)}}})}).then(r=>r.status)`)
  assert.equal(refused,422)
  fs.writeFileSync(path.join(root,'reply-ui-result.json'),JSON.stringify({sourceId:source.id,exactQuote:source.text,contextMenu:true,nativePopoutSameComposer:true,realSend:true,canonicalPersistedReply:true,cancelPreserved:true,confirmedClearOldRefRefused:true,providerTurn:false,pendingProjectionPreservesReply:pendingHasReply,mainFonts,childFonts}))
  assert.equal(pendingHasReply,true,'Pending chat projection must preserve canonical reply context')
  assert.deepEqual(childFonts,mainFonts,'Native desk text/composer fonts must match main')
}
