//! Check an implementation against the Python-generated parity vectors.
//!
//! The functions under test are passed in as an [`Implementation`], so the
//! negative controls can swap one real decision for a known-faulty one and
//! show that the unchanged vectors detect it.

use crate::credential::{self, CredentialClaim, CredentialError, LegacyVerify};
use crate::credits::{self, AmountError, Credits, LegacyGrant, PyFloat2};
use crate::identity::{self, Actor, IdentityError};
use crate::json::{self, python_ascii_string, JsonError, Limits, Number, Object, Profile, Value};
use crate::presence::{self, GenerationError, Presence};
use crate::PyOutcome;

pub const SCHEMA: &str = "orgtree.backend-codec-vectors/v1";

/// The committed vectors, generated by `oracle/generate_vectors.py`.
pub const COMMITTED: &str = include_str!("../vectors/backend-codec-vectors.json");

/// The decisions a vector run exercises.
#[derive(Clone, Copy)]
pub struct Implementation {
    pub py_round2: fn(f64) -> Result<PyFloat2, AmountError>,
    pub py_float_repr: fn(PyFloat2) -> String,
    pub py_seat_for: fn(f64) -> PyOutcome<PyFloat2>,
    pub parse_exact: fn(&Number) -> Result<Credits, AmountError>,
    pub legacy_hire_grant: fn(&Value) -> PyOutcome<LegacyGrant>,
    pub json_parse: fn(&str, Profile, Limits) -> Result<Value, JsonError>,
    pub presence_kind: fn(&Object, &str) -> &'static str,
    pub node_generation: fn(&Object) -> Result<Option<u64>, GenerationError>,
    pub legacy_api_generation: fn(&Object) -> PyOutcome<i64>,
    pub py_slugify: fn(&str) -> Result<String, IdentityError>,
    pub py_work_slugify: fn(Option<&str>) -> String,
    pub lower_table: &'static [(char, &'static str)],
    pub retired_shape: fn(&str) -> bool,
    pub actor_parse: fn(&str) -> Result<Actor, IdentityError>,
    pub new_work_name: fn(Option<&str>, &[u8; 16]) -> Result<String, orgtree_work_name_codec::NameError>,
    pub encode_payload: fn(&str, &str, i64) -> Result<String, CredentialError>,
    pub decode_payload_legacy: fn(&str) -> LegacyVerify,
    pub decode_payload_canonical: fn(&str) -> Result<CredentialClaim, CredentialError>,
}

fn presence_kind(o: &Object, k: &str) -> &'static str {
    o.get(k).kind()
}

impl Implementation {
    pub const REFERENCE: Implementation = Implementation {
        py_round2: credits::py_round2,
        py_float_repr: credits::py_float_repr,
        py_seat_for: credits::py_seat_for,
        parse_exact: credits::parse_exact,
        legacy_hire_grant: credits::legacy_hire_grant,
        json_parse: json::parse,
        presence_kind,
        node_generation: presence::node_generation,
        legacy_api_generation: presence::legacy_api_generation,
        py_slugify: identity::py_slugify,
        py_work_slugify: identity::py_work_slugify,
        lower_table: identity::PYTHON_LOWER_TO_ASCII,
        retired_shape: identity::py_is_retired_work_id_shape,
        actor_parse: Actor::parse,
        new_work_name: identity::new_work_name,
        encode_payload: credential::encode_payload,
        decode_payload_legacy: credential::decode_payload_legacy,
        decode_payload_canonical: credential::decode_payload_canonical,
    };
}

/// Result of one run: how many rows were checked per section, and every
/// mismatch with its section and row index.
#[derive(Debug, Default)]
pub struct Report {
    pub checked: Vec<(String, usize)>,
    pub failures: Vec<String>,
}

impl Report {
    pub fn total(&self) -> usize {
        self.checked.iter().map(|(_, n)| n).sum()
    }

    pub fn failed_sections(&self) -> Vec<&str> {
        let mut s: Vec<&str> = self.failures.iter().map(|f| f.split(['[', ':']).next().unwrap_or("")).collect();
        s.dedup();
        s
    }
}

// ---- small accessors over the vector document ---------------------------

fn obj(v: &Value) -> &Object {
    match v {
        Value::Object(o) => o,
        _ => panic!("vector row is not an object"),
    }
}

fn field<'a>(o: &'a Object, k: &str) -> Option<&'a Value> {
    match o.get(k) {
        Presence::Present(v) => Some(v),
        _ => None,
    }
}

fn is_null(o: &Object, k: &str) -> bool {
    o.get(k).is_null()
}

fn text<'a>(o: &'a Object, k: &str) -> Option<&'a str> {
    match field(o, k) {
        Some(Value::String(s)) => Some(s),
        _ => None,
    }
}

fn int(o: &Object, k: &str) -> Option<i64> {
    match field(o, k) {
        Some(Value::Number(n)) => n.to_i64(),
        _ => None,
    }
}

fn boolean(o: &Object, k: &str) -> Option<bool> {
    match field(o, k) {
        Some(Value::Bool(b)) => Some(*b),
        _ => None,
    }
}

fn rows<'a>(doc: &'a Object, k: &str) -> &'a [Value] {
    match field(doc, k) {
        Some(Value::Array(a)) => a,
        _ => panic!("vectors missing section {k}"),
    }
}

fn f64_bits(o: &Object) -> f64 {
    let h = text(o, "bits").expect("bits");
    f64::from_bits(u64::from_str_radix(h, 16).expect("hex bits"))
}

fn hex16(s: &str) -> [u8; 16] {
    let mut out = [0u8; 16];
    for (i, b) in out.iter_mut().enumerate() {
        *b = u8::from_str_radix(&s[2 * i..2 * i + 2], 16).expect("hex uuid");
    }
    out
}

/// The same rendering as the oracle's `render`, as compact ASCII JSON.
pub fn render(v: &Value) -> String {
    match v {
        Value::Null => "[\"null\"]".to_owned(),
        Value::Bool(b) => format!("[\"bool\",{b}]"),
        Value::Number(n) if n.is_integer_lexeme() => {
            let s = n.lexeme();
            let s = if s.trim_start_matches('-').bytes().all(|b| b == b'0') { "0" } else { s };
            format!("[\"int\",\"{s}\"]")
        }
        Value::Number(n) => format!("[\"float\",\"{:016x}\"]", n.to_f64().to_bits()),
        Value::String(s) => format!("[\"str\",{}]", python_ascii_string(s)),
        Value::Array(a) => format!("[\"list\",[{}]]", a.iter().map(render).collect::<Vec<_>>().join(",")),
        Value::Object(o) => format!(
            "[\"dict\",[{}]]",
            o.members().iter().map(|(k, v)| format!("[{},{}]", python_ascii_string(k), render(v))).collect::<Vec<_>>().join(",")
        ),
    }
}

fn outcome_name<T>(o: &PyOutcome<T>) -> String {
    match o {
        PyOutcome::Value(_) => "value".to_owned(),
        PyOutcome::Raises(e) => e.as_str().to_owned(),
        PyOutcome::OutsideParityDomain(r) => format!("outside_parity({r})"),
    }
}

/// Run every section. Panics only on a malformed vector document.
pub fn run(doc_text: &str, imp: &Implementation) -> Report {
    let doc = json::parse(doc_text, Profile::Strict, Limits { max_bytes: 64 << 20, max_depth: 64 })
        .expect("vectors are strict JSON");
    let doc = obj(&doc);
    assert_eq!(text(doc, "schema"), Some(SCHEMA), "vector schema");
    let mut r = Report::default();
    let mut section = |name: &str, n: usize, fails: Vec<String>| {
        r.checked.push((name.to_owned(), n));
        r.failures.extend(fails.into_iter().map(|f| {
            let f = format!("{name}{f}");
            if f.chars().count() > 300 { format!("{}…", f.chars().take(300).collect::<String>()) } else { f }
        }));
    };

    // py_round2 ------------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "py_round2");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let want = obj(field(o, "rust").expect("rust"));
        let got = (imp.py_round2)(f64_bits(o));
        match (text(want, "error"), got) {
            (Some(e), Err(g)) if g.as_str() == e => {}
            (None, Ok(g)) => {
                let h = int(want, "hundredths").expect("hundredths");
                let nz = boolean(want, "negative_zero").expect("negative_zero");
                let repr = (imp.py_float_repr)(g);
                if g.hundredths != h || g.negative_zero != nz || Some(repr.as_str()) != text(o, "python_repr") {
                    f.push(format!("[{i}]: got {g:?} repr {repr}, want {h} nz={nz} repr {:?}", text(o, "python_repr")));
                }
            }
            (w, g) => f.push(format!("[{i}]: got {g:?}, want error {w:?}")),
        }
    }
    section("py_round2", rs.len(), f);

    // seat_for ---------------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "seat_for");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let got = (imp.py_seat_for)(f64_bits(o));
        let ok = match (text(o, "python_raises"), field(o, "rust").map(obj), &got) {
            (Some(e), _, PyOutcome::Raises(g)) => g.as_str() == e,
            (None, Some(w), PyOutcome::Value(v)) if int(w, "hundredths").is_some() => {
                Some(v.hundredths) == int(w, "hundredths")
                    && Some((imp.py_float_repr)(*v).as_str()) == text(o, "python_repr")
            }
            (None, Some(w), PyOutcome::OutsideParityDomain(_)) => boolean(w, "outside_parity") == Some(true),
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}]: got {}", outcome_name(&got)));
        }
    }
    section("seat_for", rs.len(), f);

    // parse_exact ------------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "parse_exact");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let lx = text(o, "lexeme").expect("lexeme");
        let n = match (imp.json_parse)(lx, Profile::Strict, Limits::TEST) {
            Ok(Value::Number(n)) => n,
            other => {
                f.push(format!("[{i}]: lexeme did not parse as a number: {other:?}"));
                continue;
            }
        };
        let want = obj(field(o, "rust").expect("rust"));
        match ((imp.parse_exact)(&n), text(want, "error")) {
            (Err(g), Some(e)) if g.as_str() == e => {}
            (Ok(c), None) if Some(c.hundredths()) == int(want, "hundredths") => {}
            (g, e) => f.push(format!("[{i}] {lx}: got {g:?}, want {e:?}/{:?}", int(want, "hundredths"))),
        }
        // Differential: for float lexemes, Python `_q(json.loads(lexeme))`
        // must equal the rounding reproduction.
        if !n.is_integer_lexeme() {
            if let Some(py) = text(o, "python_q_json") {
                let got = (imp.py_round2)(n.to_f64()).map(imp.py_float_repr);
                // Python's answer is outside the parity domain when it is not
                // finite or its magnitude exceeds PARITY_MAX_HUNDREDTHS.
                let expect_err = match py.parse::<f64>() {
                    Ok(x) => !x.is_finite() || (x.abs() * 100.0).round() > credits::PARITY_MAX_HUNDREDTHS as f64,
                    Err(_) => true,
                };
                match got {
                    Ok(s) if s == py => {}
                    Err(_) if expect_err => {}
                    g => f.push(format!("[{i}] {lx}: _q differential got {g:?}, python {py}")),
                }
            }
        }
    }
    section("parse_exact", rs.len(), f);

    // hire_grant -------------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "hire_grant");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let t = text(o, "json").expect("json");
        let v = (imp.json_parse)(t, Profile::PythonLegacy, Limits::TEST).expect("legacy grant json");
        let got = (imp.legacy_hire_grant)(&v);
        let ok = match (&got, text(o, "python_stored_json"), text(o, "python_raises")) {
            (PyOutcome::OutsideParityDomain(_), _, _) => boolean(o, "rust_outside_parity") == Some(true),
            (PyOutcome::Value(g), Some(s), None) => g.python_json() == s && boolean(o, "rust_outside_parity") != Some(true),
            (PyOutcome::Raises(e), None, Some(w)) => e.as_str() == w,
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}] {t}: got {got:?}"));
        }
    }
    section("hire_grant", rs.len(), f);

    // json -------------------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "json");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let t = text(o, "text").expect("text");
        let legacy = (imp.json_parse)(t, Profile::PythonLegacy, Limits::TEST);
        match (text(o, "python").expect("python"), &legacy) {
            ("ok", Ok(v)) => {
                let want = render_expected(field(o, "python_value").expect("python_value"));
                if render(v) != want {
                    f.push(format!("[{i}] {t:?}: legacy render {} != {want}", render(v)));
                }
            }
            ("error", Err(_)) => {}
            ("outside_parity", Err(e)) if e.kind == json::JsonErrorKind::LoneSurrogate => {}
            (p, g) => f.push(format!("[{i}] {t:?}: legacy got {g:?}, python {p}")),
        }
        let strict = (imp.json_parse)(t, Profile::Strict, Limits::TEST);
        let want = text(o, "strict").expect("strict");
        let ok = match (&strict, want) {
            (Ok(_), "ok") => true,
            (Err(e), "error") => !matches!(
                e.kind,
                json::JsonErrorKind::DuplicateKey | json::JsonErrorKind::NonFiniteConstant | json::JsonErrorKind::LoneSurrogate
            ),
            (Err(e), w) => e.kind.as_str() == w,
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}] {t:?}: strict got {strict:?}, want {want}"));
        }
    }
    section("json", rs.len(), f);

    // presence ---------------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "presence");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let v = (imp.json_parse)(text(o, "json").expect("json"), Profile::Strict, Limits::TEST).expect("presence json");
        let got = (imp.presence_kind)(obj(&v), text(o, "key").expect("key"));
        if Some(got) != text(o, "python") {
            f.push(format!("[{i}]: got {got}, python {:?}", text(o, "python")));
        }
    }
    section("presence", rs.len(), f);

    // generation -------------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "generation");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let t = text(o, "json").expect("json");
        let v = (imp.json_parse)(t, Profile::PythonLegacy, Limits::TEST).expect("generation json");
        let node = obj(&v);
        let api = (imp.legacy_api_generation)(node);
        let ok = match (&api, int(o, "api_value"), text(o, "api_raises")) {
            (PyOutcome::OutsideParityDomain(_), _, _) => boolean(o, "api_rust_outside_parity") == Some(true),
            (PyOutcome::Value(g), Some(w), None) => *g == w && boolean(o, "api_rust_outside_parity") != Some(true),
            (PyOutcome::Raises(e), None, Some(w)) => e.as_str() == w,
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}] {t}: api got {api:?}"));
        }
        let want = obj(field(o, "strict").expect("strict"));
        let got = (imp.node_generation)(node);
        let ok = match (&got, text(want, "error")) {
            (Ok(None), None) => boolean(want, "absent") == Some(true),
            (Ok(Some(g)), None) => int(want, "value") == Some(*g as i64),
            (Err(e), Some(w)) => e.as_str() == w,
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}] {t}: strict got {got:?}"));
        }
    }
    section("generation", rs.len(), f);

    // slugify / work_slugify -------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "slugify");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let s = text(o, "input").expect("input");
        let got = (imp.py_slugify)(s);
        let ok = match (&got, text(o, "python"), text(o, "python_raises")) {
            (Ok(g), Some(w), None) => g == w,
            (Err(IdentityError::EmptySlug), None, Some("LedgerError")) => true,
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}] {s:?}: got {got:?}, python {:?}", text(o, "python")));
        }
    }
    section("slugify", rs.len(), f);

    let mut f = Vec::new();
    let rs = rows(doc, "work_slugify");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let input = if is_null(o, "input") { None } else { Some(text(o, "input").expect("input")) };
        let got = (imp.py_work_slugify)(input);
        if Some(got.as_str()) != text(o, "python") {
            f.push(format!("[{i}] {input:?}: got {got:?}, python {:?}", text(o, "python")));
        }
    }
    section("work_slugify", rs.len(), f);

    // lower_table ------------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "lower_table");
    let mut want: Vec<(u32, String)> = Vec::new();
    for row in rs {
        match row {
            Value::Array(pair) => match pair.as_slice() {
                [Value::Number(c), Value::String(l)] => want.push((c.to_i64().expect("cp") as u32, l.clone())),
                _ => panic!("lower_table row"),
            },
            _ => panic!("lower_table row"),
        }
    }
    let have: Vec<(u32, String)> = imp.lower_table.iter().map(|(c, l)| (*c as u32, (*l).to_owned())).collect();
    if have != want {
        f.push(format!(": table {have:?} != python {want:?}"));
    }
    if text(obj(field(doc, "oracle").expect("oracle")), "unicode") != Some(identity::PYTHON_UNICODE_VERSION) {
        f.push(": oracle Unicode version differs from PYTHON_UNICODE_VERSION".to_owned());
    }
    section("lower_table", rs.len(), f);

    // retired_shape ----------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "retired_shape");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let s = text(o, "input").expect("input");
        if Some((imp.retired_shape)(s)) != boolean(o, "python") {
            f.push(format!("[{i}] {s:?}"));
        }
    }
    section("retired_shape", rs.len(), f);

    // actor ------------------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "actor");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let s = text(o, "input").expect("input");
        let want = obj(field(o, "expected").expect("expected"));
        let got = (imp.actor_parse)(s);
        let ok = match (&got, text(want, "kind"), text(want, "error")) {
            (Ok(a), Some(k), None) => {
                a.kind() == k && (k != "agent" || matches!(a, Actor::Agent(key) if key.as_str() == s))
            }
            (Err(e), None, Some(w)) => e.as_str() == w,
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}] {s:?}: got {got:?}"));
        }
    }
    section("actor", rs.len(), f);

    // new_work_name ----------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "new_work_name");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let title = if is_null(o, "title") { None } else { text(o, "title") };
        let got = (imp.new_work_name)(title, &hex16(text(o, "uuid").expect("uuid")));
        if got.as_deref().ok() != text(o, "expected") {
            f.push(format!("[{i}] {title:?}: got {got:?}"));
        }
    }
    section("new_work_name", rs.len(), f);

    // credential_encode ------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "credential_encode");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let got = (imp.encode_payload)(
            text(o, "org").expect("org"),
            text(o, "node").expect("node"),
            int(o, "generation").expect("generation"),
        );
        let ok = match (&got, text(o, "python_payload"), text(o, "python_raises")) {
            (Ok(p), Some(w), None) => p == w,
            (Err(CredentialError::NegativeGeneration), None, Some("ValueError")) => true,
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}]: got {got:?}"));
        }
    }
    section("credential_encode", rs.len(), f);

    // credential_decode ------------------------------------------------------
    let mut f = Vec::new();
    let rs = rows(doc, "credential_decode");
    for (i, row) in rs.iter().enumerate() {
        let o = obj(row);
        let p = text(o, "payload").expect("payload");
        let python_claim = match field(o, "python") {
            Some(Value::Object(c)) => match field(c, "claim") {
                Some(Value::Array(a)) => match a.as_slice() {
                    [Value::String(org), Value::String(node), Value::Number(g)] => {
                        g.to_i64().map(|g| CredentialClaim { org: org.clone(), node: node.clone(), generation: g })
                    }
                    _ => panic!("claim shape"),
                },
                _ => panic!("claim"),
            },
            _ => None,
        };
        let legacy = (imp.decode_payload_legacy)(p);
        let ok = match (&legacy, &python_claim) {
            (LegacyVerify::OutsideParityDomain(_), _) => boolean(o, "legacy_outside_parity") == Some(true),
            (LegacyVerify::Accepted(c), Some(w)) => c == w,
            (LegacyVerify::Rejected, None) => true,
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}] {p:?}: legacy got {legacy:?}, python {python_claim:?}"));
        }
        let canonical = (imp.decode_payload_canonical)(p);
        let want_ok = boolean(o, "canonical_ok").expect("canonical_ok");
        let ok = match (&canonical, want_ok) {
            (Ok(c), true) => Some(c) == python_claim.as_ref(),
            (Err(_), false) => true,
            _ => false,
        };
        if !ok {
            f.push(format!("[{i}] {p:?}: canonical got {canonical:?}, want ok={want_ok}"));
        }
    }
    section("credential_decode", rs.len(), f);

    r
}

/// Re-render the oracle's `python_value` (already in rendered form) with the
/// same compact formatting `render` uses.
fn render_expected(v: &Value) -> String {
    match v {
        Value::Array(a) => format!("[{}]", a.iter().map(render_expected).collect::<Vec<_>>().join(",")),
        Value::String(s) => python_ascii_string(s),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => n.lexeme().to_owned(),
        Value::Null => "null".to_owned(),
        Value::Object(_) => panic!("rendered values contain no objects"),
    }
}
