"""Additive panel migrations; the shipped record-core generator stays frozen.

An extension contributes transition-only dependencies, declared windows and
read-only scope resolution. Each migration composes ALL extensions installed
at its tip, so adding a panel cannot erase an earlier panel's resolver cases.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Mapping

from . import record_derivations as D, record_sql as S


@dataclass(frozen=True)
class Extension:
    name: str
    sources: Callable[[Mapping[str, D.Source]], dict[str, D.Source]]
    windows: tuple[D.Window, ...] = ()
    before: str = ''
    after: str = ''


def sources(extensions: tuple[Extension, ...]) -> dict[str, D.Source]:
    result = dict(D.SOURCES)
    if len({extension.name for extension in extensions}) != len(extensions):
        raise ValueError('duplicate panel extension')
    for extension in extensions:
        result = extension.sources(result)
    return D.with_windows(result, tuple(window for extension in extensions for window in extension.windows))


def resolver(extensions: tuple[Extension, ...]) -> str:
    # Reuse the original generator for the declared window cases. Do not edit
    # 0018 or change its default output when a later extension is installed.
    windows = tuple(window for extension in extensions for window in extension.windows)
    complete = S.migration_sql(windows=windows)
    start = complete.index('CREATE FUNCTION orgtree.resolve_scopes')
    end = complete.index('$fn$;', start) + len('$fn$;')
    sql = complete[start:end]
    before = '\n'.join(extension.before for extension in extensions if extension.before)
    after = '\n'.join(extension.after for extension in extensions if extension.after)
    sql = sql.replace('  FOR scope_row IN SELECT entity_id', before+'\n  FOR scope_row IN SELECT entity_id', 1)
    sql = sql.replace('  -- Name scopes can add a lineage scope', after+'\n  -- Name scopes can add a lineage scope', 1)
    return sql.replace('CREATE FUNCTION', 'CREATE OR REPLACE FUNCTION', 1)


def migration_sql(previous: tuple[Extension, ...], current: tuple[Extension, ...]) -> str:
    if tuple(extension.name for extension in current[:len(previous)]) != tuple(extension.name for extension in previous):
        raise ValueError('panel migrations append extensions; they cannot drop prior ones')
    old, new = sources(previous), sources(current)
    parts = ['-- GENERATED by orgdb.record_panel_sql.migration_sql.\n', resolver(current)]
    for table, source in sorted(new.items()):
        if source == old.get(table):
            continue
        if source.excluded:
            raise ValueError('a panel migration cannot silently remove capture: '+table)
        for operation in ('insert', 'update', 'delete'):
            parts.append(f'DROP TRIGGER IF EXISTS record_capture_{operation} ON orgtree.{table};\n')
        parts.append(D.capture_sql({table:source}).replace('CREATE FUNCTION', 'CREATE OR REPLACE FUNCTION'))
    return '\n'.join(parts)
