-- The legacy org document as tables (design §3, Appendix A; landing step 1).
--
-- GENERATED from engine/backend/orgtree/orgdb/mappers (the codec specs of every section) by
-- mappers.ddl(); tests/test_orgdb_mappers.py fails while the two differ. Once a release has
-- shipped this file it never changes again: later schema changes are new migration files.
--
-- Every record table has a surrogate id; child tables are keyed by their parent's id and a
-- position. Column names are quoted because legacy keys include reserved words.

CREATE TABLE orgtree.tool_lists (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sha256 text NOT NULL UNIQUE
);

CREATE TABLE orgtree.tool_list_items (
  list_id bigint NOT NULL REFERENCES orgtree.tool_lists (id) ON DELETE CASCADE,
  pos integer NOT NULL,
  tool text NOT NULL,
  PRIMARY KEY (list_id, pos)
);

CREATE INDEX tool_list_items_tool ON orgtree.tool_list_items (tool);

CREATE TABLE orgtree.agents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  ord bigint,
  tombstone boolean NOT NULL DEFAULT false,
  parent_id bigint REFERENCES orgtree.agents (id),
  predecessor_id bigint REFERENCES orgtree.agents (id),
  successor_id bigint REFERENCES orgtree.agents (id),
  tool_list_id bigint REFERENCES orgtree.tool_lists (id),
  is_frozen boolean NOT NULL DEFAULT false,
  is_halted boolean NOT NULL DEFAULT false,
  is_inflight boolean NOT NULL DEFAULT false,
  is_remote_controlled boolean NOT NULL DEFAULT false,
  has_pending_switch boolean NOT NULL DEFAULT false,
  row_version bigint NOT NULL DEFAULT 0,
  "lineage_born" text,
  "generation" bigint,
  "parent" text,
  "parent_null" boolean,
  "ui_order" double precision,
  "created" timestamptz,
  "created_text" text,
  "archived_at" timestamptz,
  "archived_at_text" text,
  "archived_at_null" boolean,
  "rescinded_at" timestamptz,
  "rescinded_at_text" text,
  "rescinded_at_null" boolean,
  "state" text,
  "title" text,
  "model" text,
  "credit_grant" numeric,
  "lineage" text,
  "predecessor" text,
  "predecessor_null" boolean,
  "successor" text,
  "successor_null" boolean,
  "bearer_state" text,
  "bearer_state_null" boolean,
  "lost_reason" text,
  "session_id" text,
  "transcript_incarnation" text,
  "reply_incarnation" text,
  "pid" bigint,
  "pid_null" boolean,
  "session_began_at" timestamptz,
  "session_began_at_text" text,
  "session_unrun" boolean,
  "cheap_compacted" boolean,
  "compacted_unrun" boolean,
  "account" text,
  "account_primary" boolean,
  "codex_account" text,
  "codex_thread" text,
  "codex_native_home" text,
  "antigravity_account" text,
  "antigravity_conversation" text,
  "mailbox_id" text,
  "mail_seq" bigint,
  "scope_is" char(1),
  "scope_permission_mode" text,
  "scope_org_visibility" text,
  "scope_effort" text,
  "scope_model_version" text,
  "scope_prefer_reserve" boolean,
  "scope_account_fallback" boolean,
  "scope_tools_is" char(1),
  "scope_tools_bash" boolean,
  "scope_tools_web" boolean,
  "scope_tools_edit" boolean,
  "scope_tools_subagents" boolean,
  "scope_tools_mcp_is" char(1),
  "scope_add_dirs_is" char(1),
  "cost_usd" double precision,
  "cost_usd_unknown" boolean,
  "context_window" bigint,
  "occupancy" bigint,
  "occupancy_null" boolean,
  "occupancy_est" boolean,
  "cli_compactions" bigint,
  "cli_compactions_null" boolean,
  "cli_boundary_offset" bigint,
  "turn_seq" bigint,
  "turn_est_cost" json,
  "turn_est_toks" json,
  "last_status_is" char(1),
  "last_status_status" text,
  "last_status_summary" text,
  "last_status_at" timestamptz,
  "last_status_at_text" text,
  "prev_status_is" char(1),
  "prev_status_status" text,
  "prev_status_summary" text,
  "prev_status_at" timestamptz,
  "prev_status_at_text" text,
  "limit_locked" boolean,
  "config_seq" bigint,
  "hard_fail_run" bigint,
  "limit_run" bigint,
  "net_fail_run" bigint,
  "net_fail_since" timestamptz,
  "net_fail_since_text" text,
  "untrusted_limit_run" bigint,
  "docket_reminder_at" timestamptz,
  "docket_reminder_at_text" text,
  "working_activity_at" timestamptz,
  "working_activity_at_text" text,
  "cache_keepalive_at" timestamptz,
  "cache_keepalive_at_text" text,
  "last_turn_mcp_tool_count" bigint,
  "last_turn_mcp_fingerprint" text,
  "last_denials_is" char(1),
  "last_approvals_is" char(1),
  "turns_is" char(1),
  "halt_queue_is" char(1),
  "extra" json
);

CREATE TABLE orgtree.agent_mcp_servers (
  "agent_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("agent_id", "pos"),
  FOREIGN KEY ("agent_id") REFERENCES orgtree.agents ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.agent_dir_grants (
  "agent_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "path" text,
  "mode" text,
  "extra" json,
  PRIMARY KEY ("agent_id", "pos"),
  FOREIGN KEY ("agent_id") REFERENCES orgtree.agents ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.agent_tool_denials (
  "agent_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "tool" text,
  "arg" text,
  "cwd" text,
  "extra" json,
  PRIMARY KEY ("agent_id", "pos"),
  FOREIGN KEY ("agent_id") REFERENCES orgtree.agents ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.agent_tool_approvals (
  "agent_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "tool" text,
  "arg" text,
  "cwd" text,
  "extra" json,
  PRIMARY KEY ("agent_id", "pos"),
  FOREIGN KEY ("agent_id") REFERENCES orgtree.agents ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.agent_recent_turns (
  "agent_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "n" bigint,
  "at" timestamptz,
  "at_text" text,
  "cost" double precision,
  "ms" bigint,
  "ms_null" boolean,
  "toks" bigint,
  "denials" bigint,
  "approvals" bigint,
  "ran_as" text,
  "killed" boolean,
  "estimated" boolean,
  "cost_complete" boolean,
  "cost_source" text,
  "cost_unknown_fields" json,
  "route" json,
  "reported" json,
  "model_usage_key" json,
  "extra" json,
  PRIMARY KEY ("agent_id", "pos"),
  FOREIGN KEY ("agent_id") REFERENCES orgtree.agents ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.agent_carriers (
  "agent_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "halt_id" text,
  "text" text,
  "view" text,
  "ping" boolean,
  "ping_reason" text,
  "ping_reason_null" boolean,
  "from_node" text,
  "at" double precision,
  "delivery_id" text,
  "toks_is" char(1),
  "mail_ids_is" char(1),
  "claim" json,
  "extra" json,
  PRIMARY KEY ("agent_id", "pos"),
  FOREIGN KEY ("agent_id") REFERENCES orgtree.agents ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.agent_carrier_tokens (
  "agent_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "pos_2" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("agent_id", "pos", "pos_2"),
  FOREIGN KEY ("agent_id", "pos") REFERENCES orgtree.agent_carriers ("agent_id", "pos") ON DELETE CASCADE
);

CREATE TABLE orgtree.agent_carrier_mail (
  "agent_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "pos_2" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("agent_id", "pos", "pos_2"),
  FOREIGN KEY ("agent_id", "pos") REFERENCES orgtree.agent_carriers ("agent_id", "pos") ON DELETE CASCADE
);

CREATE UNIQUE INDEX agents_name ON orgtree.agents ("name") WHERE NOT tombstone;

CREATE UNIQUE INDEX agents_ord ON orgtree.agents (ord) WHERE NOT tombstone;

CREATE INDEX agents_children ON orgtree.agents (parent_id, ui_order, created, ord);

CREATE INDEX agents_live ON orgtree.agents (ord) WHERE state = 'live' AND NOT tombstone;

CREATE INDEX agents_retired ON orgtree.agents (parent_id, ui_order, created, ord) WHERE state = 'archived' AND successor_id IS NULL AND NOT tombstone;

CREATE INDEX agents_predecessor ON orgtree.agents (predecessor_id);

CREATE INDEX agents_successor ON orgtree.agents (successor_id);

CREATE INDEX agents_lineage ON orgtree.agents (lineage_born);

CREATE INDEX agents_session ON orgtree.agents (session_id);

CREATE UNIQUE INDEX agents_mailbox ON orgtree.agents (mailbox_id) WHERE mailbox_id IS NOT NULL;

CREATE INDEX agents_account ON orgtree.agents (account) WHERE state = 'live' AND account IS NOT NULL;

CREATE INDEX agents_frozen ON orgtree.agents (id) WHERE is_frozen;

CREATE INDEX agents_halted ON orgtree.agents (id) WHERE is_halted;

CREATE INDEX agents_inflight ON orgtree.agents (id) WHERE is_inflight;

CREATE INDEX agents_remote ON orgtree.agents (id) WHERE is_remote_controlled;

CREATE INDEX agents_switching ON orgtree.agents (id) WHERE has_pending_switch;

CREATE TABLE orgtree.agent_texts (
  agent_id bigint PRIMARY KEY REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  "charter" text,
  "charter_null" boolean,
  "team_charter" text,
  "team_charter_null" boolean,
  "extra" json
);

CREATE TABLE orgtree.agent_runtime (
  agent_id bigint PRIMARY KEY REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  "frozen" json,
  "frozen_null" boolean,
  "halt" json,
  "halt_null" boolean,
  "inflight" json,
  "inflight_null" boolean,
  "turn_ended" json,
  "turn_ended_null" boolean,
  "pending_switch" json,
  "pending_switch_null" boolean,
  "remote_controlled" json,
  "remote_controlled_null" boolean,
  "admit_once" json,
  "admit_once_null" boolean,
  "unstuck" json,
  "unstuck_null" boolean,
  "last_wall" json,
  "last_wall_null" boolean,
  "cache_continuity" json,
  "cache_continuity_null" boolean,
  "envelope" json,
  "envelope_null" boolean,
  "codex_route_last" json,
  "codex_route_last_null" boolean,
  "codex_usage_total" json,
  "codex_usage_total_null" boolean,
  "codex_usage_reset" json,
  "codex_usage_reset_null" boolean,
  "desktop_import" json,
  "desktop_import_null" boolean,
  "mail_drain_is" char(1),
  "mail_drain_ids_is" char(1),
  "mail_drain_retry_at" bigint,
  "mail_drain_failures" bigint,
  "mail_drain_suspended" boolean,
  "extra" json
);

CREATE TABLE orgtree.agent_mail_drain (
  "agent_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("agent_id", "pos"),
  FOREIGN KEY ("agent_id") REFERENCES orgtree.agent_runtime ("agent_id") ON DELETE CASCADE
);

CREATE TABLE orgtree.org_sections (
  "key" text PRIMARY KEY,
  ord integer NOT NULL UNIQUE,
  state char(1) NOT NULL CHECK (state IN ('v', 'n'))
);

CREATE TABLE orgtree.org_section_owners (
  section text NOT NULL,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  ord integer NOT NULL,
  state char(1) NOT NULL CHECK (state IN ('l', 'o', 'n')),
  PRIMARY KEY (section, agent_id),
  UNIQUE (section, ord)
);

CREATE TABLE orgtree.org_settings (
  singleton boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  "version" bigint,
  "slug" text,
  "name" text,
  "created" timestamptz,
  "created_text" text,
  "workspace" text,
  "permission_mode" text,
  "default_visibility" text,
  "default_effort" text,
  "max_top_grant" numeric,
  "default_top_grant" numeric,
  "compact_at" numeric,
  "max_children" bigint,
  "max_depth" bigint,
  "fable_limit_policy" text,
  "fable_filter_policy" text,
  "fable_filter_model" text,
  "fable_api_fallback" json,
  "fable_lock" json,
  "fable_lock_null" boolean,
  "cascade_hire" boolean,
  "cascade_alloc" boolean,
  "auto_resume" boolean,
  "auto_resume_compact" boolean,
  "auto_resume_last" numeric,
  "auto_cheap_compact" json,
  "auto_cheap_compact_null" boolean,
  "default_tools" json,
  "default_tools_null" boolean,
  "default_dirs" json,
  "default_dirs_null" boolean,
  "default_account" text,
  "default_account_null" boolean,
  "account_fallback_default" json,
  "account_fallback_default_null" boolean,
  "account_token_uuid" text,
  "account_token_uuid_null" boolean,
  "killswitch" json,
  "killswitch_null" boolean,
  "net_autoconnect" boolean,
  "net_identity" json,
  "net_identity_null" boolean,
  "net_spool" json,
  "net_spool_null" boolean,
  "external_inbox_multi_holder" boolean,
  "org_inbox_multi_holder" boolean,
  "org_inbox_read" bigint,
  "mail_drain_version" bigint,
  "reply_incarnation" text,
  "work_identity" text,
  "whole_grants_v1" boolean,
  "actors_typed" boolean,
  "deleted_cost_usd" numeric,
  "deleted_cost_usd_unknown" boolean,
  "api_cost_usd" numeric,
  "api_fallback" json,
  "api_fallback_null" boolean,
  "api_fallback_since" json,
  "api_fallback_since_null" boolean,
  "api_fallback_until" json,
  "api_fallback_until_null" boolean,
  "api_key" json,
  "api_key_null" boolean,
  "cred_warned_at" json,
  "cred_warned_at_null" boolean,
  "headless" json,
  "headless_null" boolean,
  "desktop_import" json,
  "desktop_import_null" boolean,
  "op_receipts_meta" json,
  "op_receipts_meta_null" boolean,
  "tool_result_receipts" json,
  "tool_result_receipts_null" boolean,
  "sandbox" json,
  "sandbox_null" boolean,
  "chain_notices" json,
  "chain_notices_null" boolean,
  "release" json,
  "release_null" boolean,
  "extra" json
);

CREATE TABLE orgtree.work_items (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  list_key text NOT NULL CHECK (list_key IN ('active', 'archive')),
  ord bigint NOT NULL,
  anchor_name text GENERATED ALWAYS AS (coalesce(owner_node, created_by_node)) STORED,
  "slug" text,
  "rev" bigint,
  "kind" text,
  "title" text,
  "objective" text,
  "status" text,
  "blocked_reason" text,
  "blocked_reason_null" boolean,
  "waiting_reason" text,
  "waiting_reason_null" boolean,
  "dropped_reason" text,
  "dropped_reason_null" boolean,
  "owner_is" char(1),
  "owner_node" text,
  "owner_generation" bigint,
  "owner_born" text,
  "reviewer_is" char(1),
  "reviewer_node" text,
  "reviewer_generation" bigint,
  "reviewer_born" text,
  "created_by_is" char(1),
  "created_by_node" text,
  "created_by_generation" bigint,
  "last_updater_is" char(1),
  "last_updater_node" text,
  "last_updater_generation" bigint,
  "participants_is" char(1),
  "at" timestamptz,
  "at_text" text,
  "updated_at" timestamptz,
  "updated_at_text" text,
  "docket_at" timestamptz,
  "docket_at_text" text,
  "status_at" timestamptz,
  "status_at_text" text,
  "archived_at" timestamptz,
  "archived_at_text" text,
  "archived_at_null" boolean,
  "done_so_far_is" char(1),
  "working_on_next_is" char(1),
  "manual_attention" json,
  "manual_attention_null" boolean,
  "manual_attention_rev" bigint,
  "dismissals_is" char(1),
  "acceptance_is" char(1),
  "dependencies_is" char(1),
  "evidence_is" char(1),
  "delivery" json,
  "delivery_null" boolean,
  "accepted" json,
  "accepted_null" boolean,
  "candidate_verdict" json,
  "candidate_verdict_null" boolean,
  "candidate_verdicts" json,
  "review_packet" json,
  "review_packet_null" boolean,
  "review_packets" json,
  "review_seats" json,
  "review_seat_requests_is" char(1),
  "history_is" char(1),
  "superseded_by" text,
  "superseded_by_null" boolean,
  "parent" text,
  "parent_null" boolean,
  "holders_is" char(1),
  "notification_attention_epoch" bigint,
  "notification_attention_active" boolean,
  "scope_is" char(1),
  "scope_seq" bigint,
  "scope_guard" bigint,
  "scope_logged" bigint,
  "artifacts_is" char(1),
  "artifact_seq" bigint,
  "findings_is" char(1),
  "finding_seq" bigint,
  "quick_staff_receipts" json,
  "post_completion" json,
  "extra" json
);

CREATE TABLE orgtree.work_item_participants (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_done (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_next (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_dismissals (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "by" text,
  "set_rev" bigint,
  "reason" text,
  "extra" json,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_acceptance (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "text" text,
  "checked_is" char(1),
  "checked_at" timestamptz,
  "checked_at_text" text,
  "checked_by_is" char(1),
  "checked_by_node" text,
  "checked_by_generation" bigint,
  "checked_evidence_ref" text,
  "checked_note" text,
  "checked_note_null" boolean,
  "checked_classification" text,
  "checked_artifact" text,
  "checked_runner" text,
  "checked_execution" text,
  "checked_execution_means" text,
  "checked_result" text,
  "checked_classification_means" text,
  "checked_composition" text,
  "checked_gate" text,
  "checked_blocked_count" bigint,
  "check_history_is" char(1),
  "extra" json,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_acceptance_checks (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "pos_2" integer NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "by_is" char(1),
  "by_node" text,
  "by_generation" bigint,
  "evidence_ref" text,
  "note" text,
  "note_null" boolean,
  "classification" text,
  "artifact" text,
  "runner" text,
  "execution" text,
  "execution_means" text,
  "result" text,
  "classification_means" text,
  "composition" text,
  "gate" text,
  "blocked_count" bigint,
  "extra" json,
  PRIMARY KEY ("item_id", "pos", "pos_2"),
  FOREIGN KEY ("item_id", "pos") REFERENCES orgtree.work_item_acceptance ("item_id", "pos") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_dependencies (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_evidence (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "by_is" char(1),
  "by_node" text,
  "by_generation" bigint,
  "kind" text,
  "ref" text,
  "note" text,
  "execution" text,
  "execution_means" text,
  "receipt" json,
  "classification" text,
  "artifact" text,
  "runner" text,
  "result" text,
  "classification_means" text,
  "extra" json,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_review_seat_requests (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "seq" bigint,
  "reviewer" text,
  "requested_by" text,
  "owner" text,
  "to" text,
  "at" timestamptz,
  "at_text" text,
  "state" text,
  "note" text,
  "decided_by" text,
  "decided_by_null" boolean,
  "decided_at" timestamptz,
  "decided_at_text" text,
  "decided_at_null" boolean,
  "decision_note" text,
  "decision_note_null" boolean,
  "extra" json,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_history (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "by" json,
  "op" text,
  "kind" text,
  "from" json,
  "from_null" boolean,
  "to" json,
  "to_null" boolean,
  "done" json,
  "next" json,
  "changes" json,
  "now" json,
  "why" text,
  "note" text,
  "note_null" boolean,
  "reason" text,
  "status" text,
  "status_from" text,
  "status_to" text,
  "stage" text,
  "reviewer" text,
  "candidate" text,
  "decision" text,
  "disposition" text,
  "finding" text,
  "artifact" text,
  "name" text,
  "scope" text,
  "via" text,
  "evidence_gap" text,
  "answer" text,
  "scope_seq" bigint,
  "batch" bigint,
  "index" bigint,
  "set_rev" bigint,
  "supersedes" bigint,
  "count" bigint,
  "answered_request" bigint,
  "answered_request_null" boolean,
  "already_seated" boolean,
  "after_completion" boolean,
  "atomic_completion" boolean,
  "review_in_flight" boolean,
  "verified" boolean,
  "verified_null" boolean,
  "accepted_at" timestamptz,
  "accepted_at_text" text,
  "first_at" timestamptz,
  "first_at_text" text,
  "last_at" timestamptz,
  "last_at_text" text,
  "raised_at" timestamptz,
  "raised_at_text" text,
  "kinds" json,
  "indexes" json,
  "touched" json,
  "requests" json,
  "done_was" json,
  "next_was" json,
  "next_actor" json,
  "raised_by" json,
  "review_packet_was" json,
  "review_packet_was_null" boolean,
  "accepted_was" json,
  "accepted_was_null" boolean,
  "superseded_by_was" json,
  "superseded_by_was_null" boolean,
  "dropped_reason_was" json,
  "dropped_reason_was_null" boolean,
  "candidate_verdict_was" json,
  "candidate_verdict_was_null" boolean,
  "extra" json,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_holders (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "node" text,
  "generation" bigint,
  "born" text,
  "from" timestamptz,
  "from_text" text,
  "by" json,
  "derived" boolean,
  "extra" json,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_scope (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "seq" bigint,
  "at" timestamptz,
  "at_text" text,
  "by_is" char(1),
  "by_node" text,
  "by_generation" bigint,
  "kind" text,
  "before" text,
  "after" text,
  "mode" text,
  "supersedes" bigint,
  "supersedes_null" boolean,
  "superseded_by" bigint,
  "superseded_by_null" boolean,
  "text" text,
  "extra" json,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_artifacts (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "public_id" text,
  "seq" bigint,
  "at" timestamptz,
  "at_text" text,
  "by_is" char(1),
  "by_node" text,
  "by_generation" bigint,
  "name" text,
  "bytes" bigint,
  "sha256" text,
  "path" text,
  "scope" text,
  "grants" json,
  "note" text,
  "extra" json,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_findings (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "public_id" text,
  "seq" bigint,
  "at" timestamptz,
  "at_text" text,
  "by_is" char(1),
  "by_node" text,
  "by_generation" bigint,
  "title" text,
  "disposition" text,
  "decisions_is" char(1),
  "detail" text,
  "severity" text,
  "evidence_ref" text,
  "extra" json,
  PRIMARY KEY ("item_id", "pos"),
  FOREIGN KEY ("item_id") REFERENCES orgtree.work_items ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.work_item_finding_decisions (
  "item_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "pos_2" integer NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "by_is" char(1),
  "by_node" text,
  "by_generation" bigint,
  "disposition" text,
  "note" text,
  "extra" json,
  PRIMARY KEY ("item_id", "pos", "pos_2"),
  FOREIGN KEY ("item_id", "pos") REFERENCES orgtree.work_item_findings ("item_id", "pos") ON DELETE CASCADE
);

CREATE UNIQUE INDEX work_items_list_ord ON orgtree.work_items (list_key, ord);

ALTER TABLE orgtree.work_items ADD CONSTRAINT work_items_slug UNIQUE (slug) DEFERRABLE INITIALLY DEFERRED;

CREATE INDEX work_items_active_order ON orgtree.work_items (coalesce(docket_at, updated_at) DESC, slug DESC) WHERE archived_at IS NULL;

CREATE INDEX work_items_owner ON orgtree.work_items (owner_node);

CREATE INDEX work_items_creator ON orgtree.work_items (created_by_node);

CREATE INDEX work_items_reviewer ON orgtree.work_items (reviewer_node);

CREATE INDEX work_items_anchor ON orgtree.work_items (anchor_name, archived_at);

CREATE INDEX work_item_participants_name ON orgtree.work_item_participants (value, item_id);

CREATE TABLE orgtree.asks (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "node" text,
  "kind" text,
  "question" text,
  "questions" json,
  "at" timestamptz,
  "at_text" text,
  "options_is" char(1),
  "header" text,
  "work_items_is" char(1),
  "rev" bigint,
  "status" text,
  "reason" text,
  "answer" json,
  "resolved_at" timestamptz,
  "resolved_at_text" text,
  "answer_mail" text,
  "extra" json
);

CREATE TABLE orgtree.ask_options (
  "asks_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "label" text,
  "description" text,
  "extra" json,
  PRIMARY KEY ("asks_id", "pos"),
  FOREIGN KEY ("asks_id") REFERENCES orgtree.asks ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.ask_work_items (
  "asks_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("asks_id", "pos"),
  FOREIGN KEY ("asks_id") REFERENCES orgtree.asks ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX asks_ord ON orgtree.asks (ord);

CREATE TABLE orgtree.credit_requests (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "node" text,
  "old" numeric,
  "new" numeric,
  "reason" text,
  "at" timestamptz,
  "at_text" text,
  "rev" bigint,
  "status" text,
  "granted" numeric,
  "notice" text,
  "extra" json
);

CREATE UNIQUE INDEX credit_requests_ord ON orgtree.credit_requests (ord);

CREATE TABLE orgtree.scope_requests (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "node" text,
  "items_is" char(1),
  "reason" text,
  "at" timestamptz,
  "at_text" text,
  "rev" bigint,
  "status" text,
  "resolved_at" timestamptz,
  "resolved_at_text" text,
  "extra" json
);

CREATE TABLE orgtree.scope_request_items (
  "scope_requests_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "kind" text,
  "path" text,
  "mode" text,
  "decision" text,
  "tool" text,
  "server" text,
  "extra" json,
  PRIMARY KEY ("scope_requests_id", "pos"),
  FOREIGN KEY ("scope_requests_id") REFERENCES orgtree.scope_requests ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX scope_requests_ord ON orgtree.scope_requests (ord);

CREATE TABLE orgtree.audience_grants (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "grantee" text,
  "grantor" text,
  "granted_at" timestamptz,
  "granted_at_text" text,
  "reason" text,
  "delegated_by" text,
  "extra" json
);

CREATE UNIQUE INDEX audience_grants_ord ON orgtree.audience_grants (ord);

CREATE TABLE orgtree.audience_requests (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "node" text,
  "target" text,
  "reason" text,
  "at" timestamptz,
  "at_text" text,
  "status" text,
  "extra" json
);

CREATE UNIQUE INDEX audience_requests_ord ON orgtree.audience_requests (ord);

CREATE TABLE orgtree.watchdogs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "owner" text,
  "name" text,
  "kind" text,
  "target" text,
  "pattern" text,
  "interval_s" bigint,
  "state" text,
  "at" timestamptz,
  "at_text" text,
  "fired" bigint,
  "events_is" char(1),
  "high_water" json,
  "last_check" timestamptz,
  "last_check_text" text,
  "last_check_ts" double precision,
  "checks_run" bigint,
  "last_output" text,
  "paused_why" text,
  "last_exit" bigint,
  "last_fired" timestamptz,
  "last_fired_text" text,
  "history_retained" boolean,
  "notice" boolean,
  "once" boolean,
  "shell" text,
  "fire_mode" text,
  "quiet_period_s" bigint,
  "silence_since" timestamptz,
  "silence_since_text" text,
  "extra" json
);

CREATE TABLE orgtree.watchdog_events (
  "watchdogs_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "gist" text,
  "extra" json,
  PRIMARY KEY ("watchdogs_id", "pos"),
  FOREIGN KEY ("watchdogs_id") REFERENCES orgtree.watchdogs ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX watchdogs_ord ON orgtree.watchdogs (ord);

CREATE TABLE orgtree.watchdog_tombs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "owner" text,
  "name" text,
  "kind" text,
  "target" text,
  "interval_s" bigint,
  "at" timestamptz,
  "at_text" text,
  "spent_at" timestamptz,
  "spent_at_text" text,
  "fired" bigint,
  "orphaned_from" text,
  "notice" boolean,
  "state" text,
  "superseded_by" text,
  "reason" text,
  "once" boolean,
  "fire_mode" text,
  "quiet_period_s" bigint,
  "silence_since" timestamptz,
  "silence_since_text" text,
  "extra" json
);

CREATE UNIQUE INDEX watchdog_tombs_ord ON orgtree.watchdog_tombs (ord);

CREATE TABLE orgtree.watchdog_history (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "gist" text,
  "watchdog" text,
  "node" text,
  "body" text,
  "extra" json
);

CREATE UNIQUE INDEX watchdog_history_ord ON orgtree.watchdog_history (ord);

CREATE TABLE orgtree.reservations (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "owner" text,
  "item" text,
  "resource" text,
  "candidate" text,
  "base" text,
  "paths_is" char(1),
  "state" text,
  "created_at" timestamptz,
  "created_at_text" text,
  "updated_at" timestamptz,
  "updated_at_text" text,
  "created_ts" double precision,
  "updated_ts" double precision,
  "expires_ts" double precision,
  "expires_at" timestamptz,
  "expires_at_text" text,
  "heartbeat_ts" double precision,
  "heartbeat_at" timestamptz,
  "heartbeat_at_text" text,
  "stale_s" double precision,
  "integration_key" text,
  "integration_key_null" boolean,
  "integration_receipt" text,
  "landed_at" timestamptz,
  "landed_at_text" text,
  "release_receipt" text,
  "successor" json,
  "successor_null" boolean,
  "extra" json
);

CREATE TABLE orgtree.reservation_paths (
  "reservations_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("reservations_id", "pos"),
  FOREIGN KEY ("reservations_id") REFERENCES orgtree.reservations ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX reservations_ord ON orgtree.reservations (ord);

CREATE TABLE orgtree.documents (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "node" text,
  "title" text,
  "body" text,
  "at" timestamptz,
  "at_text" text,
  "format" text,
  "file" text,
  "bytes" bigint,
  "orphaned_from" text,
  "extra" json
);

CREATE UNIQUE INDEX documents_ord ON orgtree.documents (ord);

CREATE TABLE orgtree.events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "op" text,
  "actor" text,
  "at" timestamptz,
  "at_text" text,
  "detail" json,
  "warnings_is" char(1),
  "extra" json
);

CREATE TABLE orgtree.event_warnings (
  "events_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("events_id", "pos"),
  FOREIGN KEY ("events_id") REFERENCES orgtree.events ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX events_ord ON orgtree.events (ord);

CREATE TABLE orgtree.lifecycle_events (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "operation_id" text,
  "kind" text,
  "state" text,
  "at" timestamptz,
  "at_text" text,
  "count" bigint,
  "message_id" text,
  "recipient" text,
  "sender" text,
  "delivery" text,
  "waited" text,
  "boundary_for" text,
  "boundary_for_null" boolean,
  "observed" boolean,
  "task_id" text,
  "owner" text,
  "settlement" text,
  "summary" text,
  "item" text,
  "issued_revision" bigint,
  "current_revision" bigint,
  "issued_candidate" text,
  "issued_candidate_null" boolean,
  "current_candidate" json,
  "current_candidate_null" boolean,
  "node" text,
  "cleanup" text,
  "door" text,
  "reason" text,
  "status" text,
  "extra" json
);

CREATE UNIQUE INDEX lifecycle_events_ord ON orgtree.lifecycle_events (ord);

CREATE TABLE orgtree.notice_log (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "node" text,
  "at" timestamptz,
  "at_text" text,
  "text" text,
  "ev" json,
  "extra" json
);

CREATE UNIQUE INDEX notice_log_ord ON orgtree.notice_log (ord);

CREATE TABLE orgtree.org_inbox (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "dir" text,
  "peer" text,
  "body" text,
  "at" timestamptz,
  "at_text" text,
  "by" text,
  "state" text,
  "state_at" timestamptz,
  "state_at_text" text,
  "net_id" text,
  "attributed" boolean,
  "extra" json
);

CREATE UNIQUE INDEX org_inbox_ord ON orgtree.org_inbox (ord);

CREATE TABLE orgtree.user_inbox (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "from" text,
  "kind" text,
  "body" text,
  "at" timestamptz,
  "at_text" text,
  "message_id" text,
  "operation_id" text,
  "attachments_is" char(1),
  "ev" json,
  "extra" json
);

CREATE TABLE orgtree.user_inbox_attachments (
  "user_inbox_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "name" text,
  "path" text,
  "bytes" bigint,
  "extra" json,
  PRIMARY KEY ("user_inbox_id", "pos"),
  FOREIGN KEY ("user_inbox_id") REFERENCES orgtree.user_inbox ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX user_inbox_ord ON orgtree.user_inbox (ord);

CREATE TABLE orgtree.user_outbox (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "from" text,
  "kind" text,
  "body" text,
  "at" timestamptz,
  "at_text" text,
  "relationship" text,
  "message_id" text,
  "operation_id" text,
  "client_op" text,
  "ev" json,
  "to" text,
  "recv_seq" bigint,
  "seq_origin" text,
  "mailbox" text,
  "attachments_is" char(1),
  "reply_to" json,
  "attachments_missing_is" char(1),
  "extra" json
);

CREATE TABLE orgtree.user_outbox_attachments (
  "user_outbox_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "name" text,
  "path" text,
  "bytes" bigint,
  "extra" json,
  PRIMARY KEY ("user_outbox_id", "pos"),
  FOREIGN KEY ("user_outbox_id") REFERENCES orgtree.user_outbox ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.user_outbox_attachments_missing (
  "user_outbox_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("user_outbox_id", "pos"),
  FOREIGN KEY ("user_outbox_id") REFERENCES orgtree.user_outbox ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX user_outbox_ord ON orgtree.user_outbox (ord);

CREATE TABLE orgtree.user_mail_log (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "from" text,
  "kind" text,
  "body" text,
  "at" timestamptz,
  "at_text" text,
  "message_id" text,
  "operation_id" text,
  "attachments_is" char(1),
  "ev" json,
  "urgent" boolean,
  "urgent_reason" text,
  "extra" json
);

CREATE TABLE orgtree.user_mail_log_attachments (
  "user_mail_log_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "name" text,
  "path" text,
  "bytes" bigint,
  "extra" json,
  PRIMARY KEY ("user_mail_log_id", "pos"),
  FOREIGN KEY ("user_mail_log_id") REFERENCES orgtree.user_mail_log ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX user_mail_log_ord ON orgtree.user_mail_log (ord);

CREATE TABLE orgtree.op_receipts (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "v" bigint,
  "public_id" text,
  "at" timestamptz,
  "at_text" text,
  "mint_ms" bigint,
  "node" text,
  "gen" bigint,
  "tool" text,
  "key" text,
  "fp" text,
  "targets" json,
  "cls" text,
  "outcome" text,
  "result" json,
  "ev_from" json,
  "ev_from_null" boolean,
  "ev_to" json,
  "ev_to_null" boolean,
  "post_effects" json,
  "fp_node" text,
  "orphaned_from" text,
  "extra" json
);

CREATE UNIQUE INDEX op_receipts_ord ON orgtree.op_receipts (ord);

CREATE TABLE orgtree.org_dirs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "path" text,
  "mode" text,
  "extra" json
);

CREATE UNIQUE INDEX org_dirs_ord ON orgtree.org_dirs (ord);

CREATE TABLE orgtree.net_hubs (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "public_id" text,
  "address" text,
  "enabled" boolean,
  "name" text,
  "extra" json
);

CREATE UNIQUE INDEX net_hubs_ord ON orgtree.net_hubs (ord);

CREATE TABLE orgtree.orphan_keys (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "key" text NOT NULL UNIQUE,
  "from" text,
  "at" timestamptz,
  "at_text" text,
  "cause" text,
  "arriving_seat" json,
  "owner" json,
  "owner_null" boolean,
  "sections_is" char(1),
  "extra" json
);

CREATE TABLE orgtree.orphan_key_sections (
  "orphan_keys_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("orphan_keys_id", "pos"),
  FOREIGN KEY ("orphan_keys_id") REFERENCES orgtree.orphan_keys ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.mail (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "public_id" text,
  "from" text,
  "kind" text,
  "body" text,
  "at" timestamptz,
  "at_text" text,
  "relationship" text,
  "restart_notice" boolean,
  "ev" json,
  "recv_seq" bigint,
  "seq_origin" text,
  "mailbox" text,
  "message_id" text,
  "operation_id" text,
  "redelivered" bigint,
  "extra" json
);

CREATE UNIQUE INDEX mail_owner ON orgtree.mail (agent_id, idx);

CREATE TABLE orgtree.notices (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "text" text,
  "ev" json,
  "extra" json
);

CREATE UNIQUE INDEX notices_owner ON orgtree.notices (agent_id, idx);

CREATE TABLE orgtree.delivery_batches (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "tok" text,
  "at" timestamptz,
  "at_text" text,
  "mail" json,
  "notices" json,
  "via" text,
  "custody_is" char(1),
  "custody_mailbox" text,
  "custody_generation" bigint,
  "custody_session" text,
  "engines" json,
  "mode" text,
  "attempt" json,
  "drive" json,
  "drive_null" boolean,
  "segments" json,
  "manual" json,
  "claim_is" char(1),
  "claim_delivery_id" text,
  "claim_tool_use_id" text,
  "claim_claimed_at" double precision,
  "claim_lease_until" double precision,
  "attempts" bigint,
  "delivery_ids_is" char(1),
  "extra" json
);

CREATE TABLE orgtree.delivery_batch_ids (
  "delivery_batches_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("delivery_batches_id", "pos"),
  FOREIGN KEY ("delivery_batches_id") REFERENCES orgtree.delivery_batches ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX delivery_batches_owner ON orgtree.delivery_batches (agent_id, idx);

CREATE TABLE orgtree.mail_log (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "public_id" text,
  "from" text,
  "kind" text,
  "body" text,
  "at" timestamptz,
  "at_text" text,
  "relationship" text,
  "message_id" text,
  "operation_id" text,
  "client_op" text,
  "ev" json,
  "restart_notice" boolean,
  "recv_seq" bigint,
  "seq_origin" text,
  "mailbox" text,
  "attachments_is" char(1),
  "stale" boolean,
  "stale_at" timestamptz,
  "stale_at_text" text,
  "stale_revision" bigint,
  "stale_candidate" text,
  "stale_candidate_null" boolean,
  "net_id" text,
  "reply_to" json,
  "model_only" boolean,
  "retracted" boolean,
  "attachments_missing_is" char(1),
  "extra" json
);

CREATE TABLE orgtree.mail_log_attachments (
  "mail_log_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "name" text,
  "path" text,
  "bytes" bigint,
  "extra" json,
  PRIMARY KEY ("mail_log_id", "pos"),
  FOREIGN KEY ("mail_log_id") REFERENCES orgtree.mail_log ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.mail_log_attachments_missing (
  "mail_log_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("mail_log_id", "pos"),
  FOREIGN KEY ("mail_log_id") REFERENCES orgtree.mail_log ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX mail_log_owner ON orgtree.mail_log (agent_id, idx);

CREATE TABLE orgtree.steer_records (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "delivery_id" text,
  "level" text,
  "mail_ids_is" char(1),
  "delivery_ids_is" char(1),
  "acked_ids_is" char(1),
  "recorded_ids_is" char(1),
  "attempts" bigint,
  "retried" boolean,
  "confirmed_duplicate" boolean,
  "text" text,
  "visible_id" text,
  "segments" json,
  "fold" bigint,
  "where" text,
  "outcome" text,
  "extra" json
);

CREATE TABLE orgtree.steer_record_mail_ids (
  "steer_records_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("steer_records_id", "pos"),
  FOREIGN KEY ("steer_records_id") REFERENCES orgtree.steer_records ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.steer_record_delivery_ids (
  "steer_records_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("steer_records_id", "pos"),
  FOREIGN KEY ("steer_records_id") REFERENCES orgtree.steer_records ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.steer_record_acked_ids (
  "steer_records_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("steer_records_id", "pos"),
  FOREIGN KEY ("steer_records_id") REFERENCES orgtree.steer_records ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.steer_record_recorded_ids (
  "steer_records_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("steer_records_id", "pos"),
  FOREIGN KEY ("steer_records_id") REFERENCES orgtree.steer_records ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX steer_records_owner ON orgtree.steer_records (agent_id, idx);

CREATE TABLE orgtree.agent_turns (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "n" bigint,
  "at" timestamptz,
  "at_text" text,
  "cost" double precision,
  "ms" bigint,
  "ms_null" boolean,
  "toks" bigint,
  "denials" bigint,
  "approvals" bigint,
  "ran_as" text,
  "killed" boolean,
  "estimated" boolean,
  "cost_complete" boolean,
  "cost_source" text,
  "cost_unknown_fields" json,
  "route" json,
  "reported" json,
  "model_usage_key" json,
  "extra" json
);

CREATE UNIQUE INDEX agent_turns_owner ON orgtree.agent_turns (agent_id, idx);

CREATE TABLE orgtree.agent_turn_errors (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "text" text,
  "ran_as" text,
  "extra" json
);

CREATE UNIQUE INDEX agent_turn_errors_owner ON orgtree.agent_turn_errors (agent_id, idx);

CREATE TABLE orgtree.work_scope_log (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "seq" bigint,
  "at" timestamptz,
  "at_text" text,
  "by_is" char(1),
  "by_node" text,
  "by_generation" bigint,
  "kind" text,
  "text" text,
  "supersedes" bigint,
  "supersedes_null" boolean,
  "superseded_by" bigint,
  "superseded_by_null" boolean,
  "before" text,
  "after" text,
  "mode" text,
  "extra" json
);

CREATE UNIQUE INDEX work_scope_log_owner ON orgtree.work_scope_log (agent_id, idx);

CREATE TABLE orgtree.mail_transitions (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "key" text NOT NULL,
  "operation" text,
  "outcome" text,
  "node" text,
  "identity" json,
  "before" json,
  "deliveries" json,
  "extra" json
);

CREATE UNIQUE INDEX mail_transitions_owner ON orgtree.mail_transitions (agent_id, "key");

CREATE TABLE orgtree.manual_attempts (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "key" text NOT NULL,
  "v" bigint,
  "at" timestamptz,
  "at_text" text,
  "tok" text,
  "mailbox" text,
  "generation" bigint,
  "session" text,
  "attempt" text,
  "engine" text,
  "delivery_id" text,
  "seat" text,
  "op_key" text,
  "op_id" text,
  "mail_ids_is" char(1),
  "digests" json,
  "provider_call_id" json,
  "provider_call_id_null" boolean,
  "call_id_source" text,
  "resolved" json,
  "resolved_null" boolean,
  "chunk_calls" json,
  "extra" json
);

CREATE TABLE orgtree.manual_attempt_mail_ids (
  "manual_attempts_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("manual_attempts_id", "pos"),
  FOREIGN KEY ("manual_attempts_id") REFERENCES orgtree.manual_attempts ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX manual_attempts_owner ON orgtree.manual_attempts (agent_id, "key");

CREATE TABLE orgtree.steer_attempts (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  agent_id bigint NOT NULL REFERENCES orgtree.agents (id) ON DELETE CASCADE,
  idx integer NOT NULL,
  "key" text NOT NULL,
  "at" timestamptz,
  "at_text" text,
  "tool_use_id" text,
  "toks_is" char(1),
  "mail_ids_is" char(1),
  "transcript_path" text,
  "tp_offset" bigint,
  "texts_n" bigint,
  "retried" boolean,
  "acked_at" timestamptz,
  "acked_at_text" text,
  "recorded_at" timestamptz,
  "recorded_at_text" text,
  "resolved" text,
  "views_is" char(1),
  "view_segments" json,
  "extra" json
);

CREATE TABLE orgtree.steer_attempt_toks (
  "steer_attempts_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("steer_attempts_id", "pos"),
  FOREIGN KEY ("steer_attempts_id") REFERENCES orgtree.steer_attempts ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.steer_attempt_mail_ids (
  "steer_attempts_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("steer_attempts_id", "pos"),
  FOREIGN KEY ("steer_attempts_id") REFERENCES orgtree.steer_attempts ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.steer_attempt_views (
  "steer_attempts_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("steer_attempts_id", "pos"),
  FOREIGN KEY ("steer_attempts_id") REFERENCES orgtree.steer_attempts ("id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX steer_attempts_owner ON orgtree.steer_attempts (agent_id, "key");

CREATE TABLE orgtree.org_doc_migrations (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "key" text NOT NULL UNIQUE,
  "at" timestamptz,
  "at_text" text,
  "repaired" bigint,
  "stripped" bigint,
  "mode" text,
  "holders_is" char(1),
  "multi_holder" boolean,
  "healed_is" char(1),
  "minted" bigint,
  "shared" bigint,
  "extra" json
);

CREATE TABLE orgtree.org_doc_migration_holders (
  "org_doc_migrations_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("org_doc_migrations_id", "pos"),
  FOREIGN KEY ("org_doc_migrations_id") REFERENCES orgtree.org_doc_migrations ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.org_doc_migration_healed (
  "org_doc_migrations_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("org_doc_migrations_id", "pos"),
  FOREIGN KEY ("org_doc_migrations_id") REFERENCES orgtree.org_doc_migrations ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.net_state (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "key" text NOT NULL UNIQUE,
  "registered_at" timestamptz,
  "registered_at_text" text,
  "address" text,
  "seen_ids_is" char(1),
  "extra" json
);

CREATE TABLE orgtree.net_state_seen_ids (
  "net_state_id" bigint NOT NULL,
  "pos" integer NOT NULL,
  "value" text,
  PRIMARY KEY ("net_state_id", "pos"),
  FOREIGN KEY ("net_state_id") REFERENCES orgtree.net_state ("id") ON DELETE CASCADE
);

CREATE TABLE orgtree.org_tier_prices (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "key" text NOT NULL UNIQUE,
  "value" numeric,
  "extra" json
);

CREATE TABLE orgtree.org_tier_models (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ord bigint NOT NULL,
  "key" text NOT NULL UNIQUE,
  "value" text,
  "extra" json
);

CREATE TABLE orgtree.retired_slugs (
  ord bigint PRIMARY KEY,
  "value" text
);
