-- GENERATED by orgdb.record_panel_sql.migration_sql.

CREATE INDEX user_mail_log_record_window ON orgtree.user_mail_log (id DESC NULLS LAST);
CREATE INDEX user_outbox_record_window ON orgtree.user_outbox (id DESC NULLS LAST);
CREATE INDEX events_record_window ON orgtree.events (id DESC NULLS LAST);

CREATE INDEX event_refs_record_window ON orgtree.event_refs (ref, win_at DESC NULLS LAST, event_id DESC NULLS LAST);
CREATE INDEX notice_log_record_window ON orgtree.notice_log (win_node, win_at DESC NULLS LAST, id DESC NULLS LAST);


CREATE INDEX record_mail_owner_sender ON orgtree.mail_log(agent_id,win_from,win_at DESC,id DESC);
CREATE FUNCTION orgtree.record_mail_senders(owner_id bigint, cap integer) RETURNS SETOF text
LANGUAGE sql STABLE SET search_path=pg_catalog,orgtree AS $fn$
  WITH RECURSIVE senders(win_from, n) AS (
    (SELECT m.win_from, 1 FROM orgtree.mail_log m
     WHERE m.agent_id=owner_id AND m.win_from IS NOT NULL AND cap>0
     ORDER BY m.win_from LIMIT 1)
    UNION ALL
    SELECT next.win_from, s.n+1 FROM senders s CROSS JOIN LATERAL
      (SELECT m.win_from FROM orgtree.mail_log m
       WHERE m.agent_id=owner_id AND m.win_from>s.win_from
       ORDER BY m.win_from LIMIT 1) next WHERE s.n<cap)
  SELECT win_from FROM senders;
$fn$;
CREATE FUNCTION orgtree.record_sent_ids(sender text, cap integer) RETURNS SETOF bigint
LANGUAGE plpgsql STABLE SET search_path=pg_catalog,orgtree AS $fn$
DECLARE head bigint[]; edge text; kept bigint[]; owner_row record; extra_ids bigint[];
BEGIN
  IF cap<=0 THEN RETURN; END IF;
  SELECT array_agg(n.id ORDER BY n.win_at DESC,k.first DESC,n.id DESC) INTO head
    FROM (SELECT m.id,m.win_at,m.agent_id FROM orgtree.mail_log m
          WHERE m.win_from=sender ORDER BY m.win_at DESC LIMIT cap+1) n
    CROSS JOIN LATERAL (SELECT f.id AS first FROM orgtree.mail_log f
      WHERE f.agent_id>=n.agent_id ORDER BY f.agent_id,f.id LIMIT 1) k;
  IF coalesce(cardinality(head),0)<=cap THEN RETURN QUERY SELECT unnest(head); RETURN; END IF;
  SELECT m.win_at INTO edge FROM orgtree.mail_log m WHERE m.id=head[cardinality(head)];
  IF (SELECT count(*) FROM orgtree.mail_log m WHERE m.id=ANY(head) AND m.win_at=edge)=1 THEN
    RETURN QUERY SELECT unnest(head[1:cap]); RETURN;
  END IF;
  SELECT coalesce(array_agg(x.id ORDER BY x.ord),ARRAY[]::bigint[]) INTO kept
    FROM unnest(head) WITH ORDINALITY x(id,ord) JOIN orgtree.mail_log m ON m.id=x.id
    WHERE m.win_at<>edge;
  FOR owner_row IN
    WITH RECURSIVE owners(agent_id) AS (
      (SELECT m.agent_id FROM orgtree.mail_log m WHERE m.win_from=sender AND m.win_at=edge
       ORDER BY m.agent_id LIMIT 1)
      UNION ALL SELECT (SELECT m.agent_id FROM orgtree.mail_log m
        WHERE m.win_from=sender AND m.win_at=edge AND m.agent_id>o.agent_id
        ORDER BY m.agent_id LIMIT 1) FROM owners o WHERE o.agent_id IS NOT NULL)
    SELECT o.agent_id FROM owners o CROSS JOIN LATERAL
      (SELECT f.id AS first FROM orgtree.mail_log f WHERE f.agent_id>=o.agent_id
       ORDER BY f.agent_id,f.id LIMIT 1) k
    WHERE o.agent_id IS NOT NULL ORDER BY k.first DESC
  LOOP
    EXIT WHEN cardinality(kept)>=cap;
    SELECT array_agg(x.id ORDER BY x.id DESC) INTO extra_ids FROM
      (SELECT m.id FROM orgtree.mail_log m WHERE m.win_from=sender AND m.win_at=edge
       AND m.agent_id>=owner_row.agent_id AND m.agent_id<=owner_row.agent_id
       ORDER BY m.agent_id DESC,m.id DESC LIMIT cap-cardinality(kept)) x;
    kept := kept||coalesce(extra_ids,ARRAY[]::bigint[]);
  END LOOP;
  RETURN QUERY SELECT unnest(kept);
END
$fn$;

CREATE OR REPLACE FUNCTION orgtree.resolve_scopes() RETURNS void
LANGUAGE plpgsql VOLATILE SET search_path=pg_catalog,orgtree AS $fn$
DECLARE scope_row record; partition_key text; named_count bigint; pile_parent bigint;
BEGIN
  PERFORM set_config('orgtree.pending_scopes','',true);
  -- Snapshot is taken AFTER the revision singleton by the caller. Reads below
  -- never lock another writer's source row; writes use ONLY this transaction's xid.

  INSERT INTO orgtree.changes(xid,entity,entity_id)
    SELECT pg_current_xact_id(),'history_name:'||r.ref,'event:'||r.event_id
    FROM orgtree.changes c JOIN orgtree.event_refs r
      ON r.event_id=substring(c.entity_id FROM length('history_event:')+1)::bigint
    WHERE c.xid=pg_current_xact_id() AND c.entity='~scope'
      AND c.entity_id LIKE 'history_event:%' ON CONFLICT DO NOTHING;

  FOR scope_row IN SELECT entity_id FROM orgtree.changes
      WHERE xid=pg_current_xact_id() AND entity='~scope' ORDER BY entity_id
  LOOP
    partition_key := substring(scope_row.entity_id FROM position(':' IN scope_row.entity_id)+1);
    IF scope_row.entity_id LIKE 'name:%' THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',id::text FROM orgtree.agents
        WHERE name=partition_key AND NOT tombstone ON CONFLICT DO NOTHING;
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'~scope','detail:'||id::text FROM orgtree.agents
        WHERE name=partition_key AND NOT tombstone ON CONFLICT DO NOTHING;
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'~scope','lineage:'||id::text FROM orgtree.agents
        WHERE name=partition_key AND NOT tombstone ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'references:%' THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',id::text FROM orgtree.agents
        WHERE parent_id=partition_key::bigint OR predecessor_id=partition_key::bigint
           OR successor_id=partition_key::bigint ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'refname:%' THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',id::text FROM orgtree.agents
        WHERE parent=partition_key OR predecessor=partition_key OR successor=partition_key
        ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'tools:%' THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',id::text FROM orgtree.agents
        WHERE tool_list_id=partition_key::bigint ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'ask:%' THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',a.id::text FROM orgtree.asks q
        JOIN orgtree.agents a ON a.name=q.node AND NOT a.tombstone
        WHERE q.id=partition_key::bigint ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'request:%' THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',a.id::text FROM orgtree.scope_requests q
        JOIN orgtree.agents a ON a.name=q.node AND NOT a.tombstone
        WHERE q.id=partition_key::bigint ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'turn:%' THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',agent_id::text FROM orgtree.agent_turns
        WHERE id=partition_key::bigint ON CONFLICT DO NOTHING;
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'~scope','detail:'||agent_id::text FROM orgtree.agent_turns
        WHERE id=partition_key::bigint ON CONFLICT DO NOTHING;
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'~scope','lineage:'||agent_id::text FROM orgtree.agent_turns
        WHERE id=partition_key::bigint ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'delivery:%' THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',agent_id::text FROM orgtree.delivery_batches
        WHERE id=partition_key::bigint ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'chain:%' THEN
      WITH RECURSIVE chain(id,parent_id,path) AS (
        SELECT id,parent_id,ARRAY[id] FROM orgtree.agents WHERE id=partition_key::bigint
        UNION ALL SELECT a.id,a.parent_id,c.path||a.id FROM chain c
        JOIN orgtree.agents a ON a.id=c.parent_id WHERE NOT a.id=ANY(c.path))
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',id::text FROM chain ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'lineage:%' THEN
      -- Body lineage follows predecessor links, including inconsistent legacy
      -- successor pointers. Resolve every dependent successor, not just one edge.
      WITH RECURSIVE lineage(id,path) AS (
        SELECT id,ARRAY[id] FROM orgtree.agents WHERE id=partition_key::bigint
        UNION ALL SELECT a.id,c.path||a.id FROM lineage c
        JOIN orgtree.agents a ON a.predecessor_id=c.id WHERE NOT a.id=ANY(c.path))
      INSERT INTO orgtree.changes(xid,entity,entity_id)
        SELECT pg_current_xact_id(),'agent',id::text FROM lineage ON CONFLICT DO NOTHING;
    ELSIF scope_row.entity_id LIKE 'window:%' THEN
      IF scope_row.entity_id LIKE 'window:user_mail_log:%' THEN
        partition_key := substring(scope_row.entity_id FROM 22);
        SELECT count(*) INTO named_count FROM orgtree.changes WHERE xid=pg_current_xact_id() AND entity='user_mail_log:'||partition_key;
        WITH candidates AS ((SELECT (r.id::text)::text AS id, r.id AS key0 FROM orgtree.user_mail_log r WHERE ('shared')::text = partition_key AND (true) ORDER BY key0 DESC NULLS LAST, (r.id::text)::text COLLATE "C" LIMIT 50 + named_count)), ranked AS (SELECT id, row_number() OVER (ORDER BY key0 DESC NULLS LAST, id COLLATE "C") AS rank FROM candidates) INSERT INTO orgtree.changes(xid,entity,entity_id) SELECT pg_current_xact_id(), 'user_mail_log:' || partition_key, id FROM ranked WHERE rank BETWEEN greatest(1,50-named_count+1) AND 50+named_count ON CONFLICT DO NOTHING;
        CONTINUE;
      END IF;
      IF scope_row.entity_id LIKE 'window:user_outbox:%' THEN
        partition_key := substring(scope_row.entity_id FROM 20);
        SELECT count(*) INTO named_count FROM orgtree.changes WHERE xid=pg_current_xact_id() AND entity='user_outbox:'||partition_key;
        WITH candidates AS ((SELECT (r.id::text)::text AS id, r.id AS key0 FROM orgtree.user_outbox r WHERE ('shared')::text = partition_key AND (true) ORDER BY key0 DESC NULLS LAST, (r.id::text)::text COLLATE "C" LIMIT 50 + named_count)), ranked AS (SELECT id, row_number() OVER (ORDER BY key0 DESC NULLS LAST, id COLLATE "C") AS rank FROM candidates) INSERT INTO orgtree.changes(xid,entity,entity_id) SELECT pg_current_xact_id(), 'user_outbox:' || partition_key, id FROM ranked WHERE rank BETWEEN greatest(1,50-named_count+1) AND 50+named_count ON CONFLICT DO NOTHING;
        CONTINUE;
      END IF;
      IF scope_row.entity_id LIKE 'window:event:%' THEN
        partition_key := substring(scope_row.entity_id FROM 14);
        SELECT count(*) INTO named_count FROM orgtree.changes WHERE xid=pg_current_xact_id() AND entity='event:'||partition_key;
        WITH candidates AS ((SELECT (r.id::text)::text AS id, r.id AS key0 FROM orgtree.events r WHERE ('shared')::text = partition_key AND (true) ORDER BY key0 DESC NULLS LAST, (r.id::text)::text COLLATE "C" LIMIT 300 + named_count)), ranked AS (SELECT id, row_number() OVER (ORDER BY key0 DESC NULLS LAST, id COLLATE "C") AS rank FROM candidates) INSERT INTO orgtree.changes(xid,entity,entity_id) SELECT pg_current_xact_id(), 'event:' || partition_key, id FROM ranked WHERE rank BETWEEN greatest(1,300-named_count+1) AND 300+named_count ON CONFLICT DO NOTHING;
        CONTINUE;
      END IF;
      IF scope_row.entity_id LIKE 'window:history_name:%' THEN
        partition_key := substring(scope_row.entity_id FROM 21);
        SELECT count(*) INTO named_count FROM orgtree.changes WHERE xid=pg_current_xact_id() AND entity='history_name:'||partition_key;
        WITH candidates AS ((SELECT ('event:'||r.event_id)::text AS id, r.win_at AS key0, 0 AS key1, r.event_id AS key2 FROM orgtree.event_refs r WHERE (r.ref)::text = partition_key AND (true) ORDER BY key0 DESC NULLS LAST, key1 DESC NULLS LAST, key2 DESC NULLS LAST, ('event:'||r.event_id)::text COLLATE "C" LIMIT 80 + named_count) UNION ALL (SELECT ('notice:'||r.id)::text AS id, r.win_at AS key0, 1 AS key1, r.id AS key2 FROM orgtree.notice_log r WHERE (r.win_node)::text = partition_key AND (true) ORDER BY key0 DESC NULLS LAST, key1 DESC NULLS LAST, key2 DESC NULLS LAST, ('notice:'||r.id)::text COLLATE "C" LIMIT 80 + named_count)), ranked AS (SELECT id, row_number() OVER (ORDER BY key0 DESC NULLS LAST, key1 DESC NULLS LAST, key2 DESC NULLS LAST, id COLLATE "C") AS rank FROM candidates) INSERT INTO orgtree.changes(xid,entity,entity_id) SELECT pg_current_xact_id(), 'history_name:' || partition_key, id FROM ranked WHERE rank BETWEEN greatest(1,80-named_count+1) AND 80+named_count ON CONFLICT DO NOTHING;
        CONTINUE;
      END IF;
      RAISE EXCEPTION 'undeclared record window scope: %', scope_row.entity_id;
    END IF;
  END LOOP;

  INSERT INTO orgtree.changes(xid,entity,entity_id)
    SELECT pg_current_xact_id(),'agent_history:'||a.id,c.entity_id
    FROM orgtree.changes c JOIN orgtree.agents a
      ON a.name=substring(c.entity FROM length('history_name:')+1) AND NOT a.tombstone
    WHERE c.xid=pg_current_xact_id() AND c.entity LIKE 'history_name:%'
    ON CONFLICT DO NOTHING;


  -- Resolve child rows through their current parent, never in their capture.
  INSERT INTO orgtree.changes(xid,entity,entity_id)
    SELECT pg_current_xact_id(),'agent_mail:'||m.agent_id,
      m.agent_id||'/delivered:mail_log:'||m.id
    FROM orgtree.changes c JOIN orgtree.mail_log m ON
      m.id=CASE WHEN c.entity_id LIKE 'mail_child:mail_log:%' THEN split_part(c.entity_id,':',3)::bigint END
    WHERE c.xid=pg_current_xact_id() AND c.entity='~scope' ON CONFLICT DO NOTHING;
  INSERT INTO orgtree.changes(xid,entity,entity_id)
    SELECT pg_current_xact_id(),'~mail_sent:'||m.win_from,'mail_log:'||m.id
    FROM orgtree.changes c JOIN orgtree.mail_log m ON
      m.id=CASE WHEN c.entity_id LIKE 'mail_child:mail_log:%' THEN split_part(c.entity_id,':',3)::bigint END
    WHERE c.xid=pg_current_xact_id() AND c.entity='~scope' ON CONFLICT DO NOTHING;
  INSERT INTO orgtree.changes(xid,entity,entity_id)
    SELECT pg_current_xact_id(),'~mail_sent:'||m."from",'user_inbox:'||m.id
    FROM orgtree.changes c JOIN orgtree.user_inbox m ON
      m.id=CASE WHEN c.entity_id LIKE 'mail_child:user_inbox:%' THEN split_part(c.entity_id,':',3)::bigint END
    WHERE c.xid=pg_current_xact_id() AND c.entity='~scope' ON CONFLICT DO NOTHING;
  INSERT INTO orgtree.changes(xid,entity,entity_id)
    SELECT pg_current_xact_id(),'~mail_sent:'||m.win_from,'user_mail_log:'||m.id
    FROM orgtree.changes c JOIN orgtree.user_mail_log m ON
      m.id=CASE WHEN c.entity_id LIKE 'mail_child:user_mail_log:%' THEN split_part(c.entity_id,':',3)::bigint END
    WHERE c.xid=pg_current_xact_id() AND c.entity='~scope' ON CONFLICT DO NOTHING;
  -- Any change in a recipient archive can move its first-row tie key. Dirty
  -- each sender's bounded recipient tail and its complete selection boundary.
  FOR scope_row IN SELECT entity_id FROM orgtree.changes
    WHERE xid=pg_current_xact_id() AND entity='~scope' AND entity_id LIKE 'mail_recipient:%'
  LOOP
    partition_key := substring(scope_row.entity_id FROM length('mail_recipient:')+1);
    INSERT INTO orgtree.changes(xid,entity,entity_id)
      SELECT pg_current_xact_id(),'~scope','mail_sender:'||x.win_from FROM
      orgtree.record_mail_senders(partition_key::bigint,2001) x(win_from)
      ON CONFLICT DO NOTHING;
    INSERT INTO orgtree.changes(xid,entity,entity_id)
      SELECT pg_current_xact_id(),'~mail_sent:'||s.win_from,'mail_log:'||m.id
      FROM orgtree.record_mail_senders(partition_key::bigint,2001) s(win_from) CROSS JOIN LATERAL
      (SELECT id FROM orgtree.mail_log WHERE agent_id=partition_key::bigint AND win_from=s.win_from
       ORDER BY win_at DESC,id DESC LIMIT 50) m LIMIT 2001 ON CONFLICT DO NOTHING;
    IF (SELECT count(*) FROM orgtree.changes WHERE xid=pg_current_xact_id())>2000 THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id) VALUES(pg_current_xact_id(),'reset','mail-bound') ON CONFLICT DO NOTHING;
      RETURN;
    END IF;
  END LOOP;
  -- Every captured old/new pending size contributes to the boundary allowance,
  -- including a batch removed entirely in this transaction.
  SELECT count(*)+coalesce(sum(CASE WHEN entity='~scope' AND entity_id LIKE 'mail_pending_size:%'
    THEN split_part(entity_id,':',4)::bigint ELSE 0 END),0) INTO named_count
    FROM orgtree.changes WHERE xid=pg_current_xact_id();
  IF named_count>2000 THEN
    INSERT INTO orgtree.changes(xid,entity,entity_id) VALUES(pg_current_xact_id(),'reset','mail-bound') ON CONFLICT DO NOTHING;
    RETURN;
  END IF;
  FOR scope_row IN SELECT entity_id FROM orgtree.changes
    WHERE xid=pg_current_xact_id() AND entity='~scope' AND entity_id LIKE 'mail_owner:%'
  LOOP
    partition_key := substring(scope_row.entity_id FROM length('mail_owner:')+1);
    INSERT INTO orgtree.changes(xid,entity,entity_id)
      SELECT pg_current_xact_id(),'agent_mail:'||partition_key,
        partition_key||'/delivered:mail_log:'||m.id FROM orgtree.mail_log m
      WHERE agent_id=partition_key::bigint ORDER BY idx DESC
      LIMIT 50+40+named_count+
        (SELECT count(*) FROM orgtree.mail WHERE agent_id=partition_key::bigint)+
        (SELECT coalesce(sum(CASE WHEN json_typeof(mail)='array' THEN json_array_length(mail) ELSE 0 END),0)
         FROM orgtree.delivery_batches WHERE agent_id=partition_key::bigint)
      ON CONFLICT DO NOTHING;
  END LOOP;
  FOR scope_row IN SELECT entity_id FROM orgtree.changes
    WHERE xid=pg_current_xact_id() AND entity='~scope' AND entity_id LIKE 'mail_sender:%'
  LOOP
    partition_key := substring(scope_row.entity_id FROM length('mail_sender:')+1);
    INSERT INTO orgtree.changes(xid,entity,entity_id)
      SELECT pg_current_xact_id(),'~mail_sent:'||partition_key,'mail_log:'||id
      FROM orgtree.record_sent_ids(partition_key,(50+named_count)::integer) id
      ON CONFLICT DO NOTHING;
    INSERT INTO orgtree.changes(xid,entity,entity_id)
      SELECT pg_current_xact_id(),'~mail_sent:'||partition_key,'user_inbox:'||id
      FROM orgtree.user_inbox WHERE "from"=partition_key LIMIT 2001 ON CONFLICT DO NOTHING;
    INSERT INTO orgtree.changes(xid,entity,entity_id)
      SELECT pg_current_xact_id(),'~mail_sent:'||partition_key,'user_mail_log:'||id
      FROM orgtree.user_mail_log WHERE win_from=partition_key ORDER BY win_at DESC,id DESC
      LIMIT 50+named_count ON CONFLICT DO NOTHING;
    IF (SELECT count(*) FROM orgtree.changes WHERE xid=pg_current_xact_id())>2000 THEN
      INSERT INTO orgtree.changes(xid,entity,entity_id) VALUES(pg_current_xact_id(),'reset','mail-bound') ON CONFLICT DO NOTHING;
      RETURN;
    END IF;
  END LOOP;
  INSERT INTO orgtree.changes(xid,entity,entity_id)
    SELECT pg_current_xact_id(),'agent_mail:'||a.id,a.id||'/sent:'||c.entity_id
    FROM orgtree.changes c JOIN orgtree.agents a
      ON a.name=substring(c.entity FROM length('~mail_sent:')+1) AND NOT a.tombstone
    WHERE c.xid=pg_current_xact_id() AND c.entity LIKE '~mail_sent:%' ON CONFLICT DO NOTHING;

  -- Name scopes can add a lineage scope while the cursor above is already
  -- open. Walk the complete final set here, including those newly added rows.
  WITH RECURSIVE lineage(id,path) AS (
    SELECT split_part(entity_id,':',2)::bigint,
           ARRAY[split_part(entity_id,':',2)::bigint] FROM orgtree.changes
    WHERE xid=pg_current_xact_id() AND entity='~scope' AND entity_id LIKE 'lineage:%'
    UNION ALL SELECT a.id,c.path||a.id FROM lineage c
    JOIN orgtree.agents a ON a.predecessor_id=c.id WHERE NOT a.id=ANY(c.path))
  INSERT INTO orgtree.changes(xid,entity,entity_id)
    SELECT pg_current_xact_id(),'agent',id::text FROM lineage ON CONFLICT DO NOTHING;
  -- Distinct parents, not one read per touched child. n counts the transaction's
  -- distinct pile scopes; it covers both removed and added children and P itself.
  FOR pile_parent,named_count IN
    SELECT split_part(entity_id,':',2)::bigint,count(*) FROM orgtree.changes
    WHERE xid=pg_current_xact_id() AND entity='~scope' AND entity_id LIKE 'pile:%'
    GROUP BY split_part(entity_id,':',2)::bigint ORDER BY 1
  LOOP
    INSERT INTO orgtree.changes(xid,entity,entity_id)
      SELECT pg_current_xact_id(),'agent',id::text FROM (
        (SELECT a.id FROM orgtree.agents a LEFT JOIN orgtree.agents s ON s.id=a.successor_id
         WHERE NOT a.tombstone AND a.state='archived'
           AND a.parent_id IS NOT DISTINCT FROM nullif(pile_parent,0)
           AND (a.successor_id IS NULL OR s.name='')
         ORDER BY coalesce(a.ui_order,0),orgtree.foreground_time(a.created,a.created_text),a.ord,a.name COLLATE "C"
         LIMIT named_count+1)
        UNION
        (SELECT a.id FROM orgtree.agents a LEFT JOIN orgtree.agents s ON s.id=a.successor_id
         WHERE NOT a.tombstone AND a.state='archived'
           AND a.parent_id IS NOT DISTINCT FROM nullif(pile_parent,0)
           AND (a.successor_id IS NULL OR s.name='')
         ORDER BY coalesce(a.ui_order,0) DESC,orgtree.foreground_time(a.created,a.created_text) DESC,
                  a.ord DESC,a.name COLLATE "C" DESC LIMIT named_count+1)
      ) edges ON CONFLICT DO NOTHING;
  END LOOP;
END
$fn$;
DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.agents;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.agents;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.agents;

CREATE OR REPLACE FUNCTION orgtree.record_capture_agents() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent' AS entity, r.id::text AS entity_id FROM new_rows r WHERE r.id IS NOT NULL
        UNION ALL
        SELECT 'agent' AS entity, r.parent_id::text AS entity_id FROM new_rows r WHERE r.parent_id IS NOT NULL
        UNION ALL
        SELECT 'agent' AS entity, r.predecessor_id::text AS entity_id FROM new_rows r WHERE r.predecessor_id IS NOT NULL
        UNION ALL
        SELECT 'agent' AS entity, r.successor_id::text AS entity_id FROM new_rows r WHERE r.successor_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'pile:' || (coalesce(r.parent_id, 0)::text || ':' || r.id::text)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'pile:' || (r.id::text || ':-')::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'chain:' || (r.parent_id)::text AS entity_id FROM new_rows r WHERE r.parent_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.successor_id)::text AS entity_id FROM new_rows r WHERE r.successor_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'references:' || (r.id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'refname:' || (r.name)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'subtree:' || (r.id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'org' AS entity, 'cost' AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'org' AS entity, 'audit' AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'org' AS entity, 'foreground' AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'org' AS entity, 'org_inbox' AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'history_identity:' || (r.id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_identity:' || (r.id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_recipient:' || (r.id)::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent' AS entity, r.id::text AS entity_id FROM old_rows r WHERE (r.id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent' AS entity, r.parent_id::text AS entity_id FROM old_rows r WHERE (r.parent_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent' AS entity, r.predecessor_id::text AS entity_id FROM old_rows r WHERE (r.predecessor_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent' AS entity, r.successor_id::text AS entity_id FROM old_rows r WHERE (r.successor_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'pile:' || (coalesce(r.parent_id, 0)::text || ':' || r.id::text)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'pile:' || (r.id::text || ':-')::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'chain:' || (r.parent_id)::text AS entity_id FROM old_rows r WHERE (r.parent_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.successor_id)::text AS entity_id FROM old_rows r WHERE (r.successor_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'references:' || (r.id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'refname:' || (r.name)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'subtree:' || (r.id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE p.id=r.id AND to_json(ROW(r.parent,r.parent_id,r.parent_misfit,r.state,r.state_misfit,r.tombstone,r.extra,r.scope_is,r.scope_permission_mode,r.scope_org_visibility,r.scope_effort,r.scope_model_version,r.scope_prefer_reserve,r.scope_account_fallback,r.scope_tools_is,r.scope_tools_bash,r.scope_tools_web,r.scope_tools_edit,r.scope_tools_subagents,r.scope_tools_mcp_is,r.scope_add_dirs_is))::text=to_json(ROW(p.parent,p.parent_id,p.parent_misfit,p.state,p.state_misfit,p.tombstone,p.extra,p.scope_is,p.scope_permission_mode,p.scope_org_visibility,p.scope_effort,p.scope_model_version,p.scope_prefer_reserve,p.scope_account_fallback,p.scope_tools_is,p.scope_tools_bash,p.scope_tools_web,p.scope_tools_edit,p.scope_tools_subagents,p.scope_tools_mcp_is,p.scope_add_dirs_is))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'cost' AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'audit' AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'foreground' AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'org_inbox' AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'history_identity:' || (r.id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_identity:' || (r.id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_recipient:' || (r.id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
        UNION ALL
        SELECT 'agent' AS entity, r.id::text AS entity_id FROM new_rows r WHERE (r.id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent' AS entity, r.parent_id::text AS entity_id FROM new_rows r WHERE (r.parent_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent' AS entity, r.predecessor_id::text AS entity_id FROM new_rows r WHERE (r.predecessor_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent' AS entity, r.successor_id::text AS entity_id FROM new_rows r WHERE (r.successor_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'pile:' || (coalesce(r.parent_id, 0)::text || ':' || r.id::text)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'pile:' || (r.id::text || ':-')::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'chain:' || (r.parent_id)::text AS entity_id FROM new_rows r WHERE (r.parent_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.successor_id)::text AS entity_id FROM new_rows r WHERE (r.successor_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'references:' || (r.id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'refname:' || (r.name)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'subtree:' || (r.id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE p.id=r.id AND to_json(ROW(r.parent,r.parent_id,r.parent_misfit,r.state,r.state_misfit,r.tombstone,r.extra,r.scope_is,r.scope_permission_mode,r.scope_org_visibility,r.scope_effort,r.scope_model_version,r.scope_prefer_reserve,r.scope_account_fallback,r.scope_tools_is,r.scope_tools_bash,r.scope_tools_web,r.scope_tools_edit,r.scope_tools_subagents,r.scope_tools_mcp_is,r.scope_add_dirs_is))::text=to_json(ROW(p.parent,p.parent_id,p.parent_misfit,p.state,p.state_misfit,p.tombstone,p.extra,p.scope_is,p.scope_permission_mode,p.scope_org_visibility,p.scope_effort,p.scope_model_version,p.scope_prefer_reserve,p.scope_account_fallback,p.scope_tools_is,p.scope_tools_bash,p.scope_tools_web,p.scope_tools_edit,p.scope_tools_subagents,p.scope_tools_mcp_is,p.scope_add_dirs_is))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'cost' AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'audit' AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'foreground' AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'org_inbox' AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'history_identity:' || (r.id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_identity:' || (r.id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_recipient:' || (r.id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE p.id=r.id AND to_json(ROW(r.name,r.tombstone))::text=to_json(ROW(p.name,p.tombstone))::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent' AS entity, r.id::text AS entity_id FROM old_rows r WHERE r.id IS NOT NULL
        UNION ALL
        SELECT 'agent' AS entity, r.parent_id::text AS entity_id FROM old_rows r WHERE r.parent_id IS NOT NULL
        UNION ALL
        SELECT 'agent' AS entity, r.predecessor_id::text AS entity_id FROM old_rows r WHERE r.predecessor_id IS NOT NULL
        UNION ALL
        SELECT 'agent' AS entity, r.successor_id::text AS entity_id FROM old_rows r WHERE r.successor_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'pile:' || (coalesce(r.parent_id, 0)::text || ':' || r.id::text)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'pile:' || (r.id::text || ':-')::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'chain:' || (r.parent_id)::text AS entity_id FROM old_rows r WHERE r.parent_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.successor_id)::text AS entity_id FROM old_rows r WHERE r.successor_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'references:' || (r.id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'refname:' || (r.name)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'subtree:' || (r.id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'org' AS entity, 'cost' AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'org' AS entity, 'audit' AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'org' AS entity, 'foreground' AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'org' AS entity, 'org_inbox' AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'history_identity:' || (r.id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_identity:' || (r.id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_recipient:' || (r.id)::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.agents REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_agents();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.agents REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_agents();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.agents REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_agents();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.delivery_batches;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.delivery_batches;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.delivery_batches;

CREATE OR REPLACE FUNCTION orgtree.record_capture_delivery_batches() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent' AS entity, r.agent_id::text AS entity_id FROM new_rows r WHERE r.agent_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/pending:delivery:'||r.id||':'||generate_series(0,(CASE WHEN json_typeof(r.mail)='array' THEN json_array_length(r.mail) ELSE 0 END)-1) AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_pending_size:' || (r.agent_id||':'||r.id||':'||(CASE WHEN json_typeof(r.mail)='array' THEN json_array_length(r.mail) ELSE 0 END))::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent' AS entity, r.agent_id::text AS entity_id FROM old_rows r WHERE (r.agent_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/pending:delivery:'||r.id||':'||generate_series(0,(CASE WHEN json_typeof(r.mail)='array' THEN json_array_length(r.mail) ELSE 0 END)-1) AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_pending_size:' || (r.agent_id||':'||r.id||':'||(CASE WHEN json_typeof(r.mail)='array' THEN json_array_length(r.mail) ELSE 0 END))::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent' AS entity, r.agent_id::text AS entity_id FROM new_rows r WHERE (r.agent_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/pending:delivery:'||r.id||':'||generate_series(0,(CASE WHEN json_typeof(r.mail)='array' THEN json_array_length(r.mail) ELSE 0 END)-1) AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_pending_size:' || (r.agent_id||':'||r.id||':'||(CASE WHEN json_typeof(r.mail)='array' THEN json_array_length(r.mail) ELSE 0 END))::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent' AS entity, r.agent_id::text AS entity_id FROM old_rows r WHERE r.agent_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/pending:delivery:'||r.id||':'||generate_series(0,(CASE WHEN json_typeof(r.mail)='array' THEN json_array_length(r.mail) ELSE 0 END)-1) AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_pending_size:' || (r.agent_id||':'||r.id||':'||(CASE WHEN json_typeof(r.mail)='array' THEN json_array_length(r.mail) ELSE 0 END))::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.delivery_batches REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_delivery_batches();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.delivery_batches REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_delivery_batches();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.delivery_batches REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_delivery_batches();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.event_refs;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.event_refs;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.event_refs;

CREATE OR REPLACE FUNCTION orgtree.record_capture_event_refs() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'history_name:' || (r.ref)::text AS entity, 'event:'||r.event_id AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:history_name:' || (r.ref)::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'history_name:' || (r.ref)::text AS entity, 'event:'||r.event_id AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:history_name:' || (r.ref)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'history_name:' || (r.ref)::text AS entity, 'event:'||r.event_id AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:history_name:' || (r.ref)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'history_name:' || (r.ref)::text AS entity, 'event:'||r.event_id AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:history_name:' || (r.ref)::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.event_refs REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_event_refs();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.event_refs REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_event_refs();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.event_refs REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_event_refs();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.event_warnings;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.event_warnings;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.event_warnings;

CREATE OR REPLACE FUNCTION orgtree.record_capture_event_warnings() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'event:shared' AS entity, r.events_id::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'history_event:' || (r.events_id)::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'event:shared' AS entity, r.events_id::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'history_event:' || (r.events_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'event:shared' AS entity, r.events_id::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'history_event:' || (r.events_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'event:shared' AS entity, r.events_id::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'history_event:' || (r.events_id)::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.event_warnings REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_event_warnings();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.event_warnings REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_event_warnings();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.event_warnings REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_event_warnings();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.events;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.events;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.events;

CREATE OR REPLACE FUNCTION orgtree.record_capture_events() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'org' AS entity, 'events_count' AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'event:' || ('shared')::text AS entity, r.id::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:event:' || ('shared')::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'org' AS entity, 'events_count' AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'event:' || ('shared')::text AS entity, r.id::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:event:' || ('shared')::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'events_count' AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'event:' || ('shared')::text AS entity, r.id::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:event:' || ('shared')::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'org' AS entity, 'events_count' AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'event:' || ('shared')::text AS entity, r.id::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:event:' || ('shared')::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.events REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_events();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.events REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_events();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.events REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_events();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.mail;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.mail;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.mail;

CREATE OR REPLACE FUNCTION orgtree.record_capture_mail() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent' AS entity, r.agent_id::text AS entity_id FROM new_rows r WHERE r.agent_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/pending:mail:'||r.id AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent' AS entity, r.agent_id::text AS entity_id FROM old_rows r WHERE (r.agent_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/pending:mail:'||r.id AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent' AS entity, r.agent_id::text AS entity_id FROM new_rows r WHERE (r.agent_id IS NOT NULL) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/pending:mail:'||r.id AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent' AS entity, r.agent_id::text AS entity_id FROM old_rows r WHERE r.agent_id IS NOT NULL
        UNION ALL
        SELECT '~scope' AS entity, 'detail:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'lineage:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/pending:mail:'||r.id AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.mail REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.mail REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.mail REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.mail_log;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.mail_log;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.mail_log;

CREATE OR REPLACE FUNCTION orgtree.record_capture_mail_log() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/delivered:mail_log:'||r.id AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_recipient:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_sender:' || (r.win_from)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~mail_sent:'||r.win_from AS entity, 'mail_log:'||r.id AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/delivered:mail_log:'||r.id AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_recipient:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_sender:' || (r.win_from)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~mail_sent:'||r.win_from AS entity, 'mail_log:'||r.id AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/delivered:mail_log:'||r.id AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_recipient:' || (r.agent_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_sender:' || (r.win_from)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~mail_sent:'||r.win_from AS entity, 'mail_log:'||r.id AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'agent_mail:'||r.agent_id AS entity, r.agent_id||'/delivered:mail_log:'||r.id AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_owner:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_recipient:' || (r.agent_id)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_sender:' || (r.win_from)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~mail_sent:'||r.win_from AS entity, 'mail_log:'||r.id AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.mail_log REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail_log();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.mail_log REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail_log();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.mail_log REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail_log();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.mail_log_attachments;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.mail_log_attachments;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.mail_log_attachments;

CREATE OR REPLACE FUNCTION orgtree.record_capture_mail_log_attachments() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT '~scope' AS entity, 'mail_child:' || ('mail_log:'||r.mail_log_id)::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT '~scope' AS entity, 'mail_child:' || ('mail_log:'||r.mail_log_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('mail_log:'||r.mail_log_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT '~scope' AS entity, 'mail_child:' || ('mail_log:'||r.mail_log_id)::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.mail_log_attachments REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail_log_attachments();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.mail_log_attachments REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail_log_attachments();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.mail_log_attachments REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail_log_attachments();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.mail_log_attachments_missing;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.mail_log_attachments_missing;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.mail_log_attachments_missing;

CREATE OR REPLACE FUNCTION orgtree.record_capture_mail_log_attachments_missing() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT '~scope' AS entity, 'mail_child:' || ('mail_log:'||r.mail_log_id)::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT '~scope' AS entity, 'mail_child:' || ('mail_log:'||r.mail_log_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('mail_log:'||r.mail_log_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT '~scope' AS entity, 'mail_child:' || ('mail_log:'||r.mail_log_id)::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.mail_log_attachments_missing REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail_log_attachments_missing();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.mail_log_attachments_missing REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail_log_attachments_missing();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.mail_log_attachments_missing REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_mail_log_attachments_missing();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.notice_log;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.notice_log;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.notice_log;

CREATE OR REPLACE FUNCTION orgtree.record_capture_notice_log() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'history_name:' || (r.win_node)::text AS entity, 'notice:'||r.id AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:history_name:' || (r.win_node)::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'history_name:' || (r.win_node)::text AS entity, 'notice:'||r.id AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:history_name:' || (r.win_node)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'history_name:' || (r.win_node)::text AS entity, 'notice:'||r.id AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:history_name:' || (r.win_node)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'history_name:' || (r.win_node)::text AS entity, 'notice:'||r.id AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:history_name:' || (r.win_node)::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.notice_log REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_notice_log();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.notice_log REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_notice_log();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.notice_log REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_notice_log();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.user_inbox;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.user_inbox;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.user_inbox;

CREATE OR REPLACE FUNCTION orgtree.record_capture_user_inbox() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'org' AS entity, 'inbox_summary' AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'user_inbox' AS entity, r.id::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_sender:' || (coalesce(r."from",r.extra->>'from'))::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~mail_sent:'||(coalesce(r."from",r.extra->>'from')) AS entity, 'user_inbox:'||r.id AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'org' AS entity, 'inbox_summary' AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_inbox' AS entity, r.id::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_sender:' || (coalesce(r."from",r.extra->>'from'))::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~mail_sent:'||(coalesce(r."from",r.extra->>'from')) AS entity, 'user_inbox:'||r.id AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'inbox_summary' AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_inbox' AS entity, r.id::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_sender:' || (coalesce(r."from",r.extra->>'from'))::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~mail_sent:'||(coalesce(r."from",r.extra->>'from')) AS entity, 'user_inbox:'||r.id AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'org' AS entity, 'inbox_summary' AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'user_inbox' AS entity, r.id::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_sender:' || (coalesce(r."from",r.extra->>'from'))::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~mail_sent:'||(coalesce(r."from",r.extra->>'from')) AS entity, 'user_inbox:'||r.id AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.user_inbox REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_inbox();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.user_inbox REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_inbox();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.user_inbox REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_inbox();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.user_inbox_attachments;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.user_inbox_attachments;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.user_inbox_attachments;

CREATE OR REPLACE FUNCTION orgtree.record_capture_user_inbox_attachments() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'org' AS entity, 'inbox_summary' AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'user_inbox' AS entity, r.user_inbox_id::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('user_inbox:'||r.user_inbox_id)::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'org' AS entity, 'inbox_summary' AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_inbox' AS entity, r.user_inbox_id::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('user_inbox:'||r.user_inbox_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'org' AS entity, 'inbox_summary' AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_inbox' AS entity, r.user_inbox_id::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('user_inbox:'||r.user_inbox_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'org' AS entity, 'inbox_summary' AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'user_inbox' AS entity, r.user_inbox_id::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('user_inbox:'||r.user_inbox_id)::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.user_inbox_attachments REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_inbox_attachments();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.user_inbox_attachments REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_inbox_attachments();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.user_inbox_attachments REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_inbox_attachments();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.user_mail_log;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.user_mail_log;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.user_mail_log;

CREATE OR REPLACE FUNCTION orgtree.record_capture_user_mail_log() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT '~scope' AS entity, 'mail_sender:' || (r.win_from)::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~mail_sent:'||(r.win_from) AS entity, 'user_mail_log:'||r.id AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT 'user_mail_log:' || ('shared')::text AS entity, r.id::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:user_mail_log:' || ('shared')::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT '~scope' AS entity, 'mail_sender:' || (r.win_from)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~mail_sent:'||(r.win_from) AS entity, 'user_mail_log:'||r.id AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_mail_log:' || ('shared')::text AS entity, r.id::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:user_mail_log:' || ('shared')::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_sender:' || (r.win_from)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~mail_sent:'||(r.win_from) AS entity, 'user_mail_log:'||r.id AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_mail_log:' || ('shared')::text AS entity, r.id::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:user_mail_log:' || ('shared')::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT '~scope' AS entity, 'mail_sender:' || (r.win_from)::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~mail_sent:'||(r.win_from) AS entity, 'user_mail_log:'||r.id AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT 'user_mail_log:' || ('shared')::text AS entity, r.id::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:user_mail_log:' || ('shared')::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.user_mail_log REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_mail_log();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.user_mail_log REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_mail_log();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.user_mail_log REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_mail_log();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.user_mail_log_attachments;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.user_mail_log_attachments;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.user_mail_log_attachments;

CREATE OR REPLACE FUNCTION orgtree.record_capture_user_mail_log_attachments() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_mail_log:shared' AS entity, r.user_mail_log_id::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('user_mail_log:'||r.user_mail_log_id)::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_mail_log:shared' AS entity, r.user_mail_log_id::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('user_mail_log:'||r.user_mail_log_id)::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_mail_log:shared' AS entity, r.user_mail_log_id::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('user_mail_log:'||r.user_mail_log_id)::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_mail_log:shared' AS entity, r.user_mail_log_id::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'mail_child:' || ('user_mail_log:'||r.user_mail_log_id)::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.user_mail_log_attachments REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_mail_log_attachments();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.user_mail_log_attachments REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_mail_log_attachments();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.user_mail_log_attachments REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_mail_log_attachments();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.user_outbox;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.user_outbox;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.user_outbox;

CREATE OR REPLACE FUNCTION orgtree.record_capture_user_outbox() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_outbox:' || ('shared')::text AS entity, r.id::text AS entity_id FROM new_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:user_outbox:' || ('shared')::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_outbox:' || ('shared')::text AS entity, r.id::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:user_outbox:' || ('shared')::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_outbox:' || ('shared')::text AS entity, r.id::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT '~scope' AS entity, 'window:user_outbox:' || ('shared')::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_outbox:' || ('shared')::text AS entity, r.id::text AS entity_id FROM old_rows r WHERE true
        UNION ALL
        SELECT '~scope' AS entity, 'window:user_outbox:' || ('shared')::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  PERFORM set_config('orgtree.pending_scopes', '1', true);
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.user_outbox REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_outbox();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.user_outbox REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_outbox();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.user_outbox REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_outbox();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.user_outbox_attachments;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.user_outbox_attachments;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.user_outbox_attachments;

CREATE OR REPLACE FUNCTION orgtree.record_capture_user_outbox_attachments() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_outbox:shared' AS entity, r.user_outbox_id::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_outbox:shared' AS entity, r.user_outbox_id::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_outbox:shared' AS entity, r.user_outbox_id::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_outbox:shared' AS entity, r.user_outbox_id::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.user_outbox_attachments REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_outbox_attachments();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.user_outbox_attachments REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_outbox_attachments();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.user_outbox_attachments REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_outbox_attachments();

DROP TRIGGER IF EXISTS record_capture_insert ON orgtree.user_outbox_attachments_missing;

DROP TRIGGER IF EXISTS record_capture_update ON orgtree.user_outbox_attachments_missing;

DROP TRIGGER IF EXISTS record_capture_delete ON orgtree.user_outbox_attachments_missing;

CREATE OR REPLACE FUNCTION orgtree.record_capture_user_outbox_attachments_missing() RETURNS trigger
LANGUAGE plpgsql SET search_path=pg_catalog,orgtree AS $fn$
BEGIN
  IF current_setting('orgtree.capture', true) = 'off' THEN RETURN NULL; END IF;
  IF TG_OP = 'INSERT' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_outbox:shared' AS entity, r.user_outbox_id::text AS entity_id FROM new_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'UPDATE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_outbox:shared' AS entity, r.user_outbox_id::text AS entity_id FROM old_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM new_rows p WHERE to_json(r)::text=to_json(p)::text)
        UNION ALL
        SELECT 'user_outbox:shared' AS entity, r.user_outbox_id::text AS entity_id FROM new_rows r WHERE (true) AND NOT EXISTS (SELECT 1 FROM old_rows p WHERE to_json(r)::text=to_json(p)::text)
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO orgtree.changes (xid, entity, entity_id)
      SELECT DISTINCT pg_current_xact_id(), entity, entity_id FROM (
        SELECT 'user_outbox:shared' AS entity, r.user_outbox_id::text AS entity_id FROM old_rows r WHERE true
      ) named WHERE entity IS NOT NULL AND entity_id IS NOT NULL
      ON CONFLICT DO NOTHING;
  END IF;
  RETURN NULL;
END
$fn$;

CREATE TRIGGER record_capture_insert AFTER INSERT ON orgtree.user_outbox_attachments_missing REFERENCING NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_outbox_attachments_missing();

CREATE TRIGGER record_capture_update AFTER UPDATE ON orgtree.user_outbox_attachments_missing REFERENCING OLD TABLE AS old_rows NEW TABLE AS new_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_outbox_attachments_missing();

CREATE TRIGGER record_capture_delete AFTER DELETE ON orgtree.user_outbox_attachments_missing REFERENCING OLD TABLE AS old_rows FOR EACH STATEMENT EXECUTE FUNCTION orgtree.record_capture_user_outbox_attachments_missing();
