//! A pure, non-authoritative Rust model of the permission-scope clamps of
//! the Python ledger (`engine/backend/orgtree/ledger.py`): what a hire,
//! rehire, retool or kiosk ceiling lets an agent hold in tools, MCP servers,
//! folders, organization visibility and permission mode.
//!
//! Given explicit inputs (never an organization document) it returns what
//! the Python functions return: the clamped grant, the list of what was
//! lost, the warnings, or Python's exact refusal text. Path comparison is
//! the engine runtime's own: CPython 3.13's Windows `normpath` and a
//! `normcase` that lowercases through the Windows NLS table, captured by the
//! oracle into [`tables`].
//!
//! It mutates nothing it is given, spawns no process, reads no environment
//! and never touches a path on disk: paths are strings. It is not wired into
//! anything and makes no authority, transaction or runtime claim. See the
//! README for the parity domain and the exclusions.

pub mod clamp;
pub mod ntpath;
pub mod pystr;
// generated by the oracle and byte-checked by it: never reformatted
#[rustfmt::skip]
pub mod tables;
pub mod val;
pub mod vectors;

pub use clamp::{
    apply_ceiling, check_tier_ceiling, clamp_dirs, clamp_tools, clamp_vis, expand_mcp, norm_dirs,
    norm_tools, raise_ceiling_for, Ceiled, DirGrant, Fail, Rules, ToolGrant,
};
pub use ntpath::{normcase, normpath, PathRules};
pub use pystr::PyStr;
pub use val::{Outside, Val};
