//! Check the crate against the Python-generated parity vectors.
//!
//! Every function takes a [`Rules`], so the negative controls can change one
//! decision and show that the unchanged vectors detect it. A missing or empty
//! section is itself a failure, so a truncated vectors file cannot pass.

use crate::admission::{self, AdmitCall};
use crate::canonical::{canonical_with, py_float_repr, py_json_float};
use crate::eviction::plan_append_with;
use crate::eviction::AppendPlan;
use crate::fingerprint::fingerprint_with;
use crate::key::{parse_key_with, DECIMAL_ZEROS, PY_SPACE};
use crate::pyint::PyInt;
use crate::sha256::{hex, sha256_with};
use crate::{PyOutcome, Rules};
use orgtree_backend_codec::json::{self, JsonErrorKind, Limits, Object, Profile, Value};
use orgtree_backend_codec::presence::Presence;

pub const SCHEMA: &str = "orgtree.op-receipt-codec-vectors/v1";

/// The committed vectors, generated by `oracle/generate_vectors.py`.
pub const COMMITTED: &str = include_str!("../vectors/op-receipt-vectors.json");

/// Every section the runner requires.
pub const SECTIONS: [&str; 12] = [
    "tables",
    "key",
    "py_int",
    "fp_node",
    "float",
    "canonical",
    "sha256",
    "fingerprint",
    "find",
    "meta",
    "admission",
    "append",
];

/// Rows checked per section, and every mismatch with its section and index.
#[derive(Debug, Default)]
pub struct Report {
    pub checked: Vec<(String, usize)>,
    pub failures: Vec<String>,
}

impl Report {
    pub fn total(&self) -> usize {
        self.checked.iter().map(|(_, n)| n).sum()
    }

    pub fn failed_sections(&self) -> Vec<&str> {
        let mut s: Vec<&str> = self
            .failures
            .iter()
            .map(|f| f.split(['[', ':']).next().unwrap_or(""))
            .collect();
        s.sort_unstable();
        s.dedup();
        s
    }
}

const INPUT_LIMITS: Limits = Limits {
    max_bytes: 1 << 20,
    max_depth: 64,
};

fn field<'a>(o: &'a Object, k: &str) -> Option<&'a Value> {
    match o.get(k) {
        Presence::Present(v) => Some(v),
        _ => None,
    }
}

fn text<'a>(o: &'a Object, k: &str) -> Option<&'a str> {
    match field(o, k) {
        Some(Value::String(s)) => Some(s),
        _ => None,
    }
}

fn int(v: Option<&Value>) -> Option<i64> {
    match v {
        Some(Value::Number(n)) => n.to_i64(),
        _ => None,
    }
}

/// An exact expected integer: a JSON integer, or a decimal string for one
/// longer than the 4300 digits a JSON integer may have.
fn big(v: Option<&Value>) -> Option<PyInt> {
    match v {
        Some(Value::Number(n)) if n.is_integer_lexeme() => PyInt::parse_decimal(n.lexeme()),
        Some(Value::String(s)) => PyInt::parse_decimal(s),
        _ => None,
    }
}

fn opt_big_eq(want: Option<&Value>, got: Option<&PyInt>) -> bool {
    match (want, got) {
        (None | Some(Value::Null), None) => true,
        (Some(w), Some(g)) => big(Some(w)).as_ref() == Some(g),
        _ => false,
    }
}

fn boolean(o: &Object, k: &str) -> Option<bool> {
    match field(o, k) {
        Some(Value::Bool(b)) => Some(*b),
        _ => None,
    }
}

fn as_obj(v: &Value) -> Option<&Object> {
    match v {
        Value::Object(o) => Some(o),
        _ => None,
    }
}

fn parse_input(s: &str) -> Result<Value, JsonErrorKind> {
    json::parse(s, Profile::PythonLegacy, INPUT_LIMITS).map_err(|e| e.kind)
}

fn parse_object(s: &str) -> Result<Object, String> {
    match parse_input(s) {
        Ok(Value::Object(o)) => Ok(o),
        Ok(_) => Err("input is not an object".to_owned()),
        Err(k) => Err(format!("input does not parse: {}", k.as_str())),
    }
}

/// Compare a Python outcome row (`value`, `raises` or `outside`) with ours.
fn outcome<T: std::fmt::Debug>(
    row: &Object,
    got: &PyOutcome<T>,
    same: impl Fn(&Value, &T) -> bool,
) -> Result<(), String> {
    let ok = match got {
        PyOutcome::Value(v) => field(row, "value").is_some_and(|want| same(want, v)),
        PyOutcome::Raises(e) => text(row, "raises") == Some(e.as_str()),
        PyOutcome::OutsideParityDomain(_) => boolean(row, "outside") == Some(true),
    };
    if ok {
        Ok(())
    } else {
        Err(format!("got {got:?}"))
    }
}

fn opt_int_eq(want: Option<&Value>, got: Option<i64>) -> bool {
    match (want, got) {
        (None | Some(Value::Null), None) => true,
        (Some(w), Some(g)) => int(Some(w)) == Some(g),
        _ => false,
    }
}

fn opt_str_eq(want: Option<&Value>, got: Option<&str>) -> bool {
    match (want, got) {
        (None | Some(Value::Null), None) => true,
        (Some(Value::String(w)), Some(g)) => w == g,
        _ => false,
    }
}

fn check_tables(row: &Object, _: &Rules) -> Result<(), String> {
    let want: Vec<i64> = match field(row, "values") {
        Some(Value::Array(a)) => a.iter().filter_map(|v| int(Some(v))).collect(),
        _ => return Err("no values".to_owned()),
    };
    let got: Vec<i64> = match text(row, "name") {
        Some("decimal_zeros") => DECIMAL_ZEROS.iter().map(|&c| i64::from(c)).collect(),
        Some("space") => PY_SPACE.iter().map(|&c| i64::from(c)).collect(),
        other => return Err(format!("unknown table {other:?}")),
    };
    if want == got {
        Ok(())
    } else {
        Err("table differs from Python".to_owned())
    }
}

fn check_key(row: &Object, rules: &Rules) -> Result<(), String> {
    let got = parse_key_with(text(row, "key").ok_or("no key")?, rules);
    if opt_int_eq(field(row, "mint"), got) {
        Ok(())
    } else {
        Err(format!("got {got:?}"))
    }
}

fn check_py_int(row: &Object, rules: &Rules) -> Result<(), String> {
    let doc = match text(row, "json") {
        Some(j) => format!(r#"{{"op_receipts_meta":{{"from_ms":{j}}}}}"#),
        None => r#"{"op_receipts_meta":{}}"#.to_owned(),
    };
    let doc = parse_object(&doc)?;
    outcome(row, &admission::watermark_with(&doc, rules), |w, g| {
        big(Some(w)).as_ref() == Some(g)
    })
}

fn check_fp_node(row: &Object, _: &Rules) -> Result<(), String> {
    let r = parse_object(text(row, "row_json").ok_or("no row_json")?)?;
    outcome(
        row,
        &admission::fp_node(&r),
        |w, g| matches!(w, Value::String(s) if s == g),
    )
}

fn check_float(row: &Object, rules: &Rules) -> Result<(), String> {
    let b =
        u64::from_str_radix(text(row, "bits").ok_or("no bits")?, 16).map_err(|e| e.to_string())?;
    let x = f64::from_bits(b);
    let repr = if rules.python_float_repr {
        py_float_repr(x)
    } else {
        format!("{x}")
    };
    let js = py_json_float(x, rules);
    if Some(repr.as_str()) == text(row, "repr") && Some(js.as_str()) == text(row, "json") {
        Ok(())
    } else {
        Err(format!("got repr {repr} json {js}"))
    }
}

/// The input of a row that Python cannot encode must be one this crate
/// refuses at the JSON reader; any other input must parse.
fn parse_args(row: &Object, outside_marks_input: bool) -> Result<Option<Value>, String> {
    let src = text(row, "args_json").ok_or("no args_json")?;
    match (
        parse_input(src),
        outside_marks_input && boolean(row, "outside") == Some(true),
    ) {
        (Err(JsonErrorKind::LoneSurrogate), true) => Ok(None),
        (Ok(v), false) => Ok(Some(v)),
        (r, outside) => Err(format!(
            "args parse {:?} but outside={outside}",
            r.map(|_| ())
        )),
    }
}

fn check_canonical(row: &Object, rules: &Rules) -> Result<(), String> {
    let Some(v) = parse_args(row, true)? else {
        return Ok(());
    };
    let got = canonical_with(&v, rules);
    if Some(got.as_str()) == text(row, "canonical") {
        Ok(())
    } else {
        Err(format!("got {got}"))
    }
}

fn unhex(s: &str) -> Result<Vec<u8>, String> {
    (0..s.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&s[i..i + 2], 16).map_err(|e| e.to_string()))
        .collect()
}

fn check_sha256(row: &Object, rules: &Rules) -> Result<(), String> {
    let data = unhex(text(row, "hex").ok_or("no hex")?)?;
    let repeat = usize::try_from(int(field(row, "repeat")).ok_or("no repeat")?)
        .map_err(|e| e.to_string())?;
    let got = hex(&sha256_with(&data.repeat(repeat), rules.sha256_k));
    if Some(got.as_str()) == text(row, "digest") {
        Ok(())
    } else {
        Err(format!("got {got}"))
    }
}

fn check_fingerprint(row: &Object, rules: &Rules) -> Result<(), String> {
    let Some(args) = parse_args(row, true)? else {
        return Ok(());
    };
    let generation = big(field(row, "generation")).ok_or("no generation")?;
    let got = fingerprint_with(
        text(row, "tool").ok_or("no tool")?,
        text(row, "node").ok_or("no node")?,
        &generation,
        &args,
        rules,
    );
    outcome(row, &got, |w, g| matches!(w, Value::String(s) if s == g))
}

fn check_find(row: &Object, rules: &Rules) -> Result<(), String> {
    let doc = parse_object(text(row, "doc_json").ok_or("no doc_json")?)?;
    let Some(args) = parse_args(row, false)? else {
        return Err("find rows always have arguments".to_owned());
    };
    let (node, key, tool) = (
        text(row, "node").ok_or("no node")?,
        text(row, "key").ok_or("no key")?,
        text(row, "tool").ok_or("no tool")?,
    );
    let got = match admission::find_with(&doc, node, key, rules) {
        PyOutcome::Value(i) => {
            let rows = match admission::receipt_rows(&doc) {
                PyOutcome::Value(r) => r,
                _ => return Err("rows unreadable".to_owned()),
            };
            match admission::classify_with(i.map(|i| rows[i]), tool, &args, node, rules) {
                PyOutcome::Value(s) => PyOutcome::Value((i, s)),
                PyOutcome::Raises(e) => PyOutcome::Raises(e),
                PyOutcome::OutsideParityDomain(r) => PyOutcome::OutsideParityDomain(r),
            }
        }
        PyOutcome::Raises(e) => PyOutcome::Raises(e),
        PyOutcome::OutsideParityDomain(r) => PyOutcome::OutsideParityDomain(r),
    };
    outcome(row, &got, |w, (i, s)| {
        as_obj(w).is_some_and(|w| {
            let idx = i.map(|i| i as i64);
            opt_int_eq(field(w, "find"), idx) && opt_str_eq(field(w, "state"), Some(s.as_str()))
        })
    })
}

fn check_meta(row: &Object, rules: &Rules) -> Result<(), String> {
    let doc = match text(row, "meta_json") {
        Some(m) => format!(r#"{{"slug":"oracle","op_receipts_meta":{m}}}"#),
        None => r#"{"slug":"oracle"}"#.to_owned(),
    };
    let doc = parse_object(&doc)?;
    let want_ahead = field(row, "schema_ahead")
        .and_then(as_obj)
        .ok_or("no schema_ahead")?;
    let want_wm = field(row, "watermark")
        .and_then(as_obj)
        .ok_or("no watermark")?;
    outcome(
        want_ahead,
        &admission::schema_ahead_with(&doc, rules),
        |w, g| matches!(w, Value::Bool(b) if b == g),
    )
    .map_err(|e| format!("schema_ahead {e}"))?;
    outcome(want_wm, &admission::watermark_with(&doc, rules), |w, g| {
        big(Some(w)).as_ref() == Some(g)
    })
    .map_err(|e| format!("watermark {e}"))
}

fn check_admission(row: &Object, rules: &Rules) -> Result<(), String> {
    let doc = parse_object(text(row, "doc_json").ok_or("no doc_json")?)?;
    let Some(args) = parse_args(row, false)? else {
        return Err("admission rows always have arguments".to_owned());
    };
    let call = AdmitCall {
        node: text(row, "node").ok_or("no node")?,
        generation: big(field(row, "generation")).ok_or("no generation")?,
        key: text(row, "key").ok_or("no key")?,
        tool: text(row, "tool").ok_or("no tool")?,
        args: &args,
        now_ms: big(field(row, "now_ms")).ok_or("no now_ms")?,
        epoch_ok: boolean(row, "epoch_ok").ok_or("no epoch_ok")?,
    };
    let got = admission::admit_with(&doc, &call, rules);
    outcome(row, &got, |w, a| {
        as_obj(w).is_some_and(|w| {
            opt_str_eq(field(w, "decision"), Some(a.decision.as_str()))
                && opt_str_eq(field(w, "reason"), a.reason)
                && opt_int_eq(field(w, "row"), a.row.map(|i| i as i64))
                && opt_str_eq(field(w, "row_state"), a.row_state.map(|s| s.as_str()))
                && opt_int_eq(field(w, "mint_ms"), a.mint_ms)
        })
    })
}

fn append_doc(row: &Object) -> Result<Object, String> {
    let spec = field(row, "log").and_then(as_obj).ok_or("no log")?;
    let n = int(field(spec, "n")).ok_or("no n")?;
    let base = int(field(spec, "base")).ok_or("no base")?;
    let step = int(field(spec, "step")).ok_or("no step")?;
    let mut rows: Vec<String> = (0..n)
        .map(|i| format!(r#"{{"mint_ms":{}}}"#, base + i * step))
        .collect();
    if let Some(Value::Array(overrides)) = field(spec, "overrides") {
        for o in overrides.iter().filter_map(as_obj) {
            let i =
                usize::try_from(int(field(o, "i")).ok_or("no i")?).map_err(|e| e.to_string())?;
            rows[i] = match (boolean(o, "absent"), text(o, "json")) {
                (Some(true), _) => "{}".to_owned(),
                (_, Some(j)) => format!(r#"{{"mint_ms":{j}}}"#),
                _ => return Err("bad override".to_owned()),
            };
        }
    }
    let mut doc = String::from(r#"{"slug":"oracle""#);
    match text(row, "section") {
        Some("list") => doc.push_str(&format!(r#","op_receipts":[{}]"#, rows.join(","))),
        Some("null") => doc.push_str(r#","op_receipts":null"#),
        Some("absent") => {}
        other => return Err(format!("unknown section {other:?}")),
    }
    if let Some(m) = text(row, "meta_json") {
        doc.push_str(&format!(r#","op_receipts_meta":{m}"#));
    }
    doc.push('}');
    parse_object(&doc)
}

fn check_append(row: &Object, rules: &Rules) -> Result<(), String> {
    let doc = append_doc(row)?;
    outcome(row, &plan_append_with(&doc, rules), |w, p: &AppendPlan| {
        as_obj(w).is_some_and(|w| {
            matches!(field(w, "created_meta"), Some(Value::Bool(b)) if *b == p.created_meta)
                && big(field(w, "seq")).as_ref() == Some(&p.seq)
                && int(field(w, "len")) == Some(p.len_after as i64)
                && int(field(w, "cut")) == Some(p.cut as i64)
                && big(field(w, "watermark")).as_ref() == Some(&p.watermark_after)
                && opt_big_eq(field(w, "evicted"), p.evicted_total.as_ref())
        })
    })
}

type Check = fn(&Object, &Rules) -> Result<(), String>;

fn checker(section: &str) -> Check {
    match section {
        "tables" => check_tables,
        "key" => check_key,
        "py_int" => check_py_int,
        "fp_node" => check_fp_node,
        "float" => check_float,
        "canonical" => check_canonical,
        "sha256" => check_sha256,
        "fingerprint" => check_fingerprint,
        "find" => check_find,
        "meta" => check_meta,
        "admission" => check_admission,
        _ => check_append,
    }
}

/// Run every section of a vectors document under `rules`.
pub fn run(vectors: &str, rules: &Rules) -> Report {
    let mut report = Report::default();
    let limits = Limits {
        max_bytes: 1 << 24,
        max_depth: 64,
    };
    let doc = match json::parse(vectors, Profile::Strict, limits) {
        Ok(Value::Object(o)) => o,
        other => {
            report.failures.push(format!(
                "document: not a vectors object ({:?})",
                other.map(|_| ())
            ));
            return report;
        }
    };
    if text(&doc, "schema") != Some(SCHEMA) {
        report.failures.push("document: wrong schema".to_owned());
    }
    for section in SECTIONS {
        let rows = match field(&doc, section) {
            Some(Value::Array(rows)) if !rows.is_empty() => rows,
            _ => {
                report
                    .failures
                    .push(format!("{section}: missing or empty section"));
                continue;
            }
        };
        let check = checker(section);
        for (i, row) in rows.iter().enumerate() {
            let result = match as_obj(row) {
                Some(o) => check(o, rules),
                None => Err("row is not an object".to_owned()),
            };
            if let Err(e) = result {
                report.failures.push(format!("{section}[{i}]: {e}"));
            }
        }
        report.checked.push((section.to_owned(), rows.len()));
    }
    report
}
