-- The app database (design §2.10, §3.1): only what cannot live in an org's
-- own database. This file: the org registry with its lifecycle claims, the
-- engine instances that own claims and leases, the machine-level settings
-- (including the one-time conversion marker), and the machine-wide turn
-- queue. The machine-wide accounts follow in their own file.
--
-- Every table lives in schema orgtree (Q7 as ruled, f14). Runtime grants are
-- applied by orgdb.lifecycle after each migration run, not here, so the
-- runtime role's name is the install's, not a constant in a migration.

CREATE TABLE orgtree.engine_instances (
  id            bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  host          text NOT NULL,
  pid           integer NOT NULL,
  started_at    timestamptz NOT NULL DEFAULT now(),
  heartbeat_at  timestamptz NOT NULL DEFAULT now()
);

-- org_id is drawn first (nextval) so the row can be inserted with its final
-- database name, which is derived from it
CREATE TABLE orgtree.orgs (
  org_id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug              text NOT NULL CHECK (slug <> ''),
  org_uuid          uuid NOT NULL UNIQUE,
  database          text NOT NULL UNIQUE,
  state             text NOT NULL CHECK (state IN ('provisioning', 'converting', 'active',
                      'closing', 'unavailable', 'trashed', 'purging')),
  unavailable_step  text CHECK (unavailable_step IN ('import', 'conversion', 'migration', 'identity')),
  state_reason      text,
  report_path       text,
  attempts          integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  attempted_build   text,
  state_at          timestamptz NOT NULL DEFAULT now(),
  created_at        timestamptz NOT NULL DEFAULT now(),
  trashed_at        timestamptz,
  -- where a converted org came from (§5.2 rule 3): the legacy database and
  -- its org_id, or the 2.1.14 file the first-launch import held back
  legacy_database   text,
  legacy_org_id     bigint,
  legacy_file       text,
  -- one lifecycle operation at a time per org (§2.13 rule 1)
  op_kind           text CHECK (op_kind IN ('create', 'convert', 'retry', 'trash', 'restore',
                      'purge', 'export', 'import')),
  op_epoch          bigint NOT NULL DEFAULT 0,
  op_owner          bigint REFERENCES orgtree.engine_instances(id) ON DELETE SET NULL,
  op_step           text,
  op_target_db      text,
  op_started_at     timestamptz,
  row_version       bigint NOT NULL DEFAULT 0,
  CONSTRAINT orgs_unavailable_step CHECK ((state = 'unavailable') = (unavailable_step IS NOT NULL)),
  CONSTRAINT orgs_claim_complete CHECK ((op_kind IS NULL) = (op_step IS NULL)),
  CONSTRAINT orgs_trashed_at CHECK (state NOT IN ('trashed', 'purging') OR trashed_at IS NOT NULL)
);

-- a trashed org's name can be reused, as today; a restore picks a free one
CREATE UNIQUE INDEX orgs_slug_in_use ON orgtree.orgs (slug) WHERE state <> 'trashed';
CREATE INDEX orgs_claimed ON orgtree.orgs (op_owner) WHERE op_kind IS NOT NULL;

-- every change to the registry is announced (§3.1): '<org_id>:<state>'
CREATE FUNCTION orgtree.orgs_notify() RETURNS trigger
LANGUAGE plpgsql AS $fn$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM pg_notify('app_orgs', OLD.org_id::text || ':deleted');
    RETURN OLD;
  END IF;
  PERFORM pg_notify('app_orgs', NEW.org_id::text || ':' || NEW.state);
  RETURN NEW;
END
$fn$;

CREATE TRIGGER orgs_notify AFTER INSERT OR UPDATE OR DELETE ON orgtree.orgs
  FOR EACH ROW EXECUTE FUNCTION orgtree.orgs_notify();

-- one row of machine-level facts (§2.10). legacy_cutover_at set = the
-- converter's one first pass has finished (§5.2); the other legacy_cutover_*
-- columns record what it read and where its report is
CREATE TABLE orgtree.app_settings (
  singleton                  boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  accounts_version           integer,
  apikey_cutover_at          timestamptz,
  apikey_cutover_at_text     text,
  legacy_cutover_at          timestamptz,
  legacy_cutover_database    text,
  legacy_cutover_level       text,
  legacy_cutover_build       text,
  legacy_cutover_report      text,
  row_version                bigint NOT NULL DEFAULT 0
);
INSERT INTO orgtree.app_settings DEFAULT VALUES;

-- the machine-wide fair queue (§2.4, rev 5 f2)
CREATE TABLE orgtree.turn_tickets (
  id           bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  request_id   text NOT NULL UNIQUE,
  org_id       bigint NOT NULL REFERENCES orgtree.orgs(org_id) ON DELETE CASCADE,
  agent_id     bigint NOT NULL,
  agent_name   text NOT NULL,
  lane         text NOT NULL,
  enqueued_at  timestamptz NOT NULL DEFAULT now(),
  state        text NOT NULL CHECK (state IN ('waiting', 'running', 'stopping', 'done', 'cancelled', 'lost')),
  claim_epoch  bigint NOT NULL DEFAULT 0,
  lease_owner  bigint REFERENCES orgtree.engine_instances(id) ON DELETE SET NULL,
  started_at   timestamptz,
  ended_at     timestamptz
);
CREATE UNIQUE INDEX turn_tickets_one_open ON orgtree.turn_tickets (org_id, agent_id)
  WHERE state IN ('waiting', 'running', 'stopping');
CREATE INDEX turn_tickets_waiting ON orgtree.turn_tickets (org_id, enqueued_at)
  WHERE state = 'waiting';
CREATE INDEX turn_tickets_leased ON orgtree.turn_tickets (lease_owner)
  WHERE state IN ('running', 'stopping');

CREATE TABLE orgtree.turn_admission (
  singleton    boolean PRIMARY KEY DEFAULT true CHECK (singleton),
  slot_limit   integer NOT NULL DEFAULT 16 CHECK (slot_limit > 0),
  last_org_id  bigint
);
INSERT INTO orgtree.turn_admission DEFAULT VALUES;
