"""Generate the scope-clamp parity vectors from the real Python ledger.

Every expected value comes from calling the current `orgtree.ledger`
functions (`norm_tools`, `norm_dirs`, `expand_mcp`, `Org._clamp_tools`,
`Org._clamp_dirs`, `Org._clamp_vis`, `Org._apply_ceiling` with and without
`raise_ceiling`, `Org._check_tier_ceiling`) and the runtime's own
`ntpath.normpath` / `ntpath.normcase`, on synthetic inputs. Nothing here
reimplements a clamp.

It also writes `src/tables.rs`: the host's Windows NLS invariant lowercase
table exactly as `ntpath.normcase` applies it (CPython 3.13 on Windows calls
`LCMapStringEx(LOCALE_NAME_INVARIANT, LCMAP_LOWERCASE)`, not `str.lower()`),
the set of code points `str.isprintable()` rejects (for `repr()` in refusal
texts), `str.isspace()`, and the static tier table. The table is stamped
with the Windows build and its own sha256: on a host whose NLS data differs,
`--check` fails instead of drifting.

Run on the engine runtime only (CPython 3.13.15, Windows):

    engine/runtime/python.exe engine/native/scope-clamp/oracle/generate_vectors.py --check
    engine/runtime/python.exe engine/native/scope-clamp/oracle/generate_vectors.py --write

It writes nothing outside the vectors file, src/tables.rs and a temporary
ORGTREE_DATA.
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import ntpath
import os
import random
import sys
import tempfile
from pathlib import Path
from typing import Any

SCHEMA = "orgtree.scope-clamp-vectors/v1"
REQUIRED_PYTHON = (3, 13)
CRATE = Path(__file__).resolve().parents[1]
DEFAULT_VECTORS = CRATE / "vectors" / "scope-clamp-vectors.json"
TABLES = CRATE / "src" / "tables.rs"
ANCHORED = ["engine/backend/orgtree/ledger.py"]
PYSTR = "\x00str"
BS = chr(92)
MAXCP = 0x110000

KNOWN_PREFIXES = (
    "cannot grant dirs ",
    "org_visibility ",
    "the kiosk ceiling caps agent tier at ",
)
KNOWN_INFIXES = (
    " does not hold ",
    " read-only; cannot grant read/write",
)


def check_known(msg: str) -> None:
    if msg.startswith(KNOWN_PREFIXES) or any(s in msg for s in KNOWN_INFIXES):
        return
    raise SystemExit(f"oracle stopped: unknown LedgerError pattern: {msg!r}")


# ---------------------------------------------------------------- encoding
def is_text(s: str) -> bool:
    return not any(0xD800 <= ord(c) < 0xE000 for c in s)


def enc(v: Any) -> Any:
    """A Python value as vector JSON: a str holding a lone surrogate becomes
    {"\\u0000str": [code points]}; dict keys must be text."""
    if isinstance(v, str):
        return v if is_text(v) else {PYSTR: [ord(c) for c in v]}
    if isinstance(v, bool) or v is None or isinstance(v, (int, float)):
        return v
    if isinstance(v, (list, tuple)):
        return [enc(x) for x in v]
    if isinstance(v, dict):
        for k in v:
            if not isinstance(k, str) or not is_text(k) or k == PYSTR:
                raise SystemExit(f"oracle stopped: dict key not encodable: {k!r}")
        return {k: enc(x) for k, x in v.items()}
    raise SystemExit(f"oracle stopped: value not encodable: {v!r}")


def run(call) -> dict:
    try:
        return {"ok": call()}
    except Exception as e:  # noqa: BLE001
        name = type(e).__name__
        if name == "LedgerError":
            check_known(str(e))
            return {"refused": enc(str(e))}
        return {"raises": name}


# ---------------------------------------------------------------- tables
def capture_tables(ledger) -> tuple[str, dict, list]:
    lower = []
    for c in range(MAXCP):
        if 0xD800 <= c < 0xE000:
            continue
        s = chr(c)
        a = ntpath.normcase(s)
        if a != s.replace("/", BS):
            if len(a) != 1:
                raise SystemExit(f"oracle stopped: normcase of U+{c:04X} is not 1:1")
            lower.append((c, ord(a)))
    nonprint, start = [], None
    for c in range(MAXCP + 1):
        bad = c < MAXCP and not chr(c).isprintable()
        if bad and start is None:
            start = c
        elif not bad and start is not None:
            nonprint.append((start, c - 1))
            start = None
    space = [c for c in range(MAXCP) if chr(c).isspace()]
    tiers = sorted(ledger.TIERS.items())
    blob = json.dumps({"lower": lower, "nonprint": nonprint, "space": space,
                       "tiers": tiers}, separators=(",", ":")).encode()
    stamp = {
        "windows": ".".join(map(str, sys.getwindowsversion()[:3])),
        "python": ".".join(map(str, sys.version_info[:3])),
        "normcase": "_winapi.LCMapStringEx(LOCALE_NAME_INVARIANT, LCMAP_LOWERCASE)",
        "sha256": hashlib.sha256(blob).hexdigest(),
        "lower": len(lower), "nonprintable_ranges": len(nonprint),
    }
    out = ["// @generated by oracle/generate_vectors.py --write. Do not edit.",
           "//!",
           "//! Case, printability and whitespace data of the engine runtime,",
           "//! captured by calling it. `NLS_LOWER` is what `ntpath.normcase`",
           "//! does to each code point (Windows NLS invariant lowercase via",
           "//! LCMapStringEx), NOT `str.lower()`.",
           "",
           f"pub const WINDOWS_BUILD: &str = {json.dumps(stamp['windows'])};",
           f"pub const PYTHON: &str = {json.dumps(stamp['python'])};",
           f"pub const TABLES_SHA256: &str = {json.dumps(stamp['sha256'])};",
           "",
           "/// (code point, lowercase) pairs, sorted; any other code point maps to itself.",
           "pub static NLS_LOWER: &[(u32, u32)] = &["]
    out += [f"    (0x{a:04x}, 0x{b:04x})," for a, b in lower]
    out += ["];", "",
            "/// Inclusive ranges of code points `str.isprintable()` rejects, sorted.",
            "pub static NONPRINTABLE: &[(u32, u32)] = &["]
    out += [f"    (0x{a:04x}, 0x{b:04x})," for a, b in nonprint]
    out += ["];", "",
            "/// `str.isspace()`, sorted.",
            f"pub static PY_WHITESPACE: [u32; {len(space)}] = ["]
    out += [f"    0x{c:04x}," for c in space]
    out += ["];", "",
            "/// `ledger.TIERS`: the static seat of each built-in tier.",
            "pub static TIERS: &[(&str, f64)] = &["]
    out += [f"    ({json.dumps(k)}, {float(v)!r})," for k, v in tiers]
    out += ["];", ""]
    return "\n".join(out), stamp, lower


# ---------------------------------------------------------------- string pools
def char_pool(lower: list[tuple[int, int]]) -> list[str]:
    diff = [0x130, 0x131, 0x1C5, 0x1C8, 0x1F2, 0x3A3, 0x3C2, 0x3F4, 0x1E9E, 0xDF, 0x212A,
            0x212B, 0x2126, 0x10400, 0x10428, 0x16E40, 0x1E900, 0xFF21, 0xFF41, 0x0130,
            0x0345, 0x0307, 0x0399, 0x03B9, 0x1FBE, 0x24B6, 0x2C00, 0xA7C0]
    pool = [chr(c) for c in diff] + [chr(a) for a, _ in lower[::7]] + [chr(b) for _, b in lower[::11]]
    pool += ["\ud800", "\udc00", "\udbff", "\udfff", "\ud801", "\x00", "\x7f", "\x85", "\xa0",
             "\u200b", "\u3000", "\t", "\n", " ", "'", '"', BS]
    return pool


def rand_path(rng: random.Random, pool: list[str]) -> str:
    parts = []
    r = rng.random()
    if r < 0.3:
        parts.append(rng.choice(["C:", "c:", "D:", "z:", "\u00e9:", "1:"]) + rng.choice([BS, "/", ""]))
    elif r < 0.45:
        parts.append(rng.choice([BS + BS, "//", BS + "/"]) + rng.choice(["srv", "SRV", "?", ".", "\u0130"]) +
                     rng.choice([BS, "/"]) + rng.choice(["share", "Sh", "UNC", "c:", ""]))
    elif r < 0.5:
        parts.append(rng.choice([BS + BS + "?" + BS + "UNC" + BS, "//?/unc/", BS + BS + "?" + BS + "C:", BS + BS + "." + BS]))
    elif r < 0.6:
        parts.append(rng.choice([BS, "/"]))
    for _ in range(rng.randint(0, 5)):
        k = rng.random()
        if k < 0.2:
            seg = rng.choice([".", "..", "...", ". ", " ..", ""])
        elif k < 0.6:
            seg = "".join(rng.choice(pool) for _ in range(rng.randint(1, 4)))
        else:
            seg = "".join(rng.choice("abcXYZ09_-") for _ in range(rng.randint(1, 5)))
        parts.append(seg + rng.choice([BS, "/", BS + BS, "", "/" + BS]))
    return "".join(parts)


# ---------------------------------------------------------------- sections
def section_paths(rng: random.Random, pool: list[str]) -> tuple[list, list, list, list]:
    hand = ["", ".", "..", "./", ".//a", "./..", "a/./b", "a/../..", "../a/../..", "C:", "C:" + BS,
            "C:/", "C:a", "C:..", "C:" + BS + "..", "C:" + BS + ".." + BS + "a", "C:a/../..",
            BS + BS + "srv" + BS + "sh", BS + BS + "srv" + BS + "sh" + BS, BS + BS + "srv" + BS + "sh" + BS + "..",
            BS + BS + "srv", BS + BS, "//", "///", "/" + BS + "x", BS + BS + "?" + BS + "C:" + BS + "a" + BS + "..",
            "//?/UNC/srv/sh/a/..", "//?/unc/srv", BS + BS + "." + BS + "C:" + BS + "a", "a:b", "\x00/..",
            " . " + BS + " .. ", "a" + BS + "..", "a" + BS + ".." + BS + "..", "..." + BS + "a", "a/.../b",
            "C:" + BS + "a" + BS + "b" + BS + BS, "\ud800\udc00", "\ud801\udc00/A", "\udc00\ud800", "A\ud800",
            "C:" + BS + "\u0130\u03a3\u1e9e", "C:/\u212a" + BS + "\u212b", "\U00010400/..", "c:" + BS + "Users" + BS + "N\u00e9",
            # repeated leading "." / ".\" after a drive are all skipped
            "C:././x", "C:." + BS + "." + BS + ".." + BS + "x", "C:.", "D:./.", "C:.//.//", "./././a", "z:." + BS + BS + "." + BS]
    paths = hand + [rand_path(rng, pool) for _ in range(3000)]
    normp = [[enc(p), enc(ntpath.normpath(p))] for p in paths]
    normc = [[enc(p), enc(ntpath.normcase(p))] for p in paths]
    reprs = []
    strips = []
    for _ in range(600):
        s = "".join(rng.choice(pool + [chr(rng.randrange(MAXCP))]) for _ in range(rng.randint(0, 6)))
        reprs.append([enc(s), enc(repr(s))])
        strips.append([enc(s), enc(s.strip())])
    for s in ["", "'", '"', "'\"", "a'b", "\x7f\x80\x9f\xa0\xad", "\u0378\ue000\U000e0001\U0010ffff", "\ud800", BS]:
        reprs.append([enc(s), enc(repr(s))])
    return normp, normc, reprs, strips


def section_norm(ledger, rng: random.Random, pool: list[str]) -> tuple[list, list, list]:
    tools_in: list[Any] = [None, {}, {"bash": False}, {"bash": 0, "web": "", "edit": [], "subagents": None},
                           {"bash": 1, "web": "x", "edit": [0], "subagents": {"a": 1}}, {"mcp": ["b", "a", "b", "", None, 0]},
                           {"mcp": ["x", "*"]}, {"mcp": "ab*"}, {"mcp": {"k": 1, "j": 2}}, {"mcp": [1, True, "1"]},
                           {"mcp": []}, {"mcp": None}, {"mcp": 5}, [], "", 0, {"mcp": ["\u0130", "i", "I", "\ud800"]},
                           {"mcp": [1.5]}, {"mcp": [["x"]]},
                           {"mcp": [1e16, 1e-5, 1e-4, 0.1, 123.0, -0.0, 1e300, 2.5e-7, 12345678901234567.0, 9999999999999998.0,
                                    [1, "a", None, True, {"k": 0.5, "İ'": "\ud800"}], {"d": []}, -7]}]
    for _ in range(40):
        tools_in.append({"mcp": [rng.choice([rng.uniform(-1e20, 1e20), rng.random() * 10 ** rng.randint(-30, 30),
                                             float(rng.randint(-10**6, 10**6)), rng.randint(-10**20, 10**20)])
                                 for _ in range(3)]})
    for _ in range(300):
        t: dict[str, Any] = {}
        for k in ledger.TOOL_KEYS:
            if rng.random() < 0.7:
                t[k] = rng.choice([True, False, 0, 1, "", "no", None])
        if rng.random() < 0.8:
            t["mcp"] = [rng.choice(["a", "b", "c", "*", "", "srv-\u00e9", "Z"]) for _ in range(rng.randint(0, 4))]
        tools_in.append(t)
    nt = [[enc(t), outcome(lambda t=t: ledger.norm_tools(copy.deepcopy(t)))] for t in tools_in]

    dirs_in: list[Any] = [None, [], "ab", ["C:/x", "c:" + BS + "X", " C:/x ", ""], [{"path": " a "}, {"path": "a", "mode": "ro"}],
                          [{"path": "a", "mode": "rx"}, {"mode": "rw"}, {"path": "b", "mode": None}],
                          [{"path": 5}], [7], [None], {"C:/a": 1, "c:/b": 2},
                          [{"path": "C:" + BS + "a" + BS + "..", "mode": "rw"}, {"path": "C:/", "mode": "ro"}],
                          [{"path": "\u0130", "mode": "rw"}, {"path": "i\u0307", "mode": "rw"}, {"path": "\u212a", "mode": "ro"}, {"path": "k"}],
                          [{"path": "b", "mode": "rw"}, {"path": "b", "mode": "ro"}, {"path": "B", "mode": "ro"}]]
    for _ in range(400):
        ds = []
        for _ in range(rng.randint(0, 6)):
            p = rand_path(rng, pool)
            if rng.random() < 0.3:
                ds.append(p)
            else:
                d: dict[str, Any] = {"path": rng.choice([p, " " + p + "\t", p.upper()])}
                if rng.random() < 0.9:
                    d["mode"] = rng.choice(["rw", "ro", "ro", "RW", ""])
                ds.append(d)
        if ds and rng.random() < 0.3:
            ds.append(copy.deepcopy(rng.choice(ds)))
        dirs_in.append(ds)
    nd = [[enc(d), outcome(lambda d=d: ledger.norm_dirs(copy.deepcopy(d)))] for d in dirs_in]

    em = []
    names = ["a", "b", "c", "*", "\u00e9", "\ud800"]
    for _ in range(300):
        def lst():
            r = rng.random()
            if r < 0.15:
                return None
            return [rng.choice(names) for _ in range(rng.randint(0, 4))]
        g, c, reg = lst(), lst(), lst()
        em.append([enc(g), enc(c), enc(reg), outcome(lambda g=g, c=c, reg=reg: ledger.expand_mcp(g, c, reg))])
    return nt, nd, em


def outcome(call) -> dict:
    r = run(call)
    if "ok" in r:
        r["ok"] = enc(r["ok"])
    return r


def dirs_list(rng: random.Random, pool: list[str], n: int, prefix: list[str]) -> list[dict]:
    out = []
    for _ in range(n):
        base = rng.choice(prefix)
        tail = rand_path(rng, pool) if rng.random() < 0.3 else rng.choice(["", "a", "a/b", "A" + BS + "B", "..", "a/..", "\u0130", "i", "\u212a"])
        out.append({"path": base + (rng.choice([BS, "/"]) + tail if tail else ""), "mode": rng.choice(["rw", "ro", "ro", "rX"])})
    return out


def section_clamps(ledger, rng: random.Random, pool: list[str]) -> tuple[list, list]:
    Org = ledger.Org
    roots = ["C:" + BS + "work", "c:/WORK", "C:" + BS + "work" + BS, "C:" + BS + "wor", "C:" + BS + "work" + BS + "sub",
             BS + BS + "srv" + BS + "share", "//SRV/share/x", "C:" + BS + "\u0130", "C:" + BS + "i", "C:" + BS + "\u212a",
             "C:" + BS + "k", "D:", "C:", "C:" + BS, "rel", ".", "C:" + BS + "work" + BS + "..", "C:" + BS + "\ud800",
             "C:" + BS + "\U00010400", "C:" + BS + "\U00010428"]
    ct = []
    whos = ["parent", "the parent", "you", "\u00e9"]
    for _ in range(600):
        req: Any = {}
        for k in ledger.TOOL_KEYS:
            if rng.random() < 0.6:
                req[k] = rng.choice([True, False, 1, 0])
        if rng.random() < 0.85:
            req["mcp"] = [rng.choice(["a", "b", "c", "*", "\u0130"]) for _ in range(rng.randint(0, 3))]
        if rng.random() < 0.1:
            req = rng.choice([None, {}, "", 0])
        par: Any = {}
        for k in ledger.TOOL_KEYS:
            if rng.random() < 0.6:
                par[k] = rng.choice([True, False, 1, 0, None])
        if rng.random() < 0.85:
            par["mcp"] = rng.choice([[rng.choice(["a", "b", "*", "\u0130"]) for _ in range(rng.randint(0, 3))], "ab", "*", []])
        if rng.random() < 0.1:
            par = None
        strict = rng.random() < 0.4
        who = rng.choice(whos)
        ct.append([enc(req), enc(par), strict, enc(who),
                   outcome(lambda req=req, par=par, strict=strict, who=who:
                           Org._clamp_tools(copy.deepcopy(req), copy.deepcopy(par), strict, who))])
    for req, par in [({"mcp": ["x"]}, {"mcp": None}), ({"mcp": ["*"]}, {"mcp": [["x"]]}), ({"mcp": ["x"]}, {"mcp": 5})]:
        ct.append([enc(req), enc(par), False, "parent",
                   outcome(lambda req=req, par=par: Org._clamp_tools(req, par, False))])

    cd = []
    for _ in range(900):
        reqd = [{"path": p, "mode": m} for p, m in
                ((d["path"], d["mode"]) for d in dirs_list(rng, pool, rng.randint(0, 4), roots))]
        if rng.random() < 0.1:
            pmap = None
        else:
            pmap = {d["path"]: d["mode"] for d in dirs_list(rng, pool, rng.randint(0, 4), roots)}
        strict = rng.random() < 0.35
        who = rng.choice(whos)
        cd.append([enc(reqd), None if pmap is None else [[enc(k), enc(v)] for k, v in pmap.items()], strict, enc(who),
                   outcome(lambda reqd=reqd, pmap=pmap, strict=strict, who=who:
                           Org._clamp_dirs(copy.deepcopy(reqd), pmap, strict, who))])
    return ct, cd


class Scratch:
    """A synthetic Org whose kiosk ceiling, tier table and one parent node
    are exactly what a row asks for."""

    def __init__(self, ledger):
        self.ledger = ledger
        base = ledger.Org.create("oracle-scope")
        self.doc = base.d

    def org(self, *, max_scope: Any = "absent", tiers: dict | None = None, parent_scope: dict | None = None):
        d = copy.deepcopy(self.doc)
        org = self.ledger.Org(d)
        if max_scope == "absent":
            org.d.pop("kiosk", None)
        else:
            org.d["kiosk"] = {"max_scope": max_scope}
        if tiers is not None:
            org.d["tiers"] = tiers
        # in place: the Org may hold a reference to the node table
        org.d["nodes"].clear()
        if parent_scope is not None:
            org.d["nodes"]["par"] = {"scope": parent_scope}
        self.logs: list = []
        orig = org._log

        def log(*a, **k):
            self.logs.append(a[0])
            return None
        org._log = log
        _ = orig
        return org


def section_ceiling(ledger, sc: Scratch, rng: random.Random, pool: list[str]) -> tuple[list, list, list]:
    VIS, PM = list(ledger.VIS_LEVELS), list(ledger.PM_LEVELS)
    roots = ["C:" + BS + "work", "c:/WORK/x", "C:" + BS + "\u0130", "C:" + BS + "i", BS + BS + "srv" + BS + "sh", "D:" + BS]
    cv = []
    for req in VIS + ["weird", None, 3]:
        for pv in VIS + ["absent", "odd", None]:
            for strict in (False, True):
                scope = {} if pv == "absent" else {"org_visibility": pv}
                org = sc.org(parent_scope=scope)
                cv.append([enc(req), enc(pv), strict, outcome(lambda org=org, req=req, strict=strict: list(org._clamp_vis(req, "par", strict)))])
        org = sc.org()
        cv.append([enc(req), "no-parent", True, outcome(lambda org=org, req=req: list(org._clamp_vis(req, None, True)))])

    ac = []
    for i in range(700):
        ms: Any
        r = rng.random()
        if r < 0.1:
            ms = rng.choice(["absent", None, {}])
        else:
            ms = {"tools": {k: rng.choice([True, False, 0, 1]) for k in ledger.TOOL_KEYS if rng.random() < 0.7}}
            ms["tools"]["mcp"] = rng.choice([["a"], ["*"], [], ["a", "b"], ["\u0130"]])
            if rng.random() < 0.8:
                ms["add_dirs"] = dirs_list(rng, pool, rng.randint(0, 3), roots)
                for d in ms["add_dirs"]:
                    d["mode"] = rng.choice(["rw", "ro"])
            if rng.random() < 0.8:
                ms["org_visibility"] = rng.choice(VIS + ["odd"])
            if rng.random() < 0.8:
                ms["permission_mode"] = rng.choice(PM + ["odd"])
            if rng.random() < 0.05:
                del ms["tools"]["mcp"]
            if rng.random() < 0.05:
                del ms["tools"]
        tools = None if rng.random() < 0.2 else {k: rng.choice([True, False]) for k in ledger.TOOL_KEYS if rng.random() < 0.7} | (
            {"mcp": rng.choice([["a"], ["*"], ["b", "c"], [], ["\u0130", "a"]])} if rng.random() < 0.9 else {})
        dirs = None if rng.random() < 0.25 else [{"path": d["path"], "mode": rng.choice(["rw", "ro"])}
                                                  for d in dirs_list(rng, pool, rng.randint(0, 3), roots)]
        if dirs and rng.random() < 0.2:
            dirs.append(copy.deepcopy(dirs[0]))
        vis = rng.choice([None] + VIS + ["odd"])
        pm = rng.choice([None] + PM + ["odd"])
        raise_c = rng.random() < 0.35
        org = sc.org(max_scope=copy.deepcopy(ms))
        warnings: list = []

        def call(org=org, tools=tools, dirs=dirs, vis=vis, pm=pm, raise_c=raise_c, warnings=warnings):
            t, d, v, p, b = org._apply_ceiling(tools=copy.deepcopy(tools), dirs=copy.deepcopy(dirs), vis=vis, pm=pm,
                                               raise_ceiling=raise_c, warnings=warnings)
            # the ceiling a raise wrote back; only when a ceiling was in force
            after = org.kiosk_ceiling() if raise_c and ms not in ("absent", None) and ms else None
            return {"tools": t, "dirs": d, "vis": v, "pm": p, "bridged": b, "warnings": list(warnings),
                    "raised": None if not raise_c or after is None else after, "logged": list(sc.logs)}
        ac.append({"max_scope": enc(ms), "tools": enc(tools), "dirs": enc(dirs), "vis": enc(vis), "pm": enc(pm),
                   "raise": raise_c, **outcome(call)})

    # a ceiling listing one folder twice: the clamp's {path: mode} map keeps
    # the LAST mode, and a raise upgrades the LAST entry in place
    dup = [{"path": "C:" + BS + "w", "mode": "ro"}, {"path": "C:" + BS + "w", "mode": "rw"}]
    dup2 = [{"path": "C:" + BS + "w", "mode": "ro"}, {"path": "C:" + BS + "w", "mode": "ro"}]
    for dirs_ceiling, req_mode, raise_c in [(dup, "rw", False), (list(reversed(dup)), "rw", False),
                                            (dup2, "rw", True), (dup, "rw", True)]:
        ms = {"tools": {"mcp": ["*"]}, "add_dirs": copy.deepcopy(dirs_ceiling)}
        dirs = [{"path": "c:/W/x", "mode": req_mode}, {"path": "C:" + BS + "w", "mode": req_mode}]
        org = sc.org(max_scope=copy.deepcopy(ms))
        warnings = []

        def call(org=org, dirs=dirs, raise_c=raise_c, warnings=warnings):
            t, d, v, p, b = org._apply_ceiling(dirs=copy.deepcopy(dirs), raise_ceiling=raise_c, warnings=warnings)
            return {"tools": t, "dirs": d, "vis": v, "pm": p, "bridged": b, "warnings": list(warnings),
                    "raised": org.kiosk_ceiling() if raise_c else None, "logged": list(sc.logs)}
        ac.append({"max_scope": enc(ms), "tools": None, "dirs": enc(dirs), "vis": None, "pm": None,
                   "raise": raise_c, **outcome(call)})

    tc = []
    tiers_doc = {"haiku": 1, "or-a-b": 3, "or-cheap": 0.1, "or-bool": True, "or-str": "3", "or-big": 10**30, "or-eq": 1.0,
                 "or-zero": 0}
    tier_names = list(ledger.TIERS) + ["or-a-b", "or-cheap", "or-bool", "or-str", "or-big", "or-eq", "or-zero", "or-missing",
                                       "nope", "\u0130", "\ud800"]
    for mt in list(ledger.TIERS) + [None, "absent", "or-a-b", "bogus", 5, "HAIKU"]:
        for tier in tier_names:
            ms: Any = "absent" if mt == "absent" else {"max_tier": mt}
            org = sc.org(max_scope=ms, tiers=copy.deepcopy(tiers_doc))
            tc.append([enc(mt), enc(tier), outcome(lambda org=org, tier=tier: org._check_tier_ceiling(tier))])
    return cv, ac, tc


# ---------------------------------------------------------------- driver
def anchors(repo: Path) -> dict[str, str]:
    return {p: hashlib.sha256((repo / p).read_bytes()).hexdigest() for p in ANCHORED}


def build(repo: Path) -> tuple[dict, str]:
    if sys.version_info[:2] != REQUIRED_PYTHON or os.name != "nt":
        raise SystemExit(f"run with the engine runtime Python {REQUIRED_PYTHON} on Windows, not {sys.version}")
    sys.path.insert(0, str(repo / "engine" / "backend"))
    from orgtree import ledger  # noqa: PLC0415

    if os.path.normcase is not ntpath.normcase or "_LCMapStringEx" not in ntpath.normcase.__code__.co_names:
        raise SystemExit("oracle stopped: ntpath.normcase is no longer LCMapStringEx; review the model")
    if ledger.TOOL_KEYS != ("bash", "web", "edit", "subagents") or \
            ledger.VIS_LEVELS != ("self", "team", "subtree", "full") or \
            ledger.PM_LEVELS != ("plan", "default", "acceptEdits", "bypassPermissions"):
        raise SystemExit("oracle stopped: ledger level constants moved; review the model")
    tables, stamp, lower = capture_tables(ledger)
    pool = char_pool(lower)
    rng = random.Random(20260923)
    normp, normc, reprs, strips = section_paths(rng, pool)
    nt, nd, em = section_norm(ledger, rng, pool)
    ct, cd = section_clamps(ledger, rng, pool)
    sc = Scratch(ledger)
    cv, ac, tc = section_ceiling(ledger, sc, rng, pool)
    doc: dict[str, Any] = {
        "schema": SCHEMA,
        "oracle": {"python": stamp["python"], "windows": stamp["windows"], "tables_sha256": stamp["sha256"],
                   "anchors": anchors(repo)},
        "limits": ("Synthetic inputs only. Expected values are current Python behavior on this Windows build, "
                   "not a new contract."),
        "normpath": normp, "normcase": normc, "repr": reprs, "strip": strips,
        "norm_tools": nt, "norm_dirs": nd, "expand_mcp": em,
        "clamp_tools": ct, "clamp_dirs": cd, "clamp_vis": cv,
        "apply_ceiling": ac, "tier_ceiling": tc,
    }
    return doc, tables


def render(doc: dict) -> str:
    """One row per line so a changed vector shows up as a readable diff."""
    parts = ["{"]
    keys = list(doc)
    for i, k in enumerate(keys):
        v = doc[k]
        tail = "," if i < len(keys) - 1 else ""
        if isinstance(v, list):
            parts.append(f" {json.dumps(k)}: [")
            for j, row in enumerate(v):
                sep = "," if j < len(v) - 1 else ""
                parts.append("  " + json.dumps(row, ensure_ascii=True, separators=(",", ":")) + sep)
            parts.append(" ]" + tail)
        else:
            parts.append(f" {json.dumps(k)}: " + json.dumps(v, ensure_ascii=True, separators=(",", ":")) + tail)
    parts.append("}")
    return "\n".join(parts) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--repo-root", type=Path, default=CRATE.parents[2])
    ap.add_argument("--vectors", type=Path, default=DEFAULT_VECTORS)
    ap.add_argument("--tables", type=Path, default=TABLES)
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = ap.parse_args()
    with tempfile.TemporaryDirectory(prefix="orgtree-scope-oracle-") as data:
        os.environ["ORGTREE_DATA"] = data
        doc, tables = build(args.repo_root.resolve())
    text = render(doc)
    digest = hashlib.sha256(text.encode()).hexdigest()
    if args.write:
        args.vectors.parent.mkdir(parents=True, exist_ok=True)
        args.vectors.write_text(text, encoding="utf-8", newline="\n")
        args.tables.write_text(tables, encoding="utf-8", newline="\n")
        print(f"wrote {args.vectors} ({len(text)} bytes, sha256 {digest}) and {args.tables}")
        return 0
    bad = []
    if args.vectors.read_text(encoding="utf-8") != text:
        bad.append(str(args.vectors))
    if args.tables.read_text(encoding="utf-8") != tables:
        bad.append(str(args.tables))
    if bad:
        print(f"MISMATCH: {', '.join(bad)} differ from what the current source and host produce")
        return 1
    print(f"matches: {args.vectors} ({len(text)} bytes, sha256 {digest}) and {args.tables}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
