-- PG-0 base schema (PYPG-PLAN §2). Applied once, in a transaction, by
-- pgstore.migrate(), which records this file's sha256 in schema_migrations
-- and refuses to start if an applied file later changes.
--
-- Layout: shared tables in `public`; each org's rows in its own schema
-- `org_<org_id>`, holding exactly the SQLite seam's five tables (store.py
-- _DDL) so store.py's statements run unchanged. `val` is TEXT, not jsonb: the
-- seam's compare-on-save compares serialized JSON byte for byte, and jsonb
-- would reorder keys (losing dict order) and rewrite every row on every save.

CREATE TABLE orgs (
  org_id     bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  slug       text   NOT NULL UNIQUE,
  -- bumped by one in every committed write (org_tx and seam save_org),
  -- in the same transaction as `NOTIFY org_rev, '<slug>:<revision>'`
  revision   bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  deleted_at timestamptz
);

-- org_tx operation receipts: written in the same transaction as the change,
-- so a retry after a lost commit finds its outcome (RT6).
CREATE TABLE receipts (
  org_id      bigint NOT NULL REFERENCES orgs(org_id),
  op_key      text   NOT NULL,
  fingerprint text,
  result      text,
  at          timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (org_id, op_key)
);

-- One org's schema. Called by pgstore when an org is first created.
CREATE FUNCTION orgtree_create_org_schema(p_org_id bigint) RETURNS text
LANGUAGE plpgsql AS $fn$
DECLARE s text := 'org_' || p_org_id;
BEGIN
  EXECUTE format('CREATE SCHEMA %I', s);
  EXECUTE format('CREATE TABLE %I.doc (key text PRIMARY KEY, val text NOT NULL)', s);
  EXECUTE format('CREATE TABLE %I.nodes (id text PRIMARY KEY, ord integer NOT NULL, val text NOT NULL)', s);
  EXECUTE format('CREATE TABLE %I.log_d (seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
                 'sect text NOT NULL, owner text NOT NULL, at text, val text NOT NULL)', s);
  EXECUTE format('CREATE INDEX ix_log_d ON %I.log_d (sect, owner, seq)', s);
  EXECUTE format('CREATE TABLE %I.log_l (seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
                 'sect text NOT NULL, at text, val text NOT NULL)', s);
  EXECUTE format('CREATE INDEX ix_log_l ON %I.log_l (sect, seq)', s);
  EXECUTE format('CREATE TABLE %I.meta (key text PRIMARY KEY, val text NOT NULL)', s);
  RETURN s;
END
$fn$;

-- SQLite's json_extract for the seam's few projection queries. One path
-- returns the value (a string unquoted, anything else as JSON text); several
-- return a JSON array. Paths are the '$.a.b' form store.py uses.
CREATE FUNCTION json_extract(v text, VARIADIC paths text[]) RETURNS text
LANGUAGE sql IMMUTABLE AS $fn$
  SELECT CASE WHEN array_length(paths, 1) = 1 THEN (
           SELECT CASE jsonb_typeof(x) WHEN 'string' THEN x #>> '{}'
                                        WHEN 'null' THEN NULL ELSE x::text END
           FROM (SELECT v::jsonb #> string_to_array(substr(paths[1], 3), '.') AS x) q)
         ELSE (SELECT jsonb_agg(v::jsonb #> string_to_array(substr(p, 3), '.') ORDER BY o)::text
               FROM unnest(paths) WITH ORDINALITY AS t(p, o))
         END
$fn$;
