-- PG-0 × PG-1: the engine connects as `orgtree_runtime` (LOGIN, no superuser,
-- CONNECT + TEMP on the database); migrations run as `orgtree_admin`. So the
-- runtime role gets DML on the shared tables, and each org's schema is created
-- by a SECURITY DEFINER function (running as its owner, the admin) that grants
-- the runtime role DML on the new tables. Every grant is skipped when the role
-- does not exist (a bare test server).

CREATE OR REPLACE FUNCTION orgtree_create_org_schema(p_org_id bigint) RETURNS text
LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public AS $fn$
DECLARE s text := 'org_' || p_org_id;
BEGIN
  EXECUTE format('CREATE SCHEMA %I', s);
  EXECUTE format('CREATE TABLE %I.doc (key text PRIMARY KEY, val text NOT NULL)', s);
  EXECUTE format('CREATE TABLE %I.nodes (id text PRIMARY KEY, ord integer NOT NULL, val text NOT NULL)', s);
  EXECUTE format('CREATE TABLE %I.log_d (seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
                 'sect text NOT NULL, owner text NOT NULL, at text, val text NOT NULL)', s);
  EXECUTE format('CREATE INDEX ix_log_d ON %I.log_d (sect, owner, seq)', s);
  EXECUTE format('CREATE TABLE %I.log_l (seq bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, '
                 'sect text NOT NULL, at text, val text NOT NULL)', s);
  EXECUTE format('CREATE INDEX ix_log_l ON %I.log_l (sect, seq)', s);
  EXECUTE format('CREATE TABLE %I.meta (key text PRIMARY KEY, val text NOT NULL)', s);
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'orgtree_runtime') THEN
    EXECUTE format('GRANT USAGE ON SCHEMA %I TO orgtree_runtime', s);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA %I TO orgtree_runtime', s);
    EXECUTE format('GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA %I TO orgtree_runtime', s);
  END IF;
  RETURN s;
END
$fn$;

REVOKE ALL ON FUNCTION orgtree_create_org_schema(bigint) FROM PUBLIC;

DO $grants$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'orgtree_runtime') THEN
    GRANT USAGE ON SCHEMA public TO orgtree_runtime;
    GRANT SELECT, INSERT, UPDATE, DELETE ON public.orgs, public.receipts TO orgtree_runtime;
    GRANT SELECT ON public.schema_migrations TO orgtree_runtime;
    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO orgtree_runtime;
    GRANT EXECUTE ON FUNCTION orgtree_create_org_schema(bigint) TO orgtree_runtime;
    GRANT EXECUTE ON FUNCTION json_extract(text, text[]) TO orgtree_runtime;
  END IF;
END
$grants$;
