-- Authoritative storage is activated by the verified converter, not by DDL.
-- Existing legacy blobs remain readable until that converter commits.
CREATE FUNCTION public.orgtree_install_receipt_rows(p_org_id bigint) RETURNS void
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE s text := 'org_' || p_org_id;
BEGIN
  IF NOT EXISTS(SELECT 1 FROM public.orgs WHERE org_id=p_org_id) THEN
    RAISE EXCEPTION 'Unknown organization %',p_org_id;
  END IF;
  EXECUTE format('CREATE TABLE IF NOT EXISTS %I.receipt_format('
    'singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),'
    'format integer NOT NULL CHECK(format=1),present boolean NOT NULL,'
    'conversion_sha256 text NOT NULL,converted_owners bigint NOT NULL,'
    'converted_receipts bigint NOT NULL,converted_carriers bigint NOT NULL)',s);
  EXECUTE format('CREATE TABLE IF NOT EXISTS %I.receipt_owners('
    'owner text PRIMARY KEY,ord bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 0 MINVALUE 0),'
    'nrows bigint NOT NULL DEFAULT 0 CHECK(nrows>=0),version bigint NOT NULL DEFAULT 0,'
    'UNIQUE(ord))',s);
  EXECUTE format('CREATE TABLE IF NOT EXISTS %I.receipts('
    'owner text NOT NULL REFERENCES %I.receipt_owners(owner),token text NOT NULL,'
    'ord bigint NOT NULL CHECK(ord>=0),val text NOT NULL,version bigint NOT NULL DEFAULT 1,'
    'PRIMARY KEY(owner,token),UNIQUE(owner,ord))',s,s);
  EXECUTE format('CREATE TABLE IF NOT EXISTS %I.receipt_carriers('
    'owner text NOT NULL,carrier text NOT NULL,token text NOT NULL,'
    'PRIMARY KEY(owner,carrier,token),FOREIGN KEY(owner,token) REFERENCES %I.receipts(owner,token))',s,s);
  EXECUTE format('CREATE INDEX IF NOT EXISTS ix_receipt_carriers_operation ON %I.receipt_carriers(owner,token)',s);
  IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='orgtree_runtime') THEN
    -- Explicit conversion/replacement runs through the same runtime transaction.
    -- Ordinary append callers use orgtree_put_receipt below.
    EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE ON '
      '%I.receipt_format,%I.receipt_owners,%I.receipts,%I.receipt_carriers TO orgtree_runtime',s,s,s,s);
    EXECUTE format('GRANT USAGE,SELECT,UPDATE ON SEQUENCE %I.receipt_owners_ord_seq TO orgtree_runtime',s);
  END IF;
END
$fn$;
REVOKE ALL ON FUNCTION public.orgtree_install_receipt_rows(bigint) FROM PUBLIC;

CREATE FUNCTION public.orgtree_put_receipt(p_org_id bigint,p_owner text,p_token text,
                                          p_value text,p_expected text DEFAULT NULL)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE s text := 'org_' || p_org_id; payload json; old_value text; old_version bigint;
        total bigint; next_version bigint; entry record; marker integer;
BEGIN
  IF NOT EXISTS(SELECT 1 FROM public.orgs WHERE org_id=p_org_id) THEN
    RAISE EXCEPTION 'Unknown organization %',p_org_id;
  END IF;
  payload := p_value::json;
  IF p_owner IS NULL OR p_owner='' OR p_token IS NULL OR p_token=''
     OR json_typeof(payload) IS DISTINCT FROM 'object'
     OR payload->>'node' IS DISTINCT FROM p_owner
     OR payload->>'operation' IS DISTINCT FROM p_token
     OR payload->>'outcome' IS NULL OR payload->>'outcome' NOT IN ('confirmed','reclaimed')
     OR json_typeof(payload->'before') IS DISTINCT FROM 'object'
     OR json_typeof(payload->'identity') IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'Unsupported custody receipt';
  END IF;
  IF json_array_length(payload->'identity')<>3
     OR EXISTS(SELECT key FROM json_each(payload) GROUP BY key HAVING count(*)>1)
     OR EXISTS(SELECT key FROM json_each(payload->'before') GROUP BY key HAVING count(*)>1) THEN
    RAISE EXCEPTION 'Ambiguous custody receipt';
  END IF;
  EXECUTE format('SELECT format FROM %I.receipt_format WHERE singleton',s) INTO marker;
  IF marker IS DISTINCT FROM 1 THEN RAISE EXCEPTION 'Custody receipt conversion incomplete'; END IF;
  -- Fixed order: owner advisory -> owner summary row -> affected receipt.
  -- Callers changing several owners acquire these in sorted owner order.
  PERFORM pg_advisory_xact_lock(hashtext(s),hashtext('receipt-owner:'||p_owner));
  EXECUTE format('SELECT nrows FROM %I.receipt_owners WHERE owner=$1',s) INTO total USING p_owner;
  IF total IS NULL THEN
    EXECUTE format('INSERT INTO %I.receipt_owners(owner) VALUES($1)',s) USING p_owner;
  END IF;
  EXECUTE format('SELECT nrows FROM %I.receipt_owners WHERE owner=$1 FOR UPDATE',s)
    INTO total USING p_owner;
  EXECUTE format('SELECT val,version FROM %I.receipts WHERE owner=$1 AND token=$2 FOR UPDATE',s)
    INTO old_value,old_version USING p_owner,p_token;
  IF old_value=p_value THEN RETURN old_version; END IF;
  IF old_value IS DISTINCT FROM p_expected THEN RAISE EXCEPTION 'Stale custody receipt' USING ERRCODE='40001'; END IF;
  IF old_value IS NULL THEN
    EXECUTE format('INSERT INTO %I.receipts(owner,token,ord,val) VALUES($1,$2,$3,$4) RETURNING version',s)
      INTO next_version USING p_owner,p_token,total,p_value;
    EXECUTE format('UPDATE %I.receipt_owners SET nrows=nrows+1,version=version+1 WHERE owner=$1',s)
      USING p_owner;
  ELSE
    EXECUTE format('UPDATE %I.receipts SET val=$3,version=version+1 WHERE owner=$1 AND token=$2 RETURNING version',s)
      INTO next_version USING p_owner,p_token,p_value;
    EXECUTE format('DELETE FROM %I.receipt_carriers WHERE owner=$1 AND token=$2',s)
      USING p_owner,p_token;
    EXECUTE format('UPDATE %I.receipt_owners SET version=version+1 WHERE owner=$1',s) USING p_owner;
  END IF;
  FOR entry IN SELECT key,value FROM json_each_text(payload->'before') LOOP
    IF entry.key='' OR entry.value !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'Unsupported carrier fingerprint'; END IF;
    EXECUTE format('INSERT INTO %I.receipt_carriers(owner,carrier,token) VALUES($1,$2,$3)',s)
      USING p_owner,entry.key,p_token;
  END LOOP;
  -- Only the first append to an absent section changes its presence marker.
  EXECUTE format('UPDATE %I.receipt_format SET present=true WHERE singleton AND NOT present',s);
  RETURN next_version;
END
$fn$;
REVOKE ALL ON FUNCTION public.orgtree_put_receipt(bigint,text,text,text,text) FROM PUBLIC;

DO $migration$
DECLARE item record;
BEGIN
  FOR item IN SELECT org_id FROM public.orgs ORDER BY org_id LOOP
    PERFORM public.orgtree_install_receipt_rows(item.org_id);
  END LOOP;
END
$migration$;

ALTER FUNCTION public.orgtree_create_org_schema(bigint) RENAME TO orgtree_create_org_schema_before_receipts;
CREATE FUNCTION public.orgtree_create_org_schema(p_org_id bigint) RETURNS text
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $fn$
DECLARE s text;
BEGIN
  s := public.orgtree_create_org_schema_before_receipts(p_org_id);
  PERFORM public.orgtree_install_receipt_rows(p_org_id);
  RETURN s;
END
$fn$;
REVOKE ALL ON FUNCTION public.orgtree_create_org_schema(bigint) FROM PUBLIC;
DO $grant$
BEGIN
  IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='orgtree_runtime') THEN
    GRANT EXECUTE ON FUNCTION public.orgtree_create_org_schema(bigint) TO orgtree_runtime;
    GRANT EXECUTE ON FUNCTION public.orgtree_put_receipt(bigint,text,text,text,text) TO orgtree_runtime;
  END IF;
END
$grant$;
