// realwire.test.tsx — REAL WIRE SHAPES through the REAL client code.
//
// The fixtures in fixtures/real-wire-user-dup.json were generated by the
// actual engine (api.node_chat + api._send_receipt) over a copy of live data —
// not by FakeServer. Every prior ghost/pending suite runs on FakeServer's
// LEGACY shapes (no segments, no `ev`), so the typed-path seams — receipt
// decode gating bindPendingMail, segment validation gating serverMailIds —
// have never been exercised against what the server actually sends. This
// probe closes that gap: if any leg here reds, that seam is the user-message
// duplication.
//
// Run: node tests/run.mjs realwire

import { advance, inAct, mountView, realClock, useFakeClock } from './harness'
import test from 'node:test'
import type { TestContext } from 'node:test'
import assert from 'node:assert/strict'
import { useEffect } from 'react'
import { decodeEventRow } from '../src/events/decode'
import { isSegments, segmentMailIds } from '../src/events/wire'
import {
  addPending, bindPendingMail, refreshConvo, resetConvos, useConvo,
} from '../src/convo'
import type { Convo } from '../src/convo'
// esbuild inlines the JSON at bundle time — the bundle runs from a temp dir,
// so a runtime readFileSync of a test-relative path would miss.
import FIXTURE from './fixtures/real-wire-user-dup.json'

/* eslint-disable @typescript-eslint/no-explicit-any */
const FX: any = FIXTURE

test('REAL WIRE §A: the /message receipt decodes known — the gate on ghost binding', () => {
  const d = decodeEventRow(FX.send_response, 'operator')
  assert.equal(d.kind, 'known',
    'receipt failed decode; ev=' + JSON.stringify(FX.send_response.ev).slice(0, 400))
})

test('REAL WIRE §B: a steered row’s segments validate, and every EV-BEARING mail row yields its id', () => {
  assert.ok(FX.steered_rows.length > 0, 'fixture carries no steered rows')
  let evRows = 0
  for (const row of FX.steered_rows) {
    assert.ok(isSegments(row.segments, 'operator'),
      'isSegments rejected: ' + JSON.stringify(row.segments).slice(0, 700))
    const ids = segmentMailIds(row.segments, 'operator')
    for (const seg of row.segments ?? []) {
      if (seg.kind !== 'mail') continue
      for (const r of seg.rows ?? []) {
        // ⚠ scoped to rows that CARRY a typed event. Live data shows agent-
        // sent steered mail arriving legacy (no `ev`): those rows never mint
        // a mail id here by design — they dedup by row identity, and no
        // ghost ever waits on them (only the user's own sends have ghosts).
        if (!('ev' in r)) continue
        evRows++
        assert.ok(r.id && ids.has(r.id as string),
          'an ev-bearing steered mail row failed to yield its id: ' + JSON.stringify(r).slice(0, 400))
      }
    }
  }
  assert.ok(evRows > 0, 'fixture carries no ev-bearing steered mail rows — the leg proved nothing')
})

test('REAL WIRE §C: a typed transcript user row’s segments validate and yield mail ids', () => {
  assert.ok(FX.typed_user_rows.length > 0, 'fixture carries no typed user rows')
  for (const row of FX.typed_user_rows) {
    assert.ok(isSegments(row.segments, 'operator'),
      'isSegments rejected: ' + JSON.stringify(row.segments).slice(0, 700))
    const ids = segmentMailIds(row.segments, 'operator')
    assert.ok(ids.size > 0, 'typed user row segments yielded no mail ids')
  }
})

test('REAL WIRE §D: a pending_mail row decodes known — serverMailIds counts it', () => {
  assert.ok(FX.pending_rows.length > 0, 'fixture carries no pending rows')
  for (const row of FX.pending_rows) {
    const d = decodeEventRow(row, 'operator')
    assert.equal(d.kind, 'known',
      'pending row failed decode: ' + JSON.stringify(row).slice(0, 700))
  }
})

test('REAL WIRE §E: a ghost bound by the real receipt retires against the real payload', async (t: TestContext) => {
  useFakeClock()
  t.after(async () => { resetConvos(); realClock() })
  const payload = {
    busy: true, queued: 0, responding: true, last_error: null, occupancy: 1000,
    messages: [...FX.typed_user_rows, ...FX.steered_rows],
    live: [], mail_pending: FX.pending_rows.length,
    pending_mail: FX.pending_rows,
  }
  const g = globalThis as unknown as Record<string, unknown>
  g.fetch = () => Promise.resolve({
    ok: true,
    headers: { get: () => null },
    json: () => Promise.resolve(payload),
  })
  const SL = 'org', ND = 'probe-realwire'
  const sink: Convo[] = []
  function View() {
    const c = useConvo(SL, ND)
    useEffect(() => { if (!c.loaded) void refreshConvo(SL, ND) }, [c.loaded])
    sink.push(c)
    return null
  }
  const v = await mountView(<View />, () => sink.length)
  await advance(200)
  assert.ok(sink[sink.length - 1]!.loaded, 'first payload never installed')
  let ghost = 0
  await inAct(() => { ghost = addPending(SL, ND, 'user-dedup probe fixture message') })
  await inAct(() => { bindPendingMail(SL, ND, ghost, FX.send_response) })
  await inAct(() => refreshConvo(SL, ND, { force: true }))
  await advance(300)
  const last = sink[sink.length - 1]!
  assert.equal(last.pending.length, 0,
    'ghost failed to retire against the REAL wire payload; pending=' +
    JSON.stringify(last.pending.map((p) => ({ text: p.text, mailId: p.mailId }))))
  await v.unmount()
})
